Repository wikimedia/wikipedia-ios, pull requests merged in 2018-10, with the labels that each got.

#2669 Utilize centralauth for description editing
  WMF Framework/CommonStrings.swift
  WMF Framework/EventLoggingService.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AFHTTPSessionManager+WMFConfig.m
  Wikipedia/Code/AuthenticationDelegate.swift
  Wikipedia/Code/HTTPCookieStorage+Migration.swift
  Wikipedia/Code/ImageController.swift
  Wikipedia/Code/KeychainCredentialsManager.swift
  Wikipedia/Code/NSHTTPCookieStorage+WMFCloneCookie.h
  Wikipedia/Code/NSHTTPCookieStorage+WMFCloneCookie.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAccountLogin.swift
  Wikipedia/Code/WMFAuthTokenFetcher.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WikidataFetcher.swift
  Wikipedia/Code/Wikipedia-Bridging-Header.h
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.1

#2670 fix funky quotebox widths
  Wikipedia/assets/styleoverrides.css
  www/less/misc.less
Labels: 6.1, Low impact

#2671 sync with upstream CSS
  Wikipedia/assets/abusefilter.css
  Wikipedia/assets/preview.css
  Wikipedia/assets/styles.css
Labels: Low impact

#2673 Fix inability to close settings when navigating from the explore feed card
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/UIBarButtonItem+WMFButtonConvenience.m
  Wikipedia/Code/UIButton+WMFButton.h
  Wikipedia/Code/UIButton+WMFButton.m
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFSearchButton.m
  Wikipedia/Code/WMFSettingsViewController.h
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 6.1

#2674 Fix immediate hide/show of explore tab when changing the setting
  ContinueReadingWidget/WMFTodayContinueReadingWidgetViewController.swift
  WMF Framework/EventLoggingService.swift
  WMF Framework/ExploreFeedPreferencesUpdateCoordinator.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/FontSizeSliderViewController.swift
  Wikipedia/Code/MWKHistoryList.m
  Wikipedia/Code/MWKLanguageLinkController.m
  Wikipedia/Code/MWKSavedPageList.m
  Wikipedia/Code/NSUserDefaults+WMFApplicationDefaults.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListsAlertController.swift
  Wikipedia/Code/ReadingThemesControlsViewController.swift
  Wikipedia/Code/SavedArticlesFetcher.m
  Wikipedia/Code/SearchLanguagesBarViewController.swift
  Wikipedia/Code/SearchSettingsViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/SessionSingleton.m
  Wikipedia/Code/UIApplicationShortcutItem+WMFShortcutItem.m
  Wikipedia/Code/UIViewController+WMFOpenExternalUrl.m
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFContinueReadingContentSource.m
  Wikipedia/Code/WMFFeedContentSource.m
  Wikipedia/Code/WMFFixtureRecording.m
  Wikipedia/Code/WMFImageGalleryViewController.m
  Wikipedia/Code/WMFNearbyContentSource.m
  Wikipedia/Code/WMFReferencePopoverMessageViewController.m
  Wikipedia/Code/WMFSearchFunnel.m
  Wikipedia/Code/WMFSettingsMenuItem.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFWelcomeLanguageTableViewController.swift
  Wikipedia/Code/WMFZeroConfigurationManager.m
  Wikipedia/Code/WebViewController.m
  WikipediaUnitTests/Code/MWKLanguageLinkControllerTests.m
  WikipediaUnitTests/Code/NSUserDefaults+WMFReset.m
  WikipediaUnitTests/Code/WMFNotificationTests.m
Labels: 6.1

#2675 Add missing localization files
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.1, Low impact

#2677 Use correct section index when scrolling to current event card
  Wikipedia/Code/OnThisDayViewController.swift
Labels: 6.1, Low impact

#2678 Show section editor for articles without wikidata items
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.1, Low impact

#2679 Wikidata description editing minor bug fixes
  WMF Framework/WMFArticle+CoreDataProperties.h
  WMF Framework/WMFArticle+CoreDataProperties.m
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia.xcdatamodel/contents
  Wikipedia/Code/DescriptionEditViewController.storyboard
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/MWKArticle.h
  Wikipedia/Code/MWKArticle.m
  Wikipedia/Code/MWKDataObject.m
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticleRequestSerializer.m
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.1, Low impact

#2663 Edit Notifications
  WMF Framework/AsyncOperation.swift
  WMF Framework/CSRFTokenOperation.swift
  WMF Framework/CommonStrings.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/Remote Notifications/Model/RemoteNotification+CoreDataClass.swift
  WMF Framework/Remote Notifications/Model/RemoteNotification+CoreDataProperties.swift
  WMF Framework/Remote Notifications/Model/RemoteNotifications.xcdatamodeld/RemoteNotifications.xcdatamodel/contents
  WMF Framework/Remote Notifications/Model/RemoteNotificationsModelController.swift
  WMF Framework/Remote Notifications/Operations/RemoteNotificationsFetchOperation.swift
  WMF Framework/Remote Notifications/Operations/RemoteNotificationsMarkAsReadOperation.swift
  WMF Framework/Remote Notifications/Operations/RemoteNotificationsOperation.swift
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  WMF Framework/Remote Notifications/RemoteNotificationsController.swift
  WMF Framework/Remote Notifications/RemoteNotificationsOperationsController.swift
  WMF Framework/WMFArticle+Extensions.h
  WMF Framework/WMFArticle+Extensions.m
  WMF Framework/WMFDispatchSourceTimer.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DebugReadingListsViewController.swift
  Wikipedia/Code/MWKArticle.h
  Wikipedia/Code/MWKArticle.m
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/ReadMoreAboutRevertedEditViewController.swift
  Wikipedia/Code/ReadMoreAboutRevertedEditViewController.xib
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAlertManager.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAuthTokenFetcher.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFNotificationsController.h
  Wikipedia/Code/WMFNotificationsController.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFThemeableNavigationController.h
  Wikipedia/Code/WMFThemeableNavigationController.m
  Wikipedia/Code/WikidataDescriptionEditingController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/Third Party Code/RMessage/RMessageView.h
  Wikipedia/Third Party Code/RMessage/RMessageView.m
  Wikipedia/Third Party Code/RMessage/RMessageView.xib
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  WikipediaUnitTests/Fixtures/Obama.json
Labels: 6.1

#2681 Support landscape on description edit intro
  Wikipedia/Code/DescriptionWelcome.storyboard
  Wikipedia/Code/DescriptionWelcomeInitialViewController.swift
Labels: Low impact

#2683 Fix failing article tests
  Wikipedia/Code/MWKArticle.m
  WikipediaUnitTests/Fixtures/Barack_Obama/Article.plist
Labels: Low impact

#2686 Add missing completion
  WMF Framework/ReadingListsAPIController.swift
Labels: 6.1

#2682 Debounce description save button
  Wikipedia/Code/DescriptionEditViewController.swift
Labels: 6.1, Low impact

#2685 Update pagelib to 6.1.4
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  www/package-lock.json
  www/package.json
Labels: 6.1, Low impact

#2688 Use new PeriodicWorker & BackgroundFetcher in remote notifications
  WMF Framework/Remote Notifications/RemoteNotificationsOperationsController.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: Update branch before merging

#2687 Keep top element near top of screen when resizing text
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.m
  Wikipedia/assets/index.js
  www/index-main.js
  www/js/windowResizeScroll.js
Labels: 6.1.1, Low impact

#2691 Fix search highlighting regression on iOS 11.4 non-default themes
  Wikipedia/assets/styleoverrides.css
  www/less/findInPage.less
Labels: 6.1, Low impact, Regression

#2695 Ensure feed cards and detail views are updated when title description changes
  WMF Framework/CacheGroup+CoreDataClass.swift
  WMF Framework/CacheGroup+CoreDataProperties.swift
  WMF Framework/CacheItem+CoreDataClass.swift
  WMF Framework/CacheItem+CoreDataProperties.swift
  WMF Framework/NSManagedObject+Extensions.swift
  WMF Framework/WMFArticle+Extensions.swift
  WMF Framework/WMFArticle+QuadKey.swift
  WMF Framework/WMFContentGroup+Display.swift
  WMF Framework/WMFKeyValue+CoreDataClass.h
  WMF Framework/WMFKeyValue+CoreDataClass.m
  WMF Framework/WMFKeyValue+CoreDataProperties.h
  WMF Framework/WMFKeyValue+CoreDataProperties.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ColumnarCollectionViewControllerLayoutCache.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleFetcher.m
Labels: Low impact

#2697 Fix crash when tapping disambiguation pages
  Wikipedia/Code/WMFArticleViewController.m
Labels: Low impact

#2698 [BUG] Reference highlight misplaced on iPhone X and SE (and others)
  Wikipedia/Code/WebViewController.m
Labels: Low impact

#2696 Move authentication status into Session
  Gemfile.lock
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AuthenticationDelegate.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
Labels: 6.1

#2701 Fix incorrect domain for notifications controller
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  WMF Framework/Remote Notifications/RemoteNotificationsOperationsController.swift
  Wikipedia/Code/Session.swift
Labels: 6.1, Low impact

#2699 Fix iOS 12 article search result vertical centering
  Wikipedia/Code/WebViewController.m
Labels: 6.1, Changes welcome

#2702 Batch mark notifications as read requests
  WMF Framework/Collection+AsyncMap.swift
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Array+Chunked.swift
Labels: 6.1

#2704 Fix reversed blocks in deadline controller performIfBeforeDeadline
  WMF Framework/Remote Notifications/RemoteNotificationsOperationsController.swift
Labels: 6.1, Low impact

#2708 Fix screenshot string matching bug
  WikipediaUITests/XCUIApplication+SnapshotUtilities.swift
Labels: 6.1, Low impact

#2710 Fix 6.1 crashes
  Wikipedia/Code/ReachabilityNotifier.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFImageGalleryViewController.m
Labels: 6.1

#2712 Fix iPad scroll to initial on this day event
  Wikipedia/Code/OnThisDayViewController.swift
Labels: 6.1, Low impact

#2711 Fix description editing cursor jump
  Wikipedia/Code/DescriptionEditViewController.swift
Labels: 6.1, Low impact

#2713 Fix explore feed crash caused by fix for T201211
  Wikipedia/Code/ExploreViewController.swift
Labels: 6.1, Low impact

#2714 Add 10% leeway to periodic timers
  WMF Framework/RepeatingTimer.swift
Labels: 6.1.1

#2718 Remove unneeded recovered reference
  Wikipedia.xcodeproj/project.pbxproj
Labels: 6.1.1

#2717 Bump version to 6.1.1
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: 6.1.1

#2716 Use ProcessInfo.processInfo.beginActivity and endActivity for background tasks
  WMF Framework/Background.swift
  WMF Framework/EventLoggingService.swift
  Wikipedia/Code/ImageController.swift
Labels: 6.1.1

#2715 Specify initial delay and leeway for the periodic worker
  WMF Framework/PeriodicWorker.swift
  WMF Framework/RepeatingTimer.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.1

#2721 Fix wmf_push methods view controller traversal
  Wikipedia/Code/UIViewController+WMFArticlePresentation.m
Labels: 6.1.1

#2722 don't allow editing English wikidata descriptions
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.1, Changes welcome

#2720 Add async map tests & fix out-of-order bugs
  WMF Framework/Collection+AsyncMap.swift
  Wikipedia.xcodeproj/project.pbxproj
  WikipediaUnitTests/Code/Collection+AsyncMapTests.swift
Labels: 6.1.1, Changes welcome

#2723 Fix search 3d touch shortcut
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.1, Changes welcome, Low impact

#2726 Peek/Pop in Places, list view sometimes pops the wrong card/image
  Wikipedia/Code/PlacesViewController.swift
Labels: 6.1.1, Low impact

#2728 Shorter delays, longer timeouts for async map tests
  WikipediaUnitTests/Code/Collection+AsyncMapTests.swift
Labels: 6.1.1, Low impact

#2730 Use semaphore to control access to the results set
  WikipediaUnitTests/Code/Collection+AsyncMapTests.swift
Labels: 6.1.1, Low impact

#2727 Fastlane updates for Jenkins
  fastlane/Fastfile
  fastlane/README.md
Labels: 6.1.1

#2729 [BUG] Missing reading lists hint when article added to list via long press
  Wikipedia/Code/AddArticlesToReadingListViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ReadingListHintController.swift
  Wikipedia/Code/ReadingListHintViewController.swift
  Wikipedia/Code/SaveButtonsController.swift
Labels: 6.1.1, Changes welcome, Low impact

#2731 Use asyncMapToDictionary for fetchArticleSummaryResponsesForArticles
  WMF Framework/Collection+AsyncMap.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/Session.swift
  WikipediaUnitTests/Code/Collection+AsyncMapTests.swift
Labels: 6.1.1

#2732 Consolidate configuration, add local
  WMF Framework/Configuration.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  WMF Framework/String+Domains.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Local (WIP: currently only page summaries).xcscheme
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/MWKLanguageLink.m
  Wikipedia/Code/MWKSite.m
  Wikipedia/Code/NSURL+WMFLinkParsing.h
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/NSURL+WMFMainPage.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleViewController.m
Labels: Changes welcome

#2733 [BUG] Batch selection disappears before user takes action
  WMF Framework/CollectionViewCellActionsView.swift
  WMF Framework/CollectionViewEditController.swift
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/BatchEditSelectView.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsAlertController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: 6.1.1, Changes welcome
