Repository wikimedia/wikipedia-ios, pull requests merged in 2018-04, with the labels that each got.

#2134 Fix leaking view controllers
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/ReadingListHintController.swift
Labels: 5.8

#2155 Fix disappearing "Article queued to be downloaded" label
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8

#2153 Update LICENSE.txt
  LICENSE.txt
Labels: 5.8

#2154 Update README.md
  README.md
Labels: 5.8

#2158 Add short description for app store.
  WMF Framework/CommonStrings.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2161 Update text treatment of number of articles in individual reading lists to be consistent across views and include an empty state
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
Labels: 5.8

#2130 User education for reading lists and account creation: Alerts
  WMF Framework/ReadingList+JSON.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKImage.h
  Wikipedia/Code/MWKImage.m
  Wikipedia/Code/MWKSection.h
  Wikipedia/Code/MWKSectionList.h
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Syncing will resume when internet connection is available.strings
Labels: 5.8

#2145 Estimate how much space will be freed up by erasing all saved articles
  WMF Framework/NSFileManager+DirectorySize.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ImageController.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/eu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/id.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ms.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/vi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 5.8

#2159 Inconsistencies in the bulk edit view
  Wikipedia/Code/BatchEditToolbarViewController.swift
  Wikipedia/Code/SavedViewController.swift
Labels: 5.8

#2162 Hierarchy issues on individual reading list views
  Wikipedia/Code/ReadingListDetailExtendedViewController.swift
  Wikipedia/Code/ReadingListDetailExtendedViewController.xib
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8

#2163 Improve legibility and hierarchy of all list views in Reading lists
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8

#2164 Improve legibility and hierarchy of the All articles view
  Wikipedia/Code/TagCollectionViewCell.swift
Labels: 5.8

#2165 Update to copy on Reading lists settings
  WMF Framework/CommonStrings.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2143 Don't show saved progress icon badge or progress view until there's been at least 2 seconds of progress
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Progress+ProgressUI.swift
  Wikipedia/Code/SavedArticlesFetcherProgressManager.swift
  Wikipedia/Code/SavedProgressViewController.swift
  Wikipedia/Code/SavedTabBarItemProgressBadgeManager.swift
Labels: 5.8

#2168 Fix index out of range crash when creating a new reading list tag
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8

#2166 As a user of reading lists, I would like to be able to quickly and easily refresh my synced reading lists
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedViewController.swift
Labels: 5.8

#2169 Hierarchy issues on individual reading list views followup
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8

#2171 Fix stuck cell highlight on reading list sync
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFSettingsTableViewCell.h
  Wikipedia/Code/WMFSettingsTableViewCell.m
  Wikipedia/Code/WMFSettingsTableViewCell.xib
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2172 Followup: As a user of reading lists, I would like to have a place in Settings to manage my reading list preferences
  Wikipedia/Code/ImageController.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 5.8

#2173 Followup: Inconsistencies in the bulk edit view
  WMF Framework/CollectionViewEditController.swift
  Wikipedia/Code/SavedViewController.swift
Labels: 5.8

#2174 Followup: Improve legibility and hierarchy of the All articles view
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/TagCollectionViewCell.swift
Labels: 5.8

#2175 Update to empty states for individual reading lists
  Wikipedia/Code/ReadingListDetailExtendedViewController.swift
  Wikipedia/Code/ReadingListDetailExtendedViewController.xib
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/UIViewController+WMFEmptyView.h
  Wikipedia/Code/UIViewController+WMFEmptyView.m
  Wikipedia/Code/WMFEmptyView.h
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2179 [BUG] Turn on reading list syncing? panel is presented when sync is already enabled
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 5.8

#2183 Pull to refresh fix
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/SavedViewController.swift
Labels: 5.8, Changes welcome

#2187 [BUG] Logging out causes sync error
  WMF Framework/AuthenticationDelegate.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAuthenticationManager.swift
Labels: 5.8

#2185 update "Erase" button font size to match that of "Update synced reading lists"
  Wikipedia/Code/EraseSavedArticlesView.swift
Labels: 5.8

#2188 Fix strange thumbnail animation on iPhone 7.
  WMF Framework/UIScrollView+Limits.swift
Labels: 5.8

#2189 Drop floating blue line
  Wikipedia/Code/Saved.storyboard
  Wikipedia/Code/WMFUnderlineButton.m
Labels: 5.8

#2190 Make reading list titles bold
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8

#2192 Bottom align tags with the bottom of the image, even if image is hidden
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8

#2193 add missing scrollViewWillEndDragging call
  Wikipedia/Code/ReadingListDetailViewController.swift
Labels: 5.8

#2156 For existing users with over 5000 articles per list, split reading lists with more articles than the limit per list into multiple lists
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2195 Reload cell with sync switch when sync state changes
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
Labels: 5.8

#2199 Fix list exists with the same name check
  Wikipedia/Code/ReadingListsController.swift
Labels: 5.8

#2198 [Design bug] As a user of reading lists, I'd like to see a reminder to sync my reading lists once I have more context about the feature
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 5.8

#2200 Design review updates to saved icon badge
  Wikipedia/Code/SavedTabBarItemProgressBadgeManager.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 5.8

#2194 [Design bug] Missing alerts when turning reading list sync off
  WMF Framework/CommonStrings.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/UILabel+WMFStyling.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFWelcomeIntroductionViewController.swift
  Wikipedia/Images.xcassets/reading-lists-sync-disabled.imageset/Contents.json
  Wikipedia/Images.xcassets/reading-lists-sync-disabled.imageset/articlesync.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2202 [Bug] Sort order doesn't persist after user navigates away from an individual Reading lists
  WMF Framework/ReadingList+CoreDataProperties.swift
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia.xcdatamodel/contents
  Wikipedia/Code/Collection.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2203 Orange dot and "Articles queued to be downloaded" messages not updated (disappearing) on individual reading list screen
  Wikipedia/Code/ReadingListDetailViewController.swift
Labels: 5.8

#2205 Followup: [BUG] "Done" button is disabled when I try to edit details of an empty reading list
  WMF Framework/CollectionViewEditController.swift
  Wikipedia/Code/CollectionViewEditControllerNavigationDelegate+Extensions.swift
  Wikipedia/Code/ReadingListDetailExtendedViewController.swift
  Wikipedia/Code/ReadingListDetailExtendedViewController.xib
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedViewController.swift
Labels: 5.8

#2208 Allow reading list hint views to expand vertically for long strings
  WMF Framework/UIStackView+SubviewVerification.swift
  WMF Framework/WMFCaptchaViewController.swift
  Wikipedia/Code/ReadingListHintController.swift
  Wikipedia/Code/ReadingListHintViewController.swift
  Wikipedia/Code/ReadingListHintViewController.xib
  Wikipedia/Code/SaveButton.swift
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
  Wikipedia/Code/WMFArticleNavigationController.m
Labels: 5.8

#2206 [Bug] Search box does not stay visible during scroll on individual reading list view or All articles view
  WMF Framework/NavigationBar.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NavigationBarHider.swift
  Wikipedia/Code/ReadingListDetailUnderBarViewController.swift
  Wikipedia/Code/ReadingListDetailUnderBarViewController.xib
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/SearchBarExtendedViewController.swift
  Wikipedia/Code/SearchBarExtendedViewController.xib
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFViewController.m
  Wikipedia/Code/WebViewController.m
Labels: 5.8, Changes welcome

#2210 [Design bug] As a user who has already turned reading list sync on, on my account I don't want to be asked to turn reading list sync on when I log in on a new device
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Images.xcassets/reading-lists-sync-enabled-disabled.imageset/Contents.json
  Wikipedia/Images.xcassets/reading-lists-sync-enabled-disabled.imageset/articlesync.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2211 [BUG] "Add to reading list" hint obstructed by keyboard in Search results
  Wikipedia/Code/ReadingListHintController.swift
Labels: 5.8

#2212 [Bug] Sync saved articles toggle appears to be 'on' when not logged in
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFExploreViewController.m
  Wikipedia/Code/WMFLoginViewController.swift
Labels: 5.8

#2219 fix choppy nav bar animation
  Wikipedia/Code/NavigationBarHider.swift
Labels: 5.8

#2220 [BUG] Saved RTL article get weird when you tap "Edit"
  Wikipedia/Code/ArticleCollectionViewCell.swift
Labels: 5.8

#2223 Update strings on Article storage and syncing settings
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8

#2222 [BUG] Batch editing view shows on the left for RTL languages
  Wikipedia/Code/ArticleCollectionViewCell.swift
Labels: 5.8

#2227 Hide progress indicators when user erases all saved articles.
  Wikipedia/Code/SavedArticlesFetcher.m
Labels: 5.8

#2229 [BUG] Batch edit toolbar's position is off in individual reading list view
  Wikipedia/Code/ReadingListDetailViewController.swift
Labels: 5.8

#2230 Fix breaking constraints in detail reading list view
  Wikipedia/Code/ReadingListDetailUnderBarViewController.swift
Labels: 5.8

#2228 Popover panel close button alignment when device lang is RTL
  Wikipedia/Code/ScrollableEducationPanelView.xib
Labels: 5.8

#2235 [BUG] Reading list hint confirmation arrow pointing in wrong direction when device lang is RTL
  Wikipedia/Code/ReadingListHintViewController.swift
Labels: 5.8

#2236 Fix reading list title not appearing in reading list detail modal view
  Wikipedia/Code/ReadingListDetailViewController.swift
Labels: 5.8

#2234 [BUG] Batch editing view shows on the left for RTL languages
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
Labels: 5.8

#2239 Disable danger zone
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 5.8

#2241 Fix Find in page being shown when Read more "Save for later" tapped.
  Wikipedia/Code/ReadingListHintController.swift
Labels: 5.8.1

#2243 Add missing reading lists errors
  WMF Framework/ReadingListsAPIController.swift
Labels: 5.8.1

#2247 Do not make sync fail if API returns readinglists-db-error-already-set-up
  WMF Framework/CSRFTokenOperation.swift
Labels: 5.8.1, Question

#2250 Update version number to 5.8.1
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: 5.8.1

#2249 Fix 'collection was mutated while being enumerated' crash
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/WMFMainPageContentSource.m
Labels: 5.8.1

#2251 Version 5.8.0 (iOS) broke ability to delete single searches
  Wikipedia/Code/RecentSearchesViewController.swift
Labels: 5.8.1

#2244 Investigate calls to reading list API without authenticated user
  WMF Framework/ReadingListsSyncOperation.swift
Labels: 5.8.1

#2253 Fix "ns" namespace API query parameter.
  Wikipedia/Code/NSDictionary+WMFCommonParams.m
Labels: 5.8.1

#2254 [Bug] Bulk edit menu not centered on iPhone X
  WMF Framework/BatchEditToolbarViewController.swift
  WMF Framework/BatchEditToolbarViewController.xib
  WMF Framework/CollectionViewEditController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/BatchEditToolbarViewController.swift
  Wikipedia/Code/CollectionViewEditControllerNavigationDelegate+Extensions.swift
Labels: 5.8.1

#2252 Switch API calls to use new wikidata description source.
  Wikipedia/Code/MWKSearchResult.m
  Wikipedia/Code/NSDictionary+WMFCommonParams.m
  Wikipedia/Code/WMFLocationSearchFetcher.m
  Wikipedia/Code/WMFRandomArticleFetcher.m
  Wikipedia/Code/WMFSearchFetcher.m
Labels: 5.8.1

#2248 Update pagelib to 6.0.1 and use new edit pencil bits
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.swift
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/Gruntfile.js
  www/js/sections.js
  www/package.json
Labels: 5.8.1

#2255 [BUG] Tapping on "Update synced reading lists" alerts the user that reading lists will be synced when they're logged out
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
Labels: 5.8.1, Changes welcome

#2256 [BUG] Tapping on "Update synced reading lists" alerts the user that reading lists will be synced when sync is disabled for their account
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFAccountCreationViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFTwoFactorPasswordViewController.swift
Labels: 5.8.1, Changes welcome, Update branch before merging

#2261 Add test and fixes for localized strings missing substitution context
  WMF Framework/CommonStrings.swift
  Wikipedia/Code/NSDate+WMFRelativeDate.m
  Wikipedia/Code/ReadingListDetailUnderBarViewController.swift
  Wikipedia/Code/ReadingListHintViewController.swift
  Wikipedia/Code/ReadingListsAlertController.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  WikipediaUnitTests/Code/TWNStringsTests.m
Labels: 5.8.1
