Repository wikimedia/wikipedia-ios, pull requests merged in 2018-08, with the labels that each got.

#2534 Fix interitem spacing on explore feed
  WMF Framework/ColumnarCollectionViewLayoutMetrics.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
Labels: 6.0, Low impact

#2533 Update empty state's copy, fix nav bar not showing when adding an article to a list via long press
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Low impact

#2536 Fix search tab title shrinking
  Wikipedia/Code/SearchViewController.swift
Labels: 6.0, Low impact

#2535 [Bug] Long article titles are push the W button off center
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.0, Low impact

#2537 Use preferred language for placeholder, fix sort order of nearby cell
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/WMFNearbyContentSource.m
Labels: 6.0, Low impact

#2539 Re-add 'Create a new list button' to Reading Lists VC
  WMF Framework/NavigationBar.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AddArticlesToReadingListViewController.swift
  Wikipedia/Code/CreateNewReadingListButtonView.swift
  Wikipedia/Code/CreateNewReadingListButtonView.xib
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedViewController.swift
Labels: 6.0

#2540 iOS 10 Fixes
  WMF Framework/NavigationBar.swift
  WMF Framework/Theme.swift
  Wikipedia/Code/SearchViewController.swift
Labels: 6.0

#2542 Don't catch nil reading list entries in ReadingListDetailViewController
  WMF Framework/CollectionViewEditController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ArticleURLProviderEditControllerUpdater.swift
  Wikipedia/Code/DisambiguationPagesViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
Labels: 6.0, Changes welcome, Low impact

#2543 Update MobileWikiAppiOSReadingLists to take position and age
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ReadingListsFunnel.swift
  Wikipedia/Code/SaveButtonsController.swift
Labels: 6.0

#2544 Use semi bold body for create new list button
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/WMFEmptyView.m
Labels: 6.0, Low impact

#2547 Bump feed refresh timeout interval to 60s
  WMF Framework/WMFExploreFeedContentController.m
Labels: 6.0, Low impact

#2548 Use newestVisibleGroupOfKind to ensure only visible cards are selecte…
  FeaturedArticleWidget/FeaturedArticleWidget.swift
  WMF Framework/WMFContentGroup+Extensions.h
  WMF Framework/WMFContentGroup+Extensions.m
Labels: 6.0, Low impact

#2550 Update fastlane
  Gemfile.lock
Labels: 6.0, Low impact

#2551 Add MediaWiki language code mapping
  WMF Framework/MediaWikiAcceptLanguageMapping.json
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NSLocale+WMFExtras.swift
  WikipediaUnitTests/Code/WMFLocaleTests.m
Labels: 6.0

#2554 Remove deployment target override for beta cluster tests
  Wikipedia.xcodeproj/project.pbxproj
Labels: 6.0, Low impact

#2555 Apply explore feed preferences when fetch is completed in the background
  WMF Framework/WMFExploreFeedContentController.m
Labels: 6.0, Low impact

#2557 Increase customization button hit target size
  WMF Framework/ExploreCardCollectionViewCell.swift
Labels: 6.0, Low impact

#2552 Implement feed event logging
  WMF Framework/WMFContentGroup+EventLogging.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/FeedFunnel.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/ReadingListsFunnel.swift
  Wikipedia/Code/SaveButtonsController.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
Labels: 6.0

#2558 T201447 + 3d touch event logging context cleanup
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ExploreViewController.swift
Labels: 6.0, Low impact

#2556 When the app is upgraded, we want to send a new snapshot to MobileWikiAppiOSUserHistory
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/UserHistoryFunnel.swift
Labels: 6.0, Low impact

#2560 Add event logging testing section to readme
  README.md
Labels: 6.0, Changes welcome, Low impact

#2561 Log snapshot after app upgrade when session starts, log feed impression after delay
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/UserHistoryFunnel.swift
Labels: 6.0, Low impact

#2566 Include script and region with Accept-Language header
  Wikipedia/Code/NSLocale+WMFExtras.swift
  WikipediaUnitTests/Code/WMFLocaleTests.m
Labels: 6.0, Low impact

#2564 Event logging fixes
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/FeedFunnel.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListsFunnel.swift
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
Labels: 6.0

#2563 Kick off event logging after migrations are completed
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFNetworkUtilities.m
Labels: 6.0

#2568 Fix Places event logging
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
Labels: 6.0.1, Low impact

#2514 Cleanup AFHTTPSessionManager extensions
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AFHTTPSessionManager+WMFAPI.swift
  Wikipedia/Code/AFHTTPSessionManager+WMFDesktopRetry.h
  Wikipedia/Code/AFHTTPSessionManager+WMFDesktopRetry.m
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/MWKSiteInfoFetcher.m
  Wikipedia/Code/PageHistoryFetcher.swift
  Wikipedia/Code/WMFAccountCreator.swift
  Wikipedia/Code/WMFAccountLogin.swift
  Wikipedia/Code/WMFArticlePreviewFetcher.m
  Wikipedia/Code/WMFArticleRevisionFetcher.m
  Wikipedia/Code/WMFAuthAccountCreationInfoFetcher.swift
  Wikipedia/Code/WMFAuthLoginInfoFetcher.swift
  Wikipedia/Code/WMFAuthTokenFetcher.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFCaptchaResetter.swift
  Wikipedia/Code/WMFCurrentlyLoggedInUserFetcher.swift
  Wikipedia/Code/WMFLocationSearchFetcher.m
  Wikipedia/Code/WMFPasswordResetter.swift
  Wikipedia/Code/WMFRandomArticleFetcher.m
  Wikipedia/Code/WMFRelatedSearchFetcher.m
Labels: 6.0.1, Changes welcome

#2570 Improve eventlogging SearchFunnel on iOS app
  WMF Framework/EventLoggingStandardEventProviding.swift
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFSearchFunnel.h
  Wikipedia/Code/WMFSearchFunnel.m
Labels: 6.0.1, Low impact

#2571 Remove Analytics
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/WMFContentGroup+Analytics.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Analytics.swift
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/DisambiguationPagesViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingThemesControlsViewController.swift
  Wikipedia/Code/SaveButton.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/ShareActivityController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleViewController.h
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.h
  Wikipedia/Code/WMFFeedContentSource.m
  Wikipedia/Code/WMFLanguagesViewController.h
  Wikipedia/Code/WMFLanguagesViewController.m
  Wikipedia/Code/WebViewController.m
Labels: Low impact

#2572 Add compass cell placeholder
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Images.xcassets/compass-w.imageset/Contents.json
  Wikipedia/Images.xcassets/compass-w.imageset/compass-w.pdf
Labels: 6.0.1, Low impact

#2567 Event logging dev debug scheme
  README.md
  WMF Framework/EventLoggingService.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Event Logging Dev Debug.xcscheme
Labels: 6.0.1, Changes welcome

#2573 Fix location cell overlap
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
Labels: 6.0.1, Low impact

#2581 As a user of Detail views, I'd like to be able to close a view from the bottom
  WMF Framework/ColumnarCollectionViewLayout.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/CollectionViewFooter.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0.1, Low impact

#2585 Fix settings vc theme
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 6.0.1, Low impact

#2584 Utilize a consistent sub-section header style on Settings and in the Article footer
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/UITableView+Theme.swift
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/assets/about.html
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/about.html
  www/package-lock.json
  www/package.json
Labels: 6.0.1, Low impact

#2579 Fix jerky tablet TOC toggle animation
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.0.1, Low impact

#2588 Remove unused / outdated cruft
  WMF Framework/NavigationBar.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NSUserActivity+WMFExtensions.m
  Wikipedia/Code/PageHistoryViewController.m
  Wikipedia/Code/SectionEditorViewController.m
  Wikipedia/Code/UICollectionViewFlowLayout+WMFItemSizeThatFits.h
  Wikipedia/Code/UICollectionViewFlowLayout+WMFItemSizeThatFits.m
  Wikipedia/Code/UICollectionViewLayout+AttributeUtils.h
  Wikipedia/Code/UICollectionViewLayout+AttributeUtils.m
  Wikipedia/Code/UITableView+DynamicCellHeight.h
  Wikipedia/Code/UITableView+DynamicCellHeight.m
  Wikipedia/Code/UIViewController+WMFOpenExternalUrl.h
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFBarButtonItemPopoverMessageViewController.m
  Wikipedia/Code/WMFBaseImageGalleryViewController_Subclass.h
  Wikipedia/Code/WMFCollectionViewPageLayout.h
  Wikipedia/Code/WMFCollectionViewPageLayout.m
  Wikipedia/Code/WMFPageCollectionViewController.h
  Wikipedia/Code/WMFPageCollectionViewController.m
  Wikipedia/Code/WMFReferencePopoverMessageViewController.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFWelcomePageViewController.swift
  Wikipedia/Code/WebViewController.m
Labels: 6.0.1, Changes welcome, Low impact

#2586 Fix large iPad article text sizing, npm warnings, and sync upstream CSS
  Wikipedia/assets/about.js
  Wikipedia/assets/abusefilter.css
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.css
  Wikipedia/assets/preview.js
  Wikipedia/assets/styleoverrides.css
  Wikipedia/assets/styles.css
  www/js/clickHandling.js
  www/js/elementLocation.js
  www/js/findInPage.js
  www/js/sections.js
  www/js/utilities.js
  www/less/misc.less
  www/package-lock.json
  www/package.json
Labels: 6.0.1

#2576 As a multilingual user, I'd like to know that I can update my Explore feed language settings via the Languages section of the Settings screen
  WMF Framework/CommonStrings.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/WMFArticleLanguagesSectionFooter.h
  Wikipedia/Code/WMFArticleLanguagesSectionFooter.m
  Wikipedia/Code/WMFArticleLanguagesSectionFooter.xib
  Wikipedia/Code/WMFLanguagesViewController.h
  Wikipedia/Code/WMFLanguagesViewController.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFWelcomeLanguageTableViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0.1

#2582 [BUG] Places header should shrink on scrolling of list view
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/Places.storyboard
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0.1

#2589 Add missing UIGraphicsEndImageContext call
  Wikipedia/Code/WMFArticleNavigationController.m
Labels: 6.0.1, Low impact

#2593 Only show sync error once for multiple errors in a row
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0.1, Low impact

#2594 [BUG] Title missing from reading list hint when tapping article "Read more" save buttons
  Wikipedia/Code/ReadingListHintViewController.swift
Labels: 6.0.1, Low impact

#2595 Add generic string equivalent for reading list hint
  Wikipedia/Code/ReadingListHintViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0.1, Low impact

#2592 [BUG] Can't edit article when arrived via redirect
  Wikipedia/Code/MWKArticle.h
  Wikipedia/Code/MWKArticle.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.0.1

#2596 Remove unused partial image info fetch
  Wikipedia/Code/MWKImageInfoFetcher.h
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/MWKImageInfoResponseSerializer.h
  Wikipedia/Code/MWKImageInfoResponseSerializer.m
Labels: 6.0.1, Low impact

#2597 Bump version to 6.0.1 and update fastlane
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  Gemfile.lock
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: 6.0.1, Low impact

#2598 Fix audio play button first tap bug
  Wikipedia/assets/index.js
  www/js/sections.js
Labels: 6.0.1, Low impact

#2600 Ensure image load completions are called on the main thread
  Wikipedia/Code/ImageControllerCompletionManager.swift
Labels: 6.0.1, Low impact

#2599 [BUG] Missing navigation bar in sub-settings views
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 6.0.1, Low impact

#2601 Update the Settings header to match other existing tab headers
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AboutViewController.h
  Wikipedia/Code/AboutViewController.m
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/AppearanceSettingsViewController.xib
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/DebugReadingListsViewController.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/NotificationSettingsViewController.xib
  Wikipedia/Code/SearchSettingsViewController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.xib
  Wikipedia/Code/SubSettingsViewController.swift
  Wikipedia/Code/SubSettingsViewController.xib
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFSettingsViewController.storyboard
  Wikipedia/Code/WMFViewController.m
Labels: 6.0.1

#2607 Update right aligned collection view cell fonts
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/ArticleCollectionViewCell+ListDisplay.swift
  Wikipedia/Code/ArticleRightAlignedImageCollectionViewCell.swift
Labels: 6.0.1, Low impact

#2608 Fix crash on force unwrap of optional
  WMF Framework/ColumnarCollectionViewLayout.swift
Labels: 6.0.1, Low impact

#2609 Perfomance profiling fixes
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/Theme.swift
  Wikipedia/Code/ImageControllerCompletionManager.swift
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.m
Labels: 6.0.1, Low impact

#2605 Update button styles to be consistent across the app
  Wikipedia/Code/WMFAuthButton.swift
Labels: 6.0.1, Low impact

#2610 Profiling fixes
  WMF Framework/EventLoggingService.swift
  WMF Framework/UIView+SemanticContent.swift
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/CircledRankView.swift
Labels: 6.0.1, Low impact

#2611 Reinstate the feed layout cache with fixes for invalidation by content group and article
  WMF Framework/ExploreCardCollectionViewCell.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ColumnarCollectionViewControllerLayoutCache.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: 6.0.1

#2613 Fix 6.0.1 crash
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: 6.0.1

#2614 Xcode 10 compiler error fixes
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/DetailTransition.swift
  Wikipedia/Code/ImageController.swift
  Wikipedia/Code/ImageDownload.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/PageHistorySection.swift
  Wikipedia/Code/SaveButton.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/TableOfContentsAboutThisArticleItem.swift
  Wikipedia/Code/TableOfContentsReadMoreItem.swift
Labels: 6.0.1, Low impact, Update branch before merging

#2615 Remove card shadows from older devices
  WMF Framework/DeviceInfo.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/Theme.swift
  Wikipedia.xcodeproj/project.pbxproj
Labels: 6.0.1

#2616 Move SaveButton to ArticleFullWidthImageCollectionViewCell because it's unused elsewhere
  FeaturedArticleWidget/FeaturedArticleWidget.swift
  WMF Framework/ArticleCollectionViewCell+Themeable.swift
  Wikipedia/Code/ArticleCollectionViewCell+ListDisplay.swift
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
  Wikipedia/Code/ArticleRightAlignedImageCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
Labels: 6.0.1, Low impact

#2617 Only show save button on random and page with preview (featured article)
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
Labels: 6.0.1, Low impact

#2618 Fix places search suggestion & empty view layout issues
  Wikipedia/Code/PlaceSearchSuggestionController.swift
  Wikipedia/Code/PlacesViewController.swift
Labels: 6.0.1

#2619 Sync with upstream css
  Wikipedia/assets/abusefilter.css
  Wikipedia/assets/preview.css
  Wikipedia/assets/styles.css
Labels: 6.0.1, Low impact

#2623 Fix batch edit toolbar's height
  Wikipedia/Code/CollectionViewEditControllerNavigationDelegate+Extensions.swift
Labels: Low impact

#2622 Add max aspect ratio for side scrolling cell images
  Wikipedia/Code/NewsCollectionViewHeader.xib
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
Labels: 6.0.1, Low impact

#2625 Fix landscape infobox width on large devices
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/package-lock.json
  www/package.json
Labels: 6.0.1, Low impact

#2626 Detail view design tweaks
  Wikipedia/Code/OnThisDayViewControllerHeader.xib
  Wikipedia/Code/ViewController.swift
Labels: 6.0.1, Low impact

#2620 Fix panel button long translation text wrapping
  WMF Framework/SetupButton.swift
  WMF Framework/UIView+SemanticContent.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AlignedImageButton.swift
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
  Wikipedia/Code/AutoLayoutSafeMultiLineButton.swift
  Wikipedia/Code/ScrollableEducationPanelView.xib
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
  Wikipedia/Code/UIButton+WMFMultiLineHeight.swift
  Wikipedia/Code/WMFBorderButton.h
  Wikipedia/Code/WMFBorderButton.m
Labels: 6.0.1, Changes welcome, Low impact

#2627 Narrower width for flow layout cells
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
Labels: 6.0.1, Low impact

#2628 Fix edit toolbar height
  WMF Framework/BatchEditToolbarViewController.xib
  Wikipedia/Code/CollectionViewEditControllerNavigationDelegate+Extensions.swift
Labels: 6.0.1, Low impact

#2624 [BUG] Long "Saved > All articles" tab text truncated in middle
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Saved.storyboard
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/UnderlineButton.swift
  Wikipedia/Code/WMFUnderlineButton.h
  Wikipedia/Code/WMFUnderlineButton.m
Labels: 6.1, Low impact

#2569 Update screenshots to work with 6.x UI changes
  Wikipedia/Code/WMFSettingsTableViewCell.xib
  WikipediaUITests/README.md
  WikipediaUITests/SnapshotHelper.swift
  WikipediaUITests/SnapshotRecorderTests.swift
  WikipediaUITests/XCUIApplication+SnapshotUtilities.swift
Labels: 6.1, Low impact
