Repository wikimedia/wikipedia-ios, pull requests merged in 2018-12, with the labels that each got.

#2798 Disable description editing for enwiki
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: Changes welcome, Low impact

#2800 Simplify app scheme URL format
  Wikipedia/Code/NSURL+WMFSchemeHandler.h
  Wikipedia/Code/NSURL+WMFSchemeHandler.m
  Wikipedia/Code/WMFURLSchemeHandler.h
  Wikipedia/Code/WMFURLSchemeHandler.m
  Wikipedia/Code/WebViewController.m
  WikipediaUnitTests/Code/ImageProxyParsingTests.m
  WikipediaUnitTests/Code/NSURL+WMFProxyServerTests.m
Labels: 6.2

#2803 Fix random feed cards
  WMF Framework/WMFLegacySerializer.h
  WMF Framework/WMFLegacySerializer.m
  Wikipedia/Code/WMFRandomArticleFetcher.m
Labels: 6.2, Low impact

#2801 update fastlane snapshot helper file
  WikipediaUITests/SnapshotHelper.swift
Labels: 6.2, Low impact

#2805 Fix thread safety of asyncMap and asyncCompactMap
  WMF Framework/Collection+AsyncMap.swift
  WikipediaUnitTests/Code/Collection+AsyncMapTests.swift
Labels: 6.2

#2806 Fixed settings navigation controller after turning on explore feed
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.2, Low impact

#2807 Add Salman Jamil to contributors
  Wikipedia/Code/AboutViewController.plist
Labels: 6.2, Low impact

#2809 Remove unnecessary double space in a localizable string
  Wikipedia/Code/DescriptionHelpViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
Labels: 6.2, Low impact

#2814 Add "undo" and "redo"
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewWithEditToolbar.swift
  Wikipedia/Images.xcassets/redo.imageset/Contents.json
  Wikipedia/Images.xcassets/redo.imageset/redo.pdf
  Wikipedia/Images.xcassets/separator.imageset/Contents.json
  Wikipedia/Images.xcassets/separator.imageset/separator.pdf
  Wikipedia/Images.xcassets/undo.imageset/Contents.json
  Wikipedia/Images.xcassets/undo.imageset/undo.pdf
Labels: WIP
