Repository wikimedia/wikipedia-ios, pull requests merged in 2018-11, with the labels that each got.

#2737 [BUG] The highlight tap state of the 'Save for later' bookmark icon on default is black instead of blue
  Wikipedia/Code/SaveButton.swift
Labels: 6.1.1, Low impact

#2738 Fix gallery issues (SVG loading)
  Wikipedia/Code/MWKImageInfo.m
Labels: 6.1.1, Low impact

#2739 Fix event logging errors in MobileWikiAppiOSSearch
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/WMFSearchFunnel.h
  Wikipedia/Code/WMFSearchFunnel.m
Labels: 6.1.1, Low impact

#2740 Mitigate 0xdead10cc crashes
  WMF Framework/Background.swift
  WMF Framework/BackgroundFetcher.swift
  WMF Framework/EventLoggingService.swift
  WMF Framework/PeriodicWorker.swift
  WMF Framework/WMFArticle+Extensions.swift
  WMF Framework/WorkerController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ImageController.swift
  Wikipedia/Code/ImageControllerCompletionManager.swift
  Wikipedia/Code/SavedArticlesFetcher.m
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.1

#2741 [BUG] Misplaced close button in the "Create a new list" view
  Wikipedia/Code/ReadingListsViewController.swift
Labels: 6.1.1, Low impact

#2742 [BUG] Batch edit toolbar stays visible after batch editing is done
  WMF Framework/CollectionViewEditController.swift
Labels: 6.1.1, Low impact, Regression

#2745 Fix Zero alert crash
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.1, Low impact

#2746 Fix crash when creating AddArticlesToReadingList VC with nil article
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.1.1, Low impact

#2748 Fix wmf_wiki string
  Wikipedia/Code/URL+WMFLinkParsing.swift
Labels: 6.1.1, Low impact

#2749 Fix tap highlight regression
  WMF Framework/Theme.swift
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/ArticleRightAlignedImageCollectionViewCell.swift
  Wikipedia/Code/CollectionViewCell.swift
  Wikipedia/Code/NewsCollectionViewCell.swift
  Wikipedia/Code/OnThisDayExploreCollectionViewCell.swift
  Wikipedia/Code/RankedArticleCollectionViewCell.swift
Labels: 6.1.1, Low impact

#2750 Fix talk page URL creation
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.1.1, Low impact

#2743 [BUG] Login status incorrect when changing password (or when cookies expire)
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Images.xcassets/logged-out-warning.imageset/Contents.json
  Wikipedia/Images.xcassets/logged-out-warning.imageset/group13.pdf
  Wikipedia/Images.xcassets/relogin-failed.imageset/relogin-failed.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ast.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/el.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/eu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fa.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/gl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/id.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/is.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ja.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ms.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/my.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sr-EC.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sr-el.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/vi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.1.1

#2747 Fix toolbar and tabbar animation issues
  WMF Framework/Theme.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DetailTransition.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ReadingListHintController.swift
  Wikipedia/Code/UINavigationController+WMFHideEmptyToolbar.h
  Wikipedia/Code/UINavigationController+WMFHideEmptyToolbar.m
  Wikipedia/Code/UIViewController+WMFArticlePresentation.m
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/ViewControllerTransitionsController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleNavigationController.h
  Wikipedia/Code/WMFArticleNavigationController.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFRandomArticleViewController.m
  Wikipedia/Code/WMFViewController.h
  Wikipedia/Code/WMFViewController.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
Labels: 6.1.1

#2752 Fix wikidata editing of mismatched title cases
  WMF Framework/Configuration.swift
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.1.1

#2753 Fix theme regression - ensure all top level VCs are themed
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.1, Low impact

#2754 Fix constraint warning - deactivate before activating constraints
  Wikipedia/Code/WMFViewController.m
Labels: 6.1.1, Low impact

#2755 Fix missing random button when tapping back through random article stack
  Wikipedia/Code/WMFRandomArticleViewController.m
Labels: 6.1.1, Low impact

#2756 Fix theme issues
  WMF Framework/Theme.swift
  Wikipedia/Code/DescriptionEditViewController.swift
Labels: 6.1.1, Low impact

#2757 Update fastlane
  Gemfile.lock
Labels: Low impact

#2759 Pop to root view controller when switching to search to ensure search is visible
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.1

#2758 Fix event logging crash on willEnterForeground
  WMF Framework/EventLoggingService.swift
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.1

#2760 Fix incorrect highlighting of invisible find in page matches.
  Wikipedia/assets/index.js
  www/js/findInPage.js
Labels: 6.2

#2763 Update www depedendencies
  Wikipedia/assets/index.js
  www/js/sections.js
  www/package-lock.json
Labels: 6.2, Low impact

#2751 Invisible reading lists after erasing
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
Labels: 6.2

#2762 [OTRS FEATURED REQUEST] Persist sort order of saved articles in the Saved tab across sessions
  WMF Framework/CommonStrings.swift
  Wikipedia/Code/Collection.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: 6.2

#2766 Announcement card updates for 2018 fundraising & format consolidation
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/Configuration.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/String+HTML.swift
  WMF Framework/Theme.swift
  WMF Framework/WMFAnnouncement.h
  WMF Framework/WMFAnnouncement.m
  WMF Framework/WMFAnnouncementsFetcher.m
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/NSString+WMFHTMLParsing.h
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/NewsCollectionViewCell.swift
Labels: 6.1.1

#2769 Add remaining v2 announcement properties
  WMF Framework/WMFAnnouncement.h
  WMF Framework/WMFAnnouncement.m
  WMF Framework/WMFContentGroup+Extensions.m
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
Labels: 6.1.1

#2771 Visual updates for scrollable panels
  Wikipedia/Code/ScrollableEducationPanelView.xib
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
Labels: 6.1.1, Low impact

#2768 Expand local scheme support to all mobileapps services URLs
  WMF Framework/CSRFTokenOperation.swift
  WMF Framework/Configuration.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  WMF Framework/URLComponents+Extensions.swift
  WMF Framework/WMFAnnouncementsFetcher.m
  WMF Framework/WMFContentGroup+Extensions.h
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/WMFOnThisDayEventsFetcher.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Local (WIP: currently only mobile services endpoints).xcscheme
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFFeedContentFetcher.m
  Wikipedia/Code/WMFNetworkUtilities.h
  Wikipedia/Code/WMFNetworkUtilities.m
  Wikipedia/Code/WikidataDescriptionEditingController.swift
  WikipediaUnitTests/Code/ArticleFetcherTests.m
  WikipediaUnitTests/Code/WMFNotificationTests.m
Labels: 6.2, Changes welcome

#2767 TOC selection scrolling offset fixes
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/WebViewController.m
Labels: 6.2, Regression

#2770 As an iOS app editor, when my edit is published I want to be taken to the changed section in the article
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WebViewController.h
  Wikipedia/Code/WebViewController.m
Labels: 6.2, Low impact

#2774 Reset image view on cell reset
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
Labels: 6.2, Low impact

#2775 Fix wikidata description editing & notifications for certain languages
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.2

#2778 Fix external link loading when explore is disabled
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.2

#2777 Fix history
  Wikipedia/Code/MWKHistoryList.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.2

#2781 Use keyPath based willChangeValue methods instead of string based methods
  WMF Framework/AsyncOperation.swift
  Wikipedia/Code/ReadingListsController.swift
Labels: 6.1.2, Low impact

#2782 Convert feed content fetcher, announcements fetcher, on this day fetcher away from AFNetworking
  WMF Framework/CSRFTokenOperation.swift
  WMF Framework/Configuration.swift
  WMF Framework/NSCharacterSet+WMFLinkParsing.h
  WMF Framework/NSCharacterSet+WMFLinkParsing.m
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  WMF Framework/URLComponents+Extensions.swift
  WMF Framework/WMFAnnouncementsFetcher.m
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/WMFLegacySerializer.h
  WMF Framework/WMFLegacySerializer.m
  WMF Framework/WMFOnThisDayEventsFetcher.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AFHTTPSessionManager+WMFConfig.h
  Wikipedia/Code/AFHTTPSessionManager+WMFConfig.m
  Wikipedia/Code/ImageController.swift
  Wikipedia/Code/ImageControllerCompletionManager.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/NSDateFormatter+WMFExtensions.h
  Wikipedia/Code/NSDateFormatter+WMFExtensions.m
  Wikipedia/Code/NSError+WMFExtensions.h
  Wikipedia/Code/NSURLComponents+WMFLinkParsing.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/URL+WMFLinkParsing.swift
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WMFFeedContentFetcher.m
Labels: 6.2

#2783 Remove AFNetworking from WMFRandomArticleFetcher and WMFLocationSearchFetcher
  WMF Framework/Configuration.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/WMFLegacySerializer.m
  Wikipedia/Code/PlaceSearchService.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFFeedContentFetcher.m
  Wikipedia/Code/WMFFirstRandomViewController.m
  Wikipedia/Code/WMFLocationSearchFetcher.h
  Wikipedia/Code/WMFLocationSearchFetcher.m
  Wikipedia/Code/WMFRandomArticleFetcher.h
  Wikipedia/Code/WMFRandomArticleFetcher.m
  Wikipedia/Code/WMFRandomArticleViewController.m
  Wikipedia/Code/WMFRandomContentSource.m
Labels: 6.2

#2787 add DYLD_PRINT_STATISTICS scheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/DYLD_PRINT_STATISTICS.xcscheme
Labels: 6.2

#2788 fix missing TOC dash
  Wikipedia/Code/NSString+WMFHTMLParsing.m
Labels: 6.2

#2789 Incorporate relevant AFNetworking classes into WMF.framework
  Cartfile
  Cartfile.resolved
  WMF Framework/Third Party/AFNetworking/AFCompatibilityMacros.h
  WMF Framework/Third Party/AFNetworking/AFHTTPSessionManager.h
  WMF Framework/Third Party/AFNetworking/AFHTTPSessionManager.m
  WMF Framework/Third Party/AFNetworking/AFNetworkReachabilityManager.h
  WMF Framework/Third Party/AFNetworking/AFNetworkReachabilityManager.m
  WMF Framework/Third Party/AFNetworking/AFNetworking.h
  WMF Framework/Third Party/AFNetworking/AFSecurityPolicy.h
  WMF Framework/Third Party/AFNetworking/AFSecurityPolicy.m
  WMF Framework/Third Party/AFNetworking/AFURLRequestSerialization.h
  WMF Framework/Third Party/AFNetworking/AFURLRequestSerialization.m
  WMF Framework/Third Party/AFNetworking/AFURLResponseSerialization.h
  WMF Framework/Third Party/AFNetworking/AFURLResponseSerialization.m
  WMF Framework/Third Party/AFNetworking/AFURLSessionManager.h
  WMF Framework/Third Party/AFNetworking/AFURLSessionManager.m
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AFHTTPRequestSerializer+WMFRequestHeaders.h
  Wikipedia/Code/AFHTTPSessionManager+WMFCancelAll.h
  Wikipedia/Code/AFHTTPSessionManager+WMFConfig.h
  Wikipedia/Code/MWKLanguageLinkFetcher.m
  Wikipedia/Code/MWNetworkActivityIndicatorManager.m
  Wikipedia/Code/PageHistoryFetcher.swift
  Wikipedia/Code/PreviewHtmlFetcher.m
  Wikipedia/Code/QueuesSingleton.h
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/WMFApiJsonResponseSerializer.h
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFBaseRequestSerializer.h
  Wikipedia/Code/WMFImageInfoController_Private.h
  Wikipedia/Code/WMFSearchResults+ResponseSerializer.m
  Wikipedia/Code/WikiTextSectionUploader.m
  Wikipedia/Third Party Code/AFNetworking/AFCompatibilityMacros.h
  Wikipedia/Third Party Code/AFNetworking/AFHTTPSessionManager.h
  Wikipedia/Third Party Code/AFNetworking/AFHTTPSessionManager.m
  Wikipedia/Third Party Code/AFNetworking/AFNetworkReachabilityManager.h
  Wikipedia/Third Party Code/AFNetworking/AFNetworkReachabilityManager.m
  Wikipedia/Third Party Code/AFNetworking/AFNetworking.h
  Wikipedia/Third Party Code/AFNetworking/AFSecurityPolicy.h
  Wikipedia/Third Party Code/AFNetworking/AFSecurityPolicy.m
  Wikipedia/Third Party Code/AFNetworking/AFURLRequestSerialization.h
  Wikipedia/Third Party Code/AFNetworking/AFURLRequestSerialization.m
  Wikipedia/Third Party Code/AFNetworking/AFURLResponseSerialization.h
  Wikipedia/Third Party Code/AFNetworking/AFURLResponseSerialization.m
  Wikipedia/Third Party Code/AFNetworking/AFURLSessionManager.h
  Wikipedia/Third Party Code/AFNetworking/AFURLSessionManager.m
  WikipediaUnitTests/Code/MWKLanguageLinkFetcherTests.m
  WikipediaUnitTests/Code/MWKSiteInfoFetcherTests.m
  WikipediaUnitTests/Code/WMFSearchFetcherTests.m
  WikipediaUnitTests/Code/WMFSearchResultsSerializationTests.m
Labels: 6.2

#2793 Fix featured article widget margins
  FeaturedArticleWidget/FeaturedArticleWidget.swift
Labels: 6.2, Low impact

#2794 Faster splash screen animation
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.2, Low impact

#2796 Fix announcement card text color
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/String+HTML.swift
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/NSString+WMFHTMLParsing.h
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/NewsCollectionViewCell.swift
Labels: Low impact
