Repository wikimedia/wikipedia-ios, pull requests merged in 2018-06, with the labels that each got.

#2343 Allow multiple languages in the explore feed
  README.md
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKLanguageLinkController.h
  Wikipedia/Code/MWKLanguageLinkController.m
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0

#2346 Add empty string protection for app install id and session id
  WMF Framework/EventLoggingStandardEventProviding.swift
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/WMFKeychainCredentials.swift
Labels: 5.8.2, Low impact

#2347 Update fastfile so it's no longer necessary to select target and config
  Gemfile.lock
  fastlane/Fastfile
Labels: 5.8.2, Low impact

#2349 Time profiler fixes
  WMF Framework/Localization/WMFLocalization.m
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/SaveButton.swift
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
Labels: 5.8.2, Low impact

#2350 Fix widget layout
  ContinueReadingWidget/WMFTodayContinueReadingWidgetViewController.swift
  FeaturedArticleWidget/FeaturedArticleWidget.swift
  TopReadWidget/WMFTodayTopReadWidgetViewController.swift
  WMF Framework/UIFont+WMFDynamicType.swift
Labels: 5.8.2

#2353 Update LibrariesUsed.plist
  Wikipedia/Resources/LibrariesUsed.plist
Labels: 5.8.2

#2314 Fastlane to take screenshots in various langs and simulators.
  .gitignore
  .ruby-version
  WMF Framework/CommonStrings.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/WikipediaUITests.xcscheme
  Wikipedia/Code/LibrariesUsed.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
  Wikipedia/Code/UIBarButtonItem+WMFButtonConvenience.m
  Wikipedia/Code/UIButton+WMFButton.h
  Wikipedia/Code/UIButton+WMFButton.m
  Wikipedia/Code/WMFAccountCreationViewController.swift
  Wikipedia/Code/WMFChangePasswordViewController.swift
  Wikipedia/Code/WMFExploreViewController.m
  Wikipedia/Code/WMFFindInPageKeyboardBar.m
  Wikipedia/Code/WMFForgotPasswordViewController.swift
  Wikipedia/Code/WMFImageGalleryViewController.m
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFSearchViewController.m
  Wikipedia/Code/WMFTwoFactorPasswordViewController.swift
  WikipediaUITests/Info.plist
  WikipediaUITests/SnapshotHelper.swift
  WikipediaUITests/SnapshotRecorderTests.swift
  WikipediaUITests/XCUIApplication+SnapshotUtilities.swift
  fastlane/Snapfile
Labels: Changes welcome

#2348 Fix account messaging & logout status when in airplane mode
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/AuthenticationDelegate.swift
  Wikipedia/Code/WMFAccountLogin.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAuthenticationManager.swift
Labels: 5.8.2

#2354 Move values relevant to event logging into EventLoggingService, persist in event logging db
  WMF Framework/EventCapsule.swift
  WMF Framework/EventLogging.xcdatamodeld/EventLogging.xcdatamodel/contents
  WMF Framework/EventLoggingService.swift
  WMF Framework/EventRecord+CoreDataProperties.swift
  WMF Framework/NSManagedObjectContext+WMFKeyValue.h
  WMF Framework/NSManagedObjectContext+WMFKeyValue.m
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AFHTTPRequestSerializer+WMFRequestHeaders.m
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/EventLogger.h
  Wikipedia/Code/EventLogger.m
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/KeychainCredentialsManager.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/SessionSingleton.h
  Wikipedia/Code/SessionSingleton.m
  Wikipedia/Code/SessionsFunnel.swift
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.m
  Wikipedia/Code/WMFKeychainCredentials.swift
  Wikipedia/Code/WMFSettingsMenuItem.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFWelcomeAnalyticsViewController.swift
  WikipediaUnitTests/Code/ArticleFetcherTests.m
Labels: 5.8.2, Changes welcome

#2355 Remove piwik
  Cartfile
  Cartfile.resolved
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingThemesControlsViewController.swift
  Wikipedia/Code/SaveButtonsController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/ShareActivityController.swift
  Wikipedia/Code/UIViewController+WMFArticlePresentation.m
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFExploreViewController.m
  Wikipedia/Code/WMFFeedContentSource.m
  Wikipedia/Code/WMFSearchViewController.m
  Wikipedia/Code/WebViewController.m
  Wikipedia/Resources/LibrariesUsed.plist
Labels: 5.8.2, Low impact

#2357 Update existing keychain values to kSecAttrAccessibleAfterFirstUnlock
  Wikipedia/Code/WMFKeychainCredentials.swift
Labels: 6.0

#2358 Reduce log spam
  WMF Framework/EventLoggingService.swift
  WMF Framework/WMFAnnouncementsFetcher.m
  WMF Framework/WMFOnThisDayEventsFetcher.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/SavedArticlesFetcher.m
  Wikipedia/Code/WMFArticlePreviewFetcher.m
  Wikipedia/Code/WMFArticleRevisionFetcher.m
  Wikipedia/Code/WMFEnglishFeaturedTitleFetcher.h
  Wikipedia/Code/WMFEnglishFeaturedTitleFetcher.m
  Wikipedia/Code/WMFFeedContentFetcher.m
  Wikipedia/Code/WMFMantleJSONResponseSerializer.h
  Wikipedia/Code/WMFMantleJSONResponseSerializer.m
  Wikipedia/Code/WMFRandomArticleFetcher.m
  Wikipedia/Code/WMFRelatedSearchFetcher.m
  Wikipedia/Code/WMFSearchFetcher.m
  Wikipedia/Code/WMFSearchResults+ResponseSerializer.m
  Wikipedia/Code/WMFZeroConfigurationFetcher.m
  WikipediaUnitTests/Code/WMFENFeaturedTitleFetcherTests.m
Labels: 6.0

#2360 Ensure key values are set
  WMF Framework/EventLoggingService.swift
Labels: 5.8.2, Low impact

#2361 Rename key measure to measure_time for LoginFunnel and SessionsFunnel
  Wikipedia/Code/LoginFunnel.swift
  Wikipedia/Code/SessionsFunnel.swift
Labels: 5.8.2, Changes welcome

#2367 Update collection view layout to have full width date headers for new explore design
  FeaturedArticleWidget/FeaturedArticleWidget.swift
  WMF Framework/ColumarCollectionViewLayoutSection.swift
  WMF Framework/ColumnarCollectionViewLayout.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
  WMF Framework/ColumnarCollectionViewLayoutMetrics.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/CollectionViewCell.swift
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayCollectionViewCell.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
  Wikipedia/Code/SizeThatFitsReusableView.swift
  Wikipedia/Code/WMFCVLAttributes.h
  Wikipedia/Code/WMFCVLAttributes.m
  Wikipedia/Code/WMFCVLColumn.h
  Wikipedia/Code/WMFCVLColumn.m
  Wikipedia/Code/WMFCVLInfo.h
  Wikipedia/Code/WMFCVLInfo.m
  Wikipedia/Code/WMFCVLInvalidationContext.h
  Wikipedia/Code/WMFCVLInvalidationContext.m
  Wikipedia/Code/WMFCVLMetrics.h
  Wikipedia/Code/WMFCVLMetrics.m
  Wikipedia/Code/WMFCVLSectionColumn.h
  Wikipedia/Code/WMFCVLSectionColumn.m
  Wikipedia/Code/WMFColumnarCollectionViewLayout.h
  Wikipedia/Code/WMFColumnarCollectionViewLayout.m
  Wikipedia/Code/WMFEmptySectionCollectionViewCell.h
  Wikipedia/Code/WMFEmptySectionCollectionViewCell.m
  Wikipedia/Code/WMFEmptySectionCollectionViewCell.xib
  Wikipedia/Code/WMFExploreCollectionViewCell.h
  Wikipedia/Code/WMFExploreCollectionViewCell.m
  Wikipedia/Code/WMFFeedContentSource.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
Labels: 6.0, Changes welcome

#2368 Refinements for explore feed design changes: T185954
  WMF Framework/ColumnarCollectionViewLayout.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/UIView+SemanticContent.swift
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/ArticleRightAlignedImageCollectionViewCell.swift
  Wikipedia/Code/CollectionViewCell.swift
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/ColumnarCollectionViewLayoutManager.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SaveButtonsController.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/ShareActivityController.swift
Labels: 6.0, Low impact

#2369 Feed design updates T185954
  Gemfile.lock
  WMF Framework/CollectionViewCellActionsView.swift
  WMF Framework/CollectionViewEditController.swift
  WMF Framework/ColumarCollectionViewLayoutSection.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/UIView+SemanticContent.swift
  WMF Framework/WMFContentGroup+Display.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/DisambiguationPagesViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreHeaderCollectionReusableView.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ImageCollectionViewCell.swift
  Wikipedia/Code/NewsCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/OnThisDayCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/OnThisDayExploreCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/RecentSearchesViewController.swift
  Wikipedia/Code/SaveButton.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/UIScreen+WMFImageWidth.m
  Wikipedia/Code/WMFCompassView.h
  Wikipedia/Code/WMFCompassView.m
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
  fastlane/metadata/ca/description.txt
Labels: 6.0, Low impact

#2370 As an Explore user, I want to be able to control the content I see on that feed
  WMF Framework/CommonStrings.swift
  WMF Framework/HasText.swift
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/BaseExploreFeedSettingsViewController.xib
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/FeedCardSettingsViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKLanguageLink.h
  Wikipedia/Code/MWKLanguageLink.m
  Wikipedia/Code/MWKLanguageLinkController.h
  Wikipedia/Code/MWKLanguageLinkController.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/PlaceSearchFilterListController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFAlertManager.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
  Wikipedia/Code/WMFContentGroupKind+IsInFeed.swift
  Wikipedia/Code/WMFFeedContentSource.m
  Wikipedia/Code/WMFRandomDiceButton.m
  Wikipedia/Code/WMFSearchButton.h
  Wikipedia/Code/WMFSettingsMenuItem.h
  Wikipedia/Code/WMFSettingsMenuItem.m
  Wikipedia/Code/WMFSettingsTableViewCell.h
  Wikipedia/Code/WMFSettingsTableViewCell.m
  Wikipedia/Code/WMFSettingsTableViewCell.xib
  Wikipedia/Code/WMFSettingsViewController.h
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFWelcomeExplorationViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Changes welcome

#2371 Add new explore feed items to the shortest column instead of alternating between columns
  WMF Framework/ColumarCollectionViewLayoutSection.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
Labels: 6.0, Low impact

#2373 Dynamic type fixes
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/ArticleCollectionViewCell.swift
Labels: 6.0, Changes welcome

#2295 Use new pagelib reference collection bits.
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/js/clickHandling.js
  www/js/refs.js
  www/package-lock.json
  www/package.json
Labels: 6.0
