Repository wikimedia/wikipedia-ios, pull requests merged in 2018-05, with the labels that each got.

#2266 Update progress bar string.
  Wikipedia/Code/SavedProgressViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 5.8.1

#2268 Article downloading -> Article download
  Wikipedia/Code/SavedProgressViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  download
Labels: 5.8.1

#2269 [BUG] Swipe actions don't animate properly for RTL cells
  WMF Framework/CollectionViewCellActionsView.swift
Labels: 5.8.1

#2270 Bump pagelib version to get edit pencil pixel push tweaks
  Wikipedia/assets/about.js
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  Wikipedia/assets/wikimedia-page-library-transform.css
  www/package.json
Labels: 5.8.1

#2240 [BUG] Batch edit selection indicator is not centered
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/BatchEditSelectView.swift
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: 5.8.1

#2274 Update NYTPhotoViewer
  Cartfile.resolved
  scripts/carthage_update
Labels: 5.8.1

#2279 Use the same appInstallID for all event logging
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AFHTTPRequestSerializer+WMFRequestHeaders.m
  Wikipedia/Code/EventLogger.m
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/ReadingActionFunnel.h
  Wikipedia/Code/ReadingActionFunnel.m
  Wikipedia/Code/SavedPagesFunnel.h
  Wikipedia/Code/SavedPagesFunnel.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/SessionSingleton.m
  Wikipedia/Code/ToCInteractionFunnel.h
  Wikipedia/Code/ToCInteractionFunnel.m
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.h
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.m
  Wikipedia/Code/WMFHamburgerMenuFunnel.m
  Wikipedia/Code/WMFNetworkUtilities.m
  Wikipedia/Code/WMFSearchFunnel.m
  Wikipedia/Code/WMFShareFunnel.m
  Wikipedia/Code/WMFSuggestedPagesFunnel.m
Labels: 5.8.1

#2275 Fetch & use displaytitle for search results, ensure URL creation is done with title
  WMF Framework/NSRegularExpression+HTML.h
  WMF Framework/NSRegularExpression+HTML.m
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKSearchResult.h
  Wikipedia/Code/MWKSearchResult.m
  Wikipedia/Code/NSString+WMFHTMLParsing.h
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/WMFFirstRandomViewController.m
  Wikipedia/Code/WMFLocationSearchResults.m
  Wikipedia/Code/WMFRandomArticleViewController.m
  Wikipedia/Code/WMFRandomContentSource.m
  Wikipedia/Code/WMFRelatedSearchResults.m
  Wikipedia/Code/WMFSearchFetcher.m
Labels: 5.8.1

#2283 [Bug] iOS app is not sending data to MobileWikiAppSearch
  Wikipedia/Code/WMFSearchViewController.m
Labels: 5.8.1

#2281 Log daily usage when user opts in via Settings
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.m
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 5.8.1

#2288 Keep event logging rate at 1 for WMFSearchFunnel
  Wikipedia/Code/WMFSearchFunnel.m
Labels: 5.8.1, Low impact

#2285 Article save disk error handling
  WMF Framework/ReadingListAlertType.swift
  WMF Framework/WMFArticle+CoreDataProperties.h
  WMF Framework/WMFArticle+CoreDataProperties.m
  WMF Framework/WMFArticle+Errors.swift
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia.xcdatamodel/contents
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKArticle.h
  Wikipedia/Code/MWKArticle.m
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKSection.h
  Wikipedia/Code/MWKSection.m
  Wikipedia/Code/MWKSectionList.h
  Wikipedia/Code/MWKSectionList.m
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesFetcher.h
  Wikipedia/Code/SavedArticlesFetcher.m
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Images.xcassets/error-icon.imageset/Contents.json
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  WikipediaUnitTests/Code/ArticleFetcherTests.m
  WikipediaUnitTests/Code/MWKDataStoreStorageTests.m
  WikipediaUnitTests/Code/MWKSectionHasTextDataTests.m
Labels: 5.8.2

#2287 [Bug] The title of the 'Create new list' view is appearing outside of the header
  Wikipedia/Code/CreateReadingListViewController.swift
  Wikipedia/Code/CreateReadingListViewController.xib
Labels: 5.8.2, Low impact

#2286 [Design bug] The close button on the 'Create a new list' view is on the wrong side
  Wikipedia/Code/CreateReadingListViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
Labels: 5.8.2, Low impact

#2284 Formatting of display title for search results
  WMF Framework/NSRegularExpression+HTML.h
  WMF Framework/NSRegularExpression+HTML.m
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/NSString+WMFHTMLParsing.h
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/SearchResultsViewController.swift
  WikipediaUnitTests/Code/WMFArticleListCellVisualTests.m
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/test0ReferenceOutput_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeGreenBackgroundColorsToBlue_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeReduceLineSpacing_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemoveAllStrikeThroughs_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemovingLink_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrimReference_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrim_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testCentersPresObamasFaceVertically_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageNotCroppedBecauseFacesAreTooSmall_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageShorterThanViewIsNotStretched_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testUsesSpecifiedContentModeBehaviorOnFeaturelessImage_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testBoldAndItalic_10_3_1_LTR_iPad10_3_1_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testBoldAndItalic_10_3_1_LTR_iPhone10_3_1_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testBoldAndItalic_11_3_LTR_iPhone11_3_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldCenterShortTitleWhenDescriptionIsEmpty_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldHighlightMatchingSubstring_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldNotShowLongDescriptionWhenTitleExceedsTwoLines_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldShowLongDescriptionWhenTitleIsShort_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldShowTitleAtTheTopAndDescriptionAtTheBottom_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldTruncateAndShrinkTitle_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_11_2_RTL_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_11_2_RTL_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_11_2_RTL_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_11_2_RTL_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFPicOfTheDayTableViewCellVisualTests/testInitialStateOnlyShowsPlaceholderWithoutCaption_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFPicOfTheDayTableViewCellVisualTests/testShowsCaptionWhenImageIsFinallyDownloaded_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFPicOfTheDayTableViewCellVisualTests/testStillShowsPlaceholderWithoutCaptionWhileImageIsDownloading_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_10_3_1_LTR_iPhone10_3_1_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_10_3_1_RTL_iPad10_3_1_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_10_3_1_RTL_iPhone10_3_1_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_11_2_LTR_iPad11_2_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_11_2_RTL_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_10_3_1_LTR_iPhone10_3_1_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_10_3_1_RTL_iPad10_3_1_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_10_3_1_RTL_iPhone10_3_1_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_11_2_LTR_iPad11_2_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_11_2_LTR_iPhone11_2_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_11_2_RTL_iPhone11_2_375x667@2x.png
  fastlane/Fastfile
Labels: 5.8.2

#2289 Update test configs to 11.3 from 11.2, remove unused test images
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/test0ReferenceOutput_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeGreenBackgroundColorsToBlue_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeReduceLineSpacing_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemoveAllStrikeThroughs_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemovingLink_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrimReference_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrim_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testCentersPresObamasFaceVertically_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageNotCroppedBecauseFacesAreTooSmall_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageShorterThanViewIsNotStretched_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testUsesSpecifiedContentModeBehaviorOnFeaturelessImage_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldCenterShortTitleWhenDescriptionIsEmpty_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldHighlightMatchingSubstring_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldNotShowLongDescriptionWhenTitleExceedsTwoLines_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldShowLongDescriptionWhenTitleIsShort_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldShowTitleAtTheTopAndDescriptionAtTheBottom_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticleListCellVisualTests/testShouldTruncateAndShrinkTitle_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_10_3_1_RTL_iPad10_3_1_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_11_3_RTL_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_10_3_1_RTL_iPad10_3_1_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_11_3_RTL_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_10_3_1_RTL_iPad10_3_1_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_11_3_RTL_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_10_3_1_RTL_iPad10_3_1_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_11_3_RTL_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFPicOfTheDayTableViewCellVisualTests/testInitialStateOnlyShowsPlaceholderWithoutCaption_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFPicOfTheDayTableViewCellVisualTests/testShowsCaptionWhenImageIsFinallyDownloaded_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFPicOfTheDayTableViewCellVisualTests/testStillShowsPlaceholderWithoutCaptionWhileImageIsDownloading_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_11_3_RTL_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_11_3_LTR_iPad11_3_768x1024@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_11_3_RTL_iPad11_3_768x1024@2x.png
Labels: Low impact

#2291 Bump pagelib version to get correct `Read more` display titles.
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/package.json
Labels: 5.8.2, Low impact

#2290 Fix Xcode 9.3 warnings followup
  Wikipedia/Code/WMFWelcomeAnalyticsAnimationBackgroundView.swift
  Wikipedia/Code/WMFWelcomeAnimationBackgroundView.swift
  Wikipedia/Code/WMFWelcomeAnimationViewControllers.swift
  Wikipedia/Code/WMFWelcomeExplorationAnimationBackgroundView.swift
  Wikipedia/Code/WMFWelcomeLanguagesAnimationBackgroundView.swift
Labels: 5.8.2, Low impact

#2292 Fix trailing alignment warning
  Wikipedia/Code/ScrollableEducationPanelView.xib
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
Labels: 5.8.2

#2137 More CSS updates
  Makefile
  Wikipedia/assets/abusefilter.css
  Wikipedia/assets/preview.css
  Wikipedia/assets/styles.css
Labels: 5.8.2

#2056 T184920 increase maximum font size
  Wikipedia/Code/NSUserDefaults+WMFApplicationDefaults.swift
  Wikipedia/Code/TextSizeChangeExampleViewController.xib
Labels: 5.8.2, Low impact

#2301 Fix explore search navbar button and title hide/show
  Wikipedia/Code/WMFExploreViewController.m
Labels: Changes welcome, Low impact

#2307 Fix missing display title on older on this day pages
  Wikipedia/Code/MWKSearchResult.m
  Wikipedia/Code/WMFFeedArticlePreview.m
Labels: 5.8.2, Low impact

#2312 Add a field to MobileWikiAppDailyStats to identify whether a user is logged in, and a client side timestamp
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.m
Labels: 5.8.2, Low impact

#2313 Fix OSM build target
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Mapbox+Extensions.swift
Labels: Low impact

#2316 Migrate previous app install id if it exists
  Wikipedia/Code/WMFKeychainCredentials.swift
Labels: 5.8.2, Low impact

#2319 Use latest build system
  Wikipedia.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Labels: Low impact

#2315 Fix HTML comments appearing in news notifications
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/NSRegularExpression+HTML.m
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NSAttributedString+WMFTrim.m
  Wikipedia/Code/NSString+WMFExtras.m
  Wikipedia/Code/NSString+WMFHTMLParsing.h
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/NewsCollectionViewCell.swift
  Wikipedia/Code/WMFFeedContentSource.m
  WikipediaUnitTests/Code/NSString+WMFHTMLParsingTests.m
Labels: 5.8.2

#2310 Use PCS media endpoint for article media
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/MWKArticle.h
  Wikipedia/Code/MWKArticle.m
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKImageInfo.h
  Wikipedia/Code/MWKImageInfo.m
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/NSDictionary+WMFExtensions.h
  Wikipedia/Code/NSDictionary+WMFExtensions.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/UIScreen+WMFImageWidth.h
  Wikipedia/Code/UIScreen+WMFImageWidth.m
  Wikipedia/Code/UIViewController+WMFOpenExternalUrl.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFImageGalleryViewController.m
  WikipediaUnitTests/Code/ArticleFetcherTests.m
Labels: 5.8.2

#2323 Fix assertion fail when trying to access reading list entry after it was deleted
  Wikipedia/Code/ReadingListDetailViewController.swift
Labels: 5.8.2, Low impact

#2322 Use localized timestamp for event logging
  WMF Framework/EventLoggingStandardEventProviding+EventLoggingEventValuesProviding+EventLoggingCategory+EventLoggingLabel.swift
  Wikipedia/Code/NSDateFormatter+WMFExtensions.h
  Wikipedia/Code/NSDateFormatter+WMFExtensions.m
Labels: 5.8.2, Low impact

#2325 Handle article URLs with query parameters
  Wikipedia/Code/MWKSection.m
  Wikipedia/Code/MWKSite.h
  Wikipedia/Code/MWKSite.m
  Wikipedia/Code/MWKTitle.h
  Wikipedia/Code/MWKTitle.m
  Wikipedia/Code/NSURL+WMFLinkParsing.h
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/WMFArticleViewController.m
  WikipediaUnitTests/Code/MWKSite+Random.m
  WikipediaUnitTests/Code/MWKSiteTests.m
  WikipediaUnitTests/Code/MWKTitleTests.m
  WikipediaUnitTests/Code/NSURL+WMFLinkParsingTests.m
  WikipediaUnitTests/Code/WMFLinkParsingTests.m
Labels: 5.8.2

#2324 More reading lists event logging updates
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/LoginFunnel.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/SessionsFunnel.swift
  Wikipedia/Code/SettingsFunnel.swift
  Wikipedia/Code/ShareActivityController.swift
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.m
  Wikipedia/Code/WMFSearchFunnel.m
Labels: 5.8.2

#2326 Flip close button
  Wikipedia/Code/ScrollableEducationPanelView.xib
Labels: 5.8.2, Low impact

#2329 Update contributors list
  Wikipedia/Code/AboutViewController.plist
Labels: 5.8.2, Low impact

#2330 Update pagelib
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  www/package.json
Labels: 5.8.2, Low impact

#2327 Use local time with UTC offset in event logging timestamp
  WMF Framework/EventLoggingStandardEventProviding+EventLoggingEventValuesProviding+EventLoggingCategory+EventLoggingLabel.swift
  Wikipedia/Code/CreateAccountFunnel.m
  Wikipedia/Code/EditFunnel.m
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/NSDateFormatter+WMFExtensions.h
  Wikipedia/Code/NSDateFormatter+WMFExtensions.m
  Wikipedia/Code/ProtectedEditAttemptFunnel.m
  Wikipedia/Code/SavedPagesFunnel.m
  Wikipedia/Code/ToCInteractionFunnel.m
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.m
  Wikipedia/Code/WMFHamburgerMenuFunnel.m
  Wikipedia/Code/WMFLoginFunnel.m
  Wikipedia/Code/WMFSearchFunnel.m
  Wikipedia/Code/WMFShareFunnel.m
  Wikipedia/Code/WMFSuggestedPagesFunnel.m
Labels: 5.8.2, Low impact

#2328 Update event logging schemas to use new revisions
  Wikipedia/Code/CreateAccountFunnel.m
  Wikipedia/Code/EditFunnel.m
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/LoginFunnel.swift
  Wikipedia/Code/ProtectedEditAttemptFunnel.m
  Wikipedia/Code/ReadingListsFunnel.swift
  Wikipedia/Code/SessionsFunnel.swift
  Wikipedia/Code/SettingsFunnel.swift
  Wikipedia/Code/ToCInteractionFunnel.m
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WMFDailyStatsLoggingFunnel.m
  Wikipedia/Code/WMFLoginFunnel.m
  Wikipedia/Code/WMFSearchFunnel.m
  Wikipedia/Code/WMFShareFunnel.m
Labels: 5.8.2, Low impact

#2332 Fixes issue with newlines in Wikidata descriptions that led to T195551
  WMF Framework/NSRegularExpression+HTML.h
  WMF Framework/NSRegularExpression+HTML.m
  Wikipedia/Code/NSString+WMFExtras.h
  Wikipedia/Code/NSString+WMFExtras.m
  Wikipedia/Code/WKWebView+ElementLocation.m
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.swift
  Wikipedia/Code/WebViewController.m
Labels: 5.8.2

#2333 Show announcements if countries array is missing or empty
  WMF Framework/WMFAnnouncementsFetcher.m
Labels: 5.8.2, Low impact

#2335 Use new event logging label property to identify peeked read more items
  WMF Framework/EventLoggingStandardEventProviding+EventLoggingEventValuesProviding+EventLoggingCategory+EventLoggingLabel.swift
  WMF Framework/EventLoggingStandardEventProviding.swift
  WMF Framework/WMFContentGroup+EventLogging.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/DisambiguationPagesViewController.swift
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/LoginFunnel.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/ReadingListsFunnel.swift
  Wikipedia/Code/SaveButton.swift
  Wikipedia/Code/SessionsFunnel.swift
  Wikipedia/Code/SettingsFunnel.swift
  Wikipedia/Code/ShareActivityController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFExploreViewController.m
Labels: 5.8.2

#2338 Use preferred variant for zh, default to zh-hans
  WMF Framework/Localization/WMFLocalization.m
Labels: 5.8.2

#2334 Handle listen links and all commons ogg links
  Wikipedia/Code/NSURL+WMFLinkParsing.h
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/UIViewController+WMFOpenExternalUrl.m
  Wikipedia/assets/about.js
  Wikipedia/assets/index.js
  Wikipedia/assets/languages.json
  Wikipedia/assets/preview.js
  Wikipedia/assets/styleoverrides.css
  www/less/misc.less
Labels: 5.8.2

#2340 Use PCS CSS `./site` endpoint
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/assets/index.html
  Wikipedia/assets/preview.html
  www/index.html
  www/preview.html
Labels: 5.8.2, Low impact

#2344 6.0.0 🎉
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: 6.0
