Repository wikimedia/wikipedia-ios, pull requests merged in 2018-07, with the labels that each got.

#2379 Search tweaks
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0, Low impact

#2380 Updates to the On this day card
  WMF Framework/WMFContentGroup+Display.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/OnThisDayCollectionViewCell.swift
  Wikipedia/Code/OnThisDayExploreCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/OnThisDayExploreCollectionViewCell.swift
  Wikipedia/Code/OnThisDayTimelineView.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
Labels: 6.0

#2382 Fix truncation on feed date headers and pic of day captions
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreHeaderCollectionReusableView.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ImageCollectionViewCell.swift
Labels: 6.0, Changes welcome, Low impact

#2383 Updates to explore titles and sub-titles
  Wikipedia/Code/NSDateFormatter+WMFExtensions.h
  Wikipedia/Code/NSDateFormatter+WMFExtensions.m
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ast.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/bn.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/bs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ckb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/el.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/eu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fa.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/gl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/id.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/is.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/it.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ja.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/kab.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/km.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ksh.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ms.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/my.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pa.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ps.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ro.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sah.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sr-EC.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ta.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/th.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ur.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/vi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.0, Low impact

#2384 Search bar follow on fixes
  WMF Framework/NavigationBar.swift
  WMF Framework/Theme.swift
  Wikipedia/Code/SearchTransition.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/ViewControllerTransitionsController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0, Low impact

#2385 Initial recent searches re-implementation
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/RecentSearchesViewController.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0, Low impact

#2386 Shared CollectionViewHeader class
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/CollectionViewHeader.swift
  Wikipedia/Code/ExploreHeaderCollectionReusableView.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HistoryViewController.swift
Labels: 6.0

#2390 Fix search tab root view controller disappearing from the navigation stack
  Gemfile.lock
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0, Low impact

#2392 In the news detail view updates
  WMF Framework/ColumnarCollectionViewLayoutMetrics.swift
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/NewsCollectionViewHeader.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
Labels: 6.0, Low impact

#2394 Use compact cells on `Because you read` card
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
Labels: 6.0, Low impact

#2395 Tweaks to nearby card
  WMF Framework/WMFContentGroup+Display.swift
  Wikipedia/Code/ArticleLocationAuthorizationCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/WMFCompassView.m
Labels: 6.0, Low impact

#2396 Get rid of the annoying Error: CUICatalog: Invalid asset name
  Wikipedia/Code/WMFSettingsTableViewCell.m
Labels: Low impact

#2397 Saved article/Reading list cells fixes
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/CollectionViewEditControllerNavigationDelegate+Extensions.swift
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/WMFSettingsTableViewCell.m
Labels: 6.0

#2399 Fix theme not sticking
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/NewsViewController.swift
Labels: 6.0, Changes welcome, Low impact

#2400 Feed performance fixes
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/WMFContentGroup+CoreDataProperties.h
  WMF Framework/WMFContentGroup+CoreDataProperties.m
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia.xcdatamodel/contents
  Wikipedia/Code/AlignedImageButton.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/SizeThatFitsReusableView.swift
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
  Wikipedia/Images.xcassets/overflow.imageset/Contents.json
  Wikipedia/Images.xcassets/overflow.imageset/overflow(1).pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ast.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/bs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ckb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/el.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/eu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fa.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/gl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/id.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/is.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/it.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ja.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/kab.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/km.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ms.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ne.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ta.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/vi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.0

#2403 Fix layout of explore feed footer button
  Wikipedia/Code/AlignedImageButton.swift
Labels: 6.0, Low impact

#2402 Update text slider example string
  Wikipedia/Code/TextSizeChangeExampleViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Low impact

#2401 Add section to `about` for maps license
  Wikipedia/Code/AboutViewController.m
  Wikipedia/Code/AboutViewController.plist
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/assets/about.html
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Low impact

#2404 Search & Explore animation fixes
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/CollectionViewUpdater.swift
Labels: 6.0, Low impact, Update branch before merging

#2408 Updated release notes from Josh
  WMF Framework/CommonStrings.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Low impact

#2407 Design pixel push tweaks
  WMF Framework/ColumarCollectionViewLayoutSection.swift
  WMF Framework/ColumnarCollectionViewLayoutMetrics.swift
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/ArticleCollectionViewCell+WMFFeedContentDisplaying.swift
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/ImageCollectionViewCell.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
Labels: 6.0, Changes welcome, Question(s)

#2409 Appearance fixes for navigation bar shadow & Saved tab
  WMF Framework/Theme.swift
  Wikipedia/Code/Saved.storyboard
  Wikipedia/Code/SavedViewController.swift
Labels: 6.0, Low impact

#2410 Appearance fixes
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Code/WMFTabBarUI.storyboard
Labels: 6.0, Low impact

#2412 Fix invalid constraints error in search VC
  WMF Framework/ColumarCollectionViewLayoutSection.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFTabBarUI.storyboard
Labels: 6.0, Low impact

#2415 Fix collection view crashes, revert to most sensible logic
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: 6.0, Low impact

#2416 Flip explore tab setting naming
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/el.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.0, Low impact

#2419 Fix background color of first random VC
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
Labels: 6.0, Low impact

#2405 Feed theme updates
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/NavigationBar.swift
  WMF Framework/Theme.swift
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationAuthorizationCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/ArticleRightAlignedImageCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NewsCollectionViewCell.swift
  Wikipedia/Code/OnThisDayExploreCollectionViewCell.swift
  Wikipedia/Code/RankedArticleCollectionViewCell.swift
Labels: 6.0

#2421 Pixel push card shadows
  WMF Framework/ExploreCardCollectionViewCell.swift
Labels: 6.0, Low impact

#2420 Fix collection view updates (again)
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: 6.0

#2424 Fix collection view layout invalidation
  WMF Framework/ColumarCollectionViewLayoutSection.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
Labels: 6.0, Low impact

#2425 Fix explore feed full width image cell save button alignment
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
Labels: 6.0, Low impact

#2426 Remove trailing ellipsis added by MediaWiki
  Wikipedia/Code/MWKSearchResult.m
Labels: 6.0, Low impact, Update branch before merging

#2427 Fix ToC header font, remove unused georgia title 1 style
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/WMFTableOfContentsItem.swift
Labels: 6.0, Low impact

#2423 Pixel push on this day enable location card
  Wikipedia/Code/ArticleLocationAuthorizationCollectionViewCell.swift
Labels: 6.0, Low impact

#2428 fix on this day detail view header title font regression
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/OnThisDayViewControllerHeader.swift
Labels: 6.0, Low impact

#2429 fix on this day header IB warnings
  Wikipedia/Code/OnThisDayViewControllerHeader.xib
Labels: 6.0, Low impact

#2430 Fixes for views with in-context extended bar views
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/CreateNewReadingListButtonView.swift
  Wikipedia/Code/CreateNewReadingListButtonView.xib
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Images.xcassets/plus.imageset/Contents.json
  Wikipedia/Images.xcassets/plus.imageset/plus.pdf
Labels: 6.0, Low impact

#2432 Updates to saved theme colors
  Wikipedia/Code/CreateNewReadingListButtonView.swift
  Wikipedia/Code/SavedViewController.swift
Labels: 6.0, Low impact

#2431 Pixel push card shadows
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/Theme.swift
Labels: 6.0, Low impact

#2433 Update zindicies to fix clipping during explore card deletion animation
  WMF Framework/ColumnarCollectionViewLayout.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
Labels: 6.0, Low impact

#2434 Search bug fixes
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/SearchBarExtendedViewController.xib
  Wikipedia/Code/SearchTransition.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Low impact

#2436 Invalidate layout & reload visible cells on item update
  Wikipedia/Code/ExploreViewController.swift
Labels: 6.0, Low impact

#2437 Search fixes
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0

#2440 Remove piwik from all targets
  Wikipedia.xcodeproj/project.pbxproj
Labels: 6.0, Low impact

#2439 Today > yesterday > dates
  Wikipedia/Code/NSDate+WMFRelativeDate.m
Labels: 6.0, Low impact

#2435 Present alert when toggling default tab
  WMF Framework/CommonStrings.swift
  WMF Framework/ExploreFeedPreferencesUpdateCoordinator.swift
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFSettingsViewController.h
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Changes welcome

#2441 Saved cell theme updates
  WMF Framework/Theme.swift
  Wikipedia/Code/TagCollectionViewCell.swift
Labels: 6.0, Low impact

#2443 Workaround for broken explore feed & animation state when turning off all explore feed sections
  Wikipedia/Code/CollectionViewUpdater.swift
Labels: 6.0

#2444 Reload data on CollectionViews while Explore & History aren't visible
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/ColumnarCollectionViewControllerLayoutCache.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HistoryViewController.swift
Labels: 6.0, Update branch before merging

#2446 Combine WMFTabBarUI, WMFAppViewController
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/Launch Screen.storyboard
  Wikipedia/Code/Places.storyboard
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/UIViewController+WMFArticlePresentation.m
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFAppModalProgressViewController.swift
  Wikipedia/Code/WMFAppModalProgressViewController.xib
  Wikipedia/Code/WMFAppViewController.h
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAppViewController.storyboard
  Wikipedia/Code/WMFArticleNavigationController.h
  Wikipedia/Code/WMFArticleNavigationController.m
  Wikipedia/Code/WMFRotationRespectingNavigationController.h
  Wikipedia/Code/WMFRotationRespectingNavigationController.m
  Wikipedia/Code/WMFRotationRespectingTabBarController.swift
  Wikipedia/Code/WMFTabBarController.h
  Wikipedia/Code/WMFTabBarController.m
  Wikipedia/Code/WMFTabBarUI.storyboard
  Wikipedia/Code/Wikipedia-Bridging-Header.h
Labels: 6.0

#2448 Feed detail presentation initial pass
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/CollectionViewHeader.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/DetailTransition.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/ImageScaleTransition.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.m
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/ViewControllerTransitionsController.swift
  Wikipedia/Code/WMFArticleViewController.h
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
  Wikipedia/Code/WebViewController.h
  Wikipedia/Code/WebViewController.m
Labels: 6.0

#2449 Feed customization fixes
  WMF Framework/ExploreFeedPreferencesUpdateCoordinator.swift
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/WMFContinueReadingContentSource.m
Labels: 6.0, Low impact

#2450 Fix transition bugs
  Gemfile.lock
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/DetailTransition.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/Places.storyboard
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WebViewController.h
  Wikipedia/Code/WebViewController.m
  Wikipedia/Code/WebViewController_Private.h
Labels: 6.0

#2452 Add ability to scroll to top in detail views
  Wikipedia/Code/ViewController.swift
Labels: 6.0

#2459 Update W tooltip to reflect current behavior (copy change)
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ast.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/bn.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/bs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ckb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/el.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/eu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fa.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/gl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/id.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/is.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ja.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/kab.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/km.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ms.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ta.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/vi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.0, Low impact

#2454 Explore feed customization: Collapsed feed cards
  WMF Framework/ColumnarCollectionViewLayout.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/ExploreFeedPreferencesUpdateCoordinator.swift
  WMF Framework/WMFContentGroup+CoreDataProperties.h
  WMF Framework/WMFContentGroup+CoreDataProperties.m
  WMF Framework/WMFContentGroup+Extensions.h
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia.xcdatamodel/contents
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Changes welcome

#2457 iPad ToC Fixes
  Wikipedia/Code/NavigationBarHider.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WebViewController.m
Labels: 6.0

#2458 Add an extension on IndexPath to check if it's valid
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NSFetchedResultsController+IndexPathValidation.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: Question(s), Update branch before merging

#2460 Allow users to have the app open to the Search tab
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/SearchSettingsViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFSettingsMenuItem.h
  Wikipedia/Code/WMFSettingsMenuItem.m
  Wikipedia/Code/WMFSettingsTableViewCell.h
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0

#2462 As a user of search, I would like the 'Search' button in the keyboard to complete an action
  Wikipedia/Code/SearchViewController.swift
Labels: 6.0, Low impact

#2461 Use async operation to dismiss collapsed cards
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/ExploreViewController.swift
Labels: 6.0

#2463 As a user of the Places near your location card, when I give location permissions I do not expect the card to disappear
  Wikipedia/Code/ArticleLocationAuthorizationCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Low impact

#2466 Fix shadow clipping during card hiding animation
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
Labels: 6.0, Low impact

#2467 Localize "Undo", update undo label & button
  WMF Framework/ExploreCardCollectionViewCell.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Changes welcome, Low impact

#2468 Places list slider not working on iPad
  Wikipedia/Code/PlacesViewController.swift
Labels: 6.0, Low impact

#2465 Fix WKWebView user interaction issue
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFViewController.h
  Wikipedia/Code/WMFViewController.m
  Wikipedia/Code/WebViewController.h
  Wikipedia/Code/WebViewController.m
Labels: 6.0

#2469 don't allow selection of collapsed cards
  WMF Framework/WMFContentGroup+Display.swift
Labels: 6.0, Low impact

#2470 Fix search layout on rotate
  Wikipedia/Code/SearchViewController.swift
Labels: 6.0, Low impact

#2447 MobileWikiAppiOSUserHistory schema event logging updates
  WMF Framework/EventLoggingService.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/SearchSettingsViewController.swift
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0

#2472 change `all articles` `add to..` button string to `add to list`
  WMF Framework/CommonStrings.swift
  Wikipedia/Code/BatchEditSelectView.swift
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.0, Low impact

#2473 Updates to Places near you card
  Wikipedia/Code/ArticleLocationAuthorizationCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
Labels: 6.0, Changes welcome, Low impact

#2476 Fix missing toolbar
  WMF Framework/Theme.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DetailTransition.swift
  Wikipedia/Code/UITabBar+Theme.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0, Low impact

#2478 Follow up for T195630
  WMF Framework/ColumnarCollectionViewLayoutMetrics.swift
  Wikipedia/Code/CreateNewReadingListButtonView.swift
Labels: 6.0, Low impact

#2480 Fix distance label RTL alignment
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
Labels: 6.0, Low impact

#2481 [BUG] Selecting "View on a map" from 3d touch on a feed article (having a location) is broken
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.0, Changes welcome, Low impact

#2482 Fix location manager creation, location card update
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/CLLocationManager+WMFLocationManagers.m
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/WMFNearbyContentSource.m
Labels: 6.0, Changes welcome, Low impact

#2484 Fix reappearing global cards
  WMF Framework/WMFExploreFeedContentController.m
Labels: 6.0, Low impact

#2486 Update ArticleLocationCollectionViewCell's minimum height
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
Labels: 6.0, Changes welcome, Low impact

#2483 Hide language bar when not in search focus
  Wikipedia/Code/SearchViewController.swift
Labels: 6.0, Low impact

#2477 As a user of search, I'd like to see fewer animations at the start of my search
  WMF Framework/FakeProgressController.swift
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/Places.storyboard
  Wikipedia/Code/PlacesViewController.swift
Labels: 6.0, Changes welcome, Low impact

#2487 Update dismissing the keyboard while searching
  Wikipedia/Code/SearchViewController.swift
Labels: 6.0, Low impact

#2490 Fix explore refresh spinner clipping - take two
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ExploreViewController.swift
Labels: 6.0, Changes welcome, Low impact

#2488 Pixel push changes from session with Carolyn
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/Theme.swift
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ArticleFullWidthImageCollectionViewCell.swift
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ImageCollectionViewCell.swift
Labels: 6.0, Low impact

#2492 Update On this day's footer string
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
Labels: 6.0, Low impact

#2491 Fix scroll/refresh issue on empty explore feed
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NavigationBarHider.swift
Labels: 6.0, Low impact

#2495 Update Places card spacing, fix invisible nav bar when adding articles to a new list
  Wikipedia/Code/ArticleLocationAuthorizationCollectionViewCell.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.0, Low impact

#2493 Fix nearby issues
  WMF Framework/WMFContentGroup+Extensions.h
  WMF Framework/WMFContentGroup+Extensions.m
  Wikipedia/Code/WMFLocationManager.m
  Wikipedia/Code/WMFNearbyContentSource.m
Labels: 6.0, Low impact

#2497 Fix On this day footer text
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/el.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/gl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.0, Changes welcome, Low impact

#2496 Add missing explore feed detail headers
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/CollectionViewHeader.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/OnThisDayViewControllerHeader.swift
  Wikipedia/Code/OnThisDayViewControllerHeader.xib
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
Labels: 6.0, Low impact

#2499 Detail header pixel push
  Wikipedia/Code/CollectionViewHeader.swift
  Wikipedia/Code/NewsCollectionViewHeader.xib
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/ViewController.swift
Labels: 6.0, Low impact

#2500 Fix continue reading image resolution
  WMF Framework/WMFContentGroup+Display.swift
Labels: 6.0, Low impact, Update branch before merging

#2498 Move collapsed card away from section headers
  WMF Framework/ColumnarCollectionViewLayoutMetrics.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
Labels: 6.0, Changes welcome, Low impact

#2503 Add top spacing to title bars, shrinking title view on scroll
  WMF Framework/NavigationBar.swift
  WMF Framework/UIScrollView+Limits.swift
  WMF Framework/UIView+SemanticContent.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NavigationBarHider.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/WebViewController.m
Labels: 6.0

#2504 Update localizations
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/eu.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fi.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/it.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 6.0, Low impact

#2505 [Bug] Long article titles push the W button off center
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.0, Low impact

#2507 Editing languages during onboarding crashes app
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.0

#2508 Update "Create a new list" button view's height to match Search & Sort
  Wikipedia/Code/CreateNewReadingListButtonView.xib
Labels: 6.0, Low impact

#2509 Fix navigation bar hidng speed on explore, hiding detents everywhere
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/NavigationBarHider.swift
Labels: 6.0, Low impact

#2510 Fixes for search transition for issues introduced by top spacing
  WMF Framework/NavigationBar.swift
  WMF Framework/UIScrollView+Limits.swift
  Wikipedia/Code/NavigationBarHider.swift
  Wikipedia/Code/SearchTransition.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFViewController.m
Labels: 6.0, Low impact

#2511 Fix shadow transition
  Wikipedia/Code/SearchTransition.swift
  Wikipedia/Code/SearchViewController.swift
Labels: 6.0, Low impact

#2512 Fix hiding detents for search
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/NavigationBarHider.swift
Labels: 6.0, Low impact

#2513 Allow article image header to passthrough touches to the article view
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/PassthroughView.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.0

#2501 First set of RTL audit fixes
  WMF Framework/UIView+SemanticContent.swift
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ImageCollectionViewCell.swift
  Wikipedia/Code/MWKImageInfoFetcher+PicOfTheDayInfo.h
  Wikipedia/Code/MWKImageInfoFetcher+PicOfTheDayInfo.m
  Wikipedia/Code/MWLanguageInfo.h
  Wikipedia/Code/WMFFeedContentFetcher.h
  Wikipedia/Code/WMFFeedContentFetcher.m
  Wikipedia/Code/WMFFeedImage.h
  Wikipedia/Code/WMFFeedImage.m
Labels: 6.0, Changes welcome, Low impact

#2518 Setup fetched results controller before first appearance instead of on set of dataStore
  Wikipedia/Code/ExploreViewController.swift
Labels: 6.0, Low impact

#2515 Second set of RTL audit fixes
  Wikipedia/Code/MWKArticle.m
  Wikipedia/Code/MWKImageInfo.h
  Wikipedia/Code/MWKImageInfo.m
  Wikipedia/Code/MWKImageInfoFetcher+PicOfTheDayInfo.m
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/MWKImageInfoResponseSerializer.m
  Wikipedia/Code/WMFImageGalleryDetailOverlayView.h
  Wikipedia/Code/WMFImageGalleryDetailOverlayView.m
  Wikipedia/Code/WMFImageGalleryViewController.m
  WikipediaUnitTests/Code/MWKImage+AssociationTestUtils.m
Labels: 6.0

#2516 Kellyroach/fix warnings
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AboutViewController.plist
  Wikipedia/Code/MWKImageInfo.h
  Wikipedia/Code/MWKSectionList.h
  Wikipedia/Code/NSUserActivity+WMFExtensions.m
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WebViewController.m
  Wikipedia/Third Party Code/RMessage/RMessageView.m
  WikipediaUITests/SnapshotHelper.swift
Labels: 6.0

#2520 Remove layout cache
  WMF Framework/UIView+SemanticContent.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ColumnarCollectionViewControllerLayoutCache.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HistoryViewController.swift
Labels: 6.0

#2521 Update Reading list empty states
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AddArticlesToReadingListViewController.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/CreateNewReadingListButtonView.swift
  Wikipedia/Code/CreateNewReadingListButtonView.xib
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/UIViewController+WMFEmptyView.h
  Wikipedia/Code/UIViewController+WMFEmptyView.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFEmptyView.h
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Code/WMFEmptyView.xib
Labels: 6.0, Changes welcome

#2524 Obj-C using `POST` for image info fetching.
  Wikipedia/Code/AFHTTPSessionManager+WMFDesktopRetry.h
  Wikipedia/Code/AFHTTPSessionManager+WMFDesktopRetry.m
  Wikipedia/Code/MWKImageInfoFetcher.m
Labels: 6.0, Changes welcome

#2523 Minor caching tweaks
  WMF Framework/UIFont+WMFDynamicType.swift
  Wikipedia/Code/ExploreCardViewController.swift
Labels: 6.0, Low impact

#2525 More RTL audit fixes
  Wikipedia/Code/ArticleLocationCollectionViewCell.swift
  Wikipedia/Code/CollectionViewCell.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/assets/about.html
  www/about.html
Labels: 6.0, Low impact

#2526 Fix on this day explore card occasionally showing only a single event
  WMF Framework/WMFContentGroup+Extensions.m
Labels: 6.0, Low impact

#2527 Re-fix header image scroll, refresh control
  Wikipedia/Code/MWKImageInfo.m
  Wikipedia/Code/WMFArticleViewController.h
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WebViewController.h
  Wikipedia/Code/WebViewController.m
  Wikipedia/Code/WebViewController_Private.h
Labels: 6.0

#2519 Fix Explore feed preferences being off for visible content groups
  WMF Framework/WMFExploreFeedContentController.m
Labels: WIP

#2528 Update fastlane
  Gemfile.lock
Labels: 6.0, Low impact

#2530 Fix 3d touch on article list views
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/SavedArticlesViewController.swift
Labels: 6.0, Low impact

#2529 Order explore feed by preferred language
  WMF Framework/WMFContentGroup+Extensions.h
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/MWKDataStore.m
Labels: 6.0

#2522 Apple Maps license
  Wikipedia/Code/AboutViewController.plist
Labels: 6.0, Low impact

#2531 Fix navigation bar header font size
  WMF Framework/NavigationBar.swift
  WMF Framework/UIFont+WMFDynamicType.swift
Labels: 6.0, Low impact

#2532 Update fastlane (again)
  Gemfile.lock
Labels: 6.0, Low impact
