Repository wikimedia/wikipedia-ios, pull requests merged in 2018-09, with the labels that each got.

#2636 Lower impact layout invalidation changes
  Wikipedia/Code/ColumnarCollectionViewControllerLayoutCache.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
Labels: 6.0.1, Low impact

#2637 Switch WMF.framework to Swift 4.2 by inheriting project setting
  ContinueReadingWidget/WMFTodayContinueReadingWidgetViewController.swift
  FeaturedArticleWidget/FeaturedArticleWidget.swift
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  TopReadWidget/WMFTodayTopReadWidgetViewController.swift
  WMF Framework/BatchEditToolbarViewController.swift
  WMF Framework/CollectionViewCellActionsView.swift
  WMF Framework/CollectionViewEditController.swift
  WMF Framework/ColumarCollectionViewLayoutSection.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
  WMF Framework/ExploreCardCollectionViewCell.swift
  WMF Framework/LabelGroupAccessibilityElement.swift
  WMF Framework/Theme.swift
  WMF Framework/ThemeableTextField.swift
  WMF Framework/UIFont+WMFDynamicType.swift
  WMF Framework/UIScrollView+Limits.swift
  WMF Framework/UIView+Constraints.swift
  WMF Framework/UIView+SemanticContent.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AnnouncementCollectionViewCell.swift
  Wikipedia/Code/ArticleRightAlignedImageCollectionViewCell.swift
  Wikipedia/Code/BatchEditSelectView.swift
  Wikipedia/Code/CircledRankView.swift
  Wikipedia/Code/CollectionViewCell.swift
  Wikipedia/Code/CollectionViewEditControllerNavigationDelegate+Extensions.swift
  Wikipedia/Code/GroupedAccessibilityView.swift
  Wikipedia/Code/OnThisDayTimelineView.swift
  WikipediaUnitTests/Code/WMFArticleListTableViewCell+DynamicTypeFontTests.swift
  WikipediaUnitTests/Code/WMFImageControllerTests.swift
Labels: Changes welcome, WIP

#2641 Workarounds for iOS 12 issues
  Wikipedia/Code/UIScrollView+WMFContentOffsetUtils.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFViewController.h
  Wikipedia/Code/WMFViewController.m
  Wikipedia/Code/WebViewController.m
Labels: 6.1, Changes welcome

#2642 Fix missing priority
  WMF Framework/UIView+Constraints.swift
Labels: 6.1, Low impact

#2587 Fix various gallery image description issues
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/LicenseView.swift
  Wikipedia/Code/SetupGradientView.swift
  Wikipedia/Code/UIView+WMFSnapshotting.m
  Wikipedia/Code/WMFImageGalleryDescriptionTextView.swift
  Wikipedia/Code/WMFImageGalleryDetailOverlayView.h
  Wikipedia/Code/WMFImageGalleryDetailOverlayView.m
  Wikipedia/Code/WMFImageGalleryDetailOverlayView.xib
  Wikipedia/Code/WMFImageGalleryGradientViews.swift
  Wikipedia/Code/WMFImageGalleryViewController.m
  Wikipedia/Images.xcassets/gallery-line-bent.imageset/Contents.json
  Wikipedia/Images.xcassets/gallery-line-bent.imageset/gallery-line-bent.pdf
  Wikipedia/Images.xcassets/gallery-line.imageset/Contents.json
  Wikipedia/Images.xcassets/gallery-line.imageset/gallery-line.pdf
  Wikipedia/Images.xcassets/gallery-top-gradient.imageset/Contents.json
  Wikipedia/Images.xcassets/gallery-top-gradient.imageset/gallery-top-gradient.png
Labels: 6.1

#2645 Bump version to 6.1
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: 6.1

#2643 Unify face detection cache internals and make its key size invariant
  Wikipedia/Code/MWKImage.h
  Wikipedia/Code/MWKImage.m
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.m
  Wikipedia/Code/WMFFaceDetectionCache.h
  Wikipedia/Code/WMFFaceDetectionCache.m
  WikipediaUnitTests/Code/MWKImageFaceDetectionTests.m
  WikipediaUnitTests/Code/UIImageView+MWKImageTests.m
Labels: 6.1, Changes welcome

#2648 Update test configs to include iOS 12
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/test0ReferenceOutput_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeGreenBackgroundColorsToBlue_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeReduceLineSpacing_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemoveAllStrikeThroughs_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemovingLink_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrimReference_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrim_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testCentersPresObamasFaceVertically_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageNotCroppedBecauseFacesAreTooSmall_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageShorterThanViewIsNotStretched_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testUsesSpecifiedContentModeBehaviorOnFeaturelessImage_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_12_0_RTL_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_12_0_RTL_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_12_0_RTL_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_12_0_RTL_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_12_0_RTL_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_12_0_LTR_iPhone12_0_375x667@2x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_12_0_RTL_iPhone12_0_375x667@2x.png
  fastlane/Fastfile
Labels: 6.1

#2649 Bundle update
  Gemfile.lock
Labels: 6.1, Low impact

#2654 Add jenkinsfile
  Jenkinsfile
  scripts/setup_rbenv_and_ruby
Labels: 6.1, Low impact

#2655 Handle non-wikipedia scheme URLs in openURL
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/NSUserActivity+WMFExtensions.h
  Wikipedia/Code/NSUserActivity+WMFExtensions.m
Labels: 6.1

#2656 Fix inset on iOS 12 after pull to refresh
  Wikipedia/Code/WebViewController.m
Labels: 6.1, Low impact

#2650 Wikidata description editing back end - first pass
  WMF Framework/CSRFTokenOperation.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AuthenticationDelegate.swift
  Wikipedia/Code/KeychainCredentialsManager.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/URL+WMFLinkParsing.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAuthTokenFetcher.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
  Wikipedia/Code/WikidataFetcher.swift
Labels: 6.1

#2660 Wikidata description API tweaks
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.1

#2659 Replace success, failure login blocks with single completion using LoginResult
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/AuthenticationDelegate.swift
  Wikipedia/Code/WMFAccountCreationViewController.swift
  Wikipedia/Code/WMFAuthTokenFetcher.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFChangePasswordViewController.swift
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFTwoFactorPasswordViewController.swift
Labels: 6.1

#2662 Add triggers to Jenkinsfile
  Jenkinsfile
Labels: 6.1, Low impact

#2631 Set reading lists limits
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/ReadingListsController.swift
Labels: 6.1

#2664 Add a missing completion call in EventLoggingService
  WMF Framework/EventLoggingService.swift
Labels: Low impact
