Repository wikimedia/wikipedia-ios, pull requests merged in 2019-04, with the labels that each got.

#3012 [Design bug] After using highlight to edit, the cursor is placed after the highlighted word
  Wikipedia/assets/codemirror/codemirror-editTextSelection.js
  www/codemirror/codemirror-editTextSelection.js
Labels: 6.2.1, Low Impact

#3013 Check if wikitext was changed
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2.1, Low Impact

#3015 Add "Clear formatting" button to TextFormattingTableViewController
  Wikipedia/Code/TextFormattingDetailTableViewCell.swift
  Wikipedia/Code/TextFormattingProvidingTableViewController.swift
  Wikipedia/Code/TextFormattingTableViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2.1

#3016 As a user of the Find and Replace feature, I want an easy way to see that replace is working
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/assets/codemirror/codemirror-common.css
  Wikipedia/assets/codemirror/resources/addon/search/search.js
  www/codemirror/codemirror-common.css
Labels: 6.2.1, Changes welcome

#3011 Remove Article Summary fetching from session, make separate Summary fetcher
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/RelatedSearchFetcher.swift
  WMF Framework/SummaryExtensions.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/ArticleSummaryController.swift
  Wikipedia/Code/DisambiguationPagesViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/PlaceSearchService.swift
  Wikipedia/Code/RandomArticleFetcher.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/ShareActivityController.swift
  Wikipedia/Code/URL+WMFLinkParsing.swift
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticlePreviewFetcher.h
  Wikipedia/Code/WMFArticlePreviewFetcher.m
  Wikipedia/Code/WMFDatabaseHouseKeeper.swift
  Wikipedia/Code/WMFFirstRandomViewController.m
  Wikipedia/Code/WMFRandomArticleViewController.m
  Wikipedia/Code/WMFRandomContentSource.m
  Wikipedia/Code/WMFRelatedPagesContentSource.m
Labels: 6.3, Changes welcome

#3019 Fix screenshots
  Gemfile.lock
  WikipediaUITests/SnapshotHelper.swift
  WikipediaUITests/SnapshotRecorderTests.swift
  WikipediaUITests/XCUIApplication+SnapshotUtilities.swift
Labels: Low Impact

#3020 Set missing isAccessibilityElement & accessibilityLabel for nav bar buttons
  WMF Framework/NavigationBar.swift
Labels: Low Impact

#3021 Fix screenshots part 2
  WikipediaUITests/README.md
  WikipediaUITests/SnapshotRecorderTests.swift
Labels: Low Impact

#3022 Update version to 6.3.0, remove HockeyApp steps from fastlane
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
  fastlane/Fastfile
  fastlane/README.md
Labels: Low Impact

#3023 Find & replace tests
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/FindAndReplaceKeyboardBar.swift
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  WikipediaUnitTests/Code/SectionEditorFindAndReplaceTests.swift
  WikipediaUnitTests/Code/WikipediaUnitTests-Bridging-Header.h
  WikipediaUnitTests/Fixtures/BarackEarlyLife.json
Labels: Changes welcome, Low Impact

#3026 Turning off Featured article cards in the feed causes Featured article widget to go blank
  FeaturedArticleWidget/FeaturedArticleWidget.swift
Labels: Low Impact

#3028 Decrease calls to wmf_articleDatabaseKey when configuring swipeable cells
  WMF Framework/WMFArticle+Extensions.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ArticleURLProviderEditControllerUpdater.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListEntryCollectionViewController.swift
Labels: Low Impact

#3029 Ensure only the first css class on the body is replaced
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: Changes welcome, Low Impact

#3032 Flatten resulting xcarchive zip, quiet operation
  fastlane/Fastfile
Labels: Low Impact

#3033 Update fastlane
  Gemfile.lock
Labels: Low Impact

#3030 Fix various screenshot bugs, add script readying images for Slack upload
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/WMFSettingsViewController.m
  WikipediaUITests/SnapshotHelper.swift
  WikipediaUITests/SnapshotRecorderTests.swift
  WikipediaUITests/XCUIApplication+SnapshotUtilities.swift
  fastlane/Snapfile
Labels: Low Impact

#3035 Screenshots fixes
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/WMFSettingsViewController.m
  WikipediaUITests/README.md
  WikipediaUITests/SnapshotRecorderTests.swift
  fastlane/Snapfile
Labels: Low Impact

#3027 Core Data performance
  WMF Framework/ExploreFeedPreferencesUpdateCoordinator.swift
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
Labels: Changes welcome

#3040 Return previous results if search results fail to validate query object
  Wikipedia/Code/WMFSearchFetcher.m
Labels: Low Impact

#3043 Fix deploy script
  fastlane/Fastfile
Labels: Low Impact

#3038 Tech: Session & SchemeHandler changes for mobile-html
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AboutViewController.m
  Wikipedia/Code/NSURL+WMFSchemeHandler.h
  Wikipedia/Code/NSURL+WMFSchemeHandler.m
  Wikipedia/Code/PreviewWebViewContainer.swift
  Wikipedia/Code/SchemeHandler/RemoteSubHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler+APIHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler+ArticleSectionHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler+BaseSubHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler+DefaultHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler+FileHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandlerCache.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.m
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.swift
  Wikipedia/Code/WMFArticleJSONCompilationHelper.h
  Wikipedia/Code/WMFArticleJSONCompilationHelper.m
  Wikipedia/Code/WMFURLSchemeHandler.h
  Wikipedia/Code/WMFURLSchemeHandler.m
  Wikipedia/Code/WebViewController.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
  WikipediaUnitTests/Code/ImageProxyParsingTests.m
Labels: Changes welcome

#3036 Small wikitext search refactors
  Wikipedia/assets/codemirror/resources/addon/search/search.js
Labels: Low Impact

#3044 Use option when building pagelib scheme which produces correct sourcemaps
  Wikipedia.xcodeproj/project.pbxproj
Labels: Low Impact

#3054 Map nowiki to nb iOS language code
  WMF Framework/Localization/WMFLocalization.m
Labels: Changes welcome, Low Impact

#3053 Switch upstream CSS to /api/rest_v1/data/css/mobile/base
  Makefile
  Wikipedia/assets/abusefilter.css
  Wikipedia/assets/preview.css
  Wikipedia/assets/styles.css
Labels: Changes welcome

#3045 Update to current long term stable node version (10.15.3)
  .node-version
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/package-lock.json
  www/package.json
Labels: Low Impact

#3055 Fix section editor focus on entry
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: Changes welcome

#3056 Address code review comments for media insert PR
  Wikipedia/Code/Advanced Settings/InsertMediaAdvancedSettingsTableViewController.swift
  Wikipedia/Code/Advanced Settings/InsertMediaImageSizeSettingsTableViewController.swift
  Wikipedia/Code/InsertMediaImageViewController.swift
  Wikipedia/Code/InsertMediaSettingsTableViewController.swift
  Wikipedia/Code/MediaWizardController.swift
  Wikipedia/Code/ThemeableTextView.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Low Impact

#3058 Search language remains the primary language when it is removed
  Wikipedia/Code/SearchViewController.swift
Labels: Low Impact

#3057 Add file protection test
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKDataStore.h
  WikipediaUnitTests/Code/SecurityTests.swift
  WikipediaUnitTests/Code/XCTestCase+DataStoreFixtureTesting.h
  WikipediaUnitTests/Code/XCTestCase+DataStoreFixtureTesting.m
Labels: Changes welcome, Low Impact

#3061 Fix commits cherrypicked into 6.2.3
  Wikipedia/Code/SectionEditorViewController.swift
Labels: Low Impact

#3064 (Continue reading) Fix accessing viewContext from a background thread
  Wikipedia/Code/MWKHistoryList.h
  Wikipedia/Code/MWKHistoryList.m
  Wikipedia/Code/WMFContinueReadingContentSource.m
Labels: Low Impact

#3065 Fix views affected by Swift 5 compiler bug
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/SearchSettingsViewController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
Labels: Changes welcome, Low Impact

#3062 Media insert: scroll away the "Selected image" view when user scrolls down the results list
  WMF Framework/UIScrollView+Limits.swift
  WMF Framework/UIView+Constraints.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Advanced Settings/InsertMediaAdvancedSettingsViewController.swift
  Wikipedia/Code/Advanced Settings/InsertMediaImagePositionSettingsViewController.swift
  Wikipedia/Code/Advanced Settings/InsertMediaImageSizeSettingsViewController.swift
  Wikipedia/Code/Advanced Settings/InsertMediaImageTypeSettingsViewController.swift
  Wikipedia/Code/AlignedImageView.swift
  Wikipedia/Code/DefaultEditToolbarView.xib
  Wikipedia/Code/InsertMediaImageEmptyView.swift
  Wikipedia/Code/InsertMediaImageEmptyView.xib
  Wikipedia/Code/InsertMediaImageInfoView.swift
  Wikipedia/Code/InsertMediaImageInfoView.xib
  Wikipedia/Code/InsertMediaImageViewController.swift
  Wikipedia/Code/InsertMediaImageViewController.xib
  Wikipedia/Code/InsertMediaSearchResultsCollectionViewController.swift
  Wikipedia/Code/InsertMediaSearchViewController.swift
  Wikipedia/Code/InsertMediaSelectedImageView.swift
  Wikipedia/Code/InsertMediaSelectedImageViewController.swift
  Wikipedia/Code/InsertMediaSettingsViewController.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/MediaWizardController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/TabbedViewController.swift
  Wikipedia/Code/UIViewController+WMFEmptyView.h
  Wikipedia/Code/UIViewController+WMFEmptyView.m
  Wikipedia/Code/VerticallySplitViewController.swift
  Wikipedia/Code/VerticallySplitViewController.xib
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFEmptyView.h
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Code/WMFViewController.m
  Wikipedia/Images.xcassets/insert-media/Contents.json
  Wikipedia/Images.xcassets/insert-media/blank.imageset/Contents.json
  Wikipedia/Images.xcassets/insert-media/blank.imageset/placeholder.pdf
  Wikipedia/Images.xcassets/insert-media/toolbar-icon.imageset/Contents.json
  Wikipedia/Images.xcassets/insert-media/toolbar-icon.imageset/media.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome
