Repository wikimedia/wikipedia-ios, pull requests merged in 2019-09, with the labels that each got.

#3226 Fix failing main thread assertion
  Wikipedia/Code/WMFImageGalleryViewController.m
Labels: Changes welcome, Low Impact

#3221 Fix iPad TOC scroll regression
  Wikipedia/Code/WMFArticleViewController.m
Labels: Changes welcome

#3228 Push settings onto the navigation stack
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFSettingsViewController.m
Labels: Changes welcome

#3208 Change -webkit-text-size-adjust to font-size
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.m
  Wikipedia/assets/styleoverrides.css
  www/less/misc.less
  www/less/refs.less
Labels: Changes welcome

#3231 Remove line-height adjustment
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.m
Labels: Changes welcome

#3232 Fix random button on iOS 13
  Wikipedia/Code/WMFRandomDiceButton.m
Labels: Low Impact

#3234 fix editor dismissing upon background in iPadOS
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFTableOfContentsViewController.swift
Labels: Changes welcome

#3237 Fix missing completion when fragment is missing
  Wikipedia/Code/WebViewController.m
Labels: Low Impact

#3238 Fix for fragments with percent encoding
  Wikipedia/Code/WMFArticleViewController.m
Labels: Low Impact

#3233 Restore Explore content offset
  WMF Framework/NavigationState.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NavigationStateController.swift
Labels: Changes welcome

#3240 Fix search icon color in languages
  Wikipedia/Code/WMFLanguagesViewController.m
Labels: Low Impact

#3244 Fix unreadable news notification on dark theme
  InTheNewsNotification/Base.lproj/MainInterface.storyboard
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/WMFExploreFeedContentController.m
Labels: Changes welcome, Low Impact

#3249 Add dark appearance variants for onboarding images
  Wikipedia/Images.xcassets/ftux-background-calendar.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-calendar.imageset/group8.pdf
  Wikipedia/Images.xcassets/ftux-background-chart.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-chart.imageset/page1.pdf
  Wikipedia/Images.xcassets/ftux-background-circle.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-circle.imageset/oval5.pdf
  Wikipedia/Images.xcassets/ftux-background-globe.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-globe.imageset/iconExplore.pdf
  Wikipedia/Images.xcassets/ftux-background-langs.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-langs.imageset/languageIcon.pdf
  Wikipedia/Images.xcassets/ftux-background-map-dot.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-map-dot.imageset/combinedShape.pdf
  Wikipedia/Images.xcassets/ftux-background-plus.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-plus.imageset/lineLineCopy.pdf
  Wikipedia/Images.xcassets/ftux-background-shield-star.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-background-shield-star.imageset/page1.pdf
  Wikipedia/Images.xcassets/ftux-langs-left.imageset/Contents.json
  Wikipedia/Images.xcassets/ftux-langs-left.imageset/noshadow.pdf
Labels: Changes welcome, Low Impact

#3250 Fix misplaced alert messages
  Wikipedia/Code/WMFThemeableNavigationController.m
Labels: Changes welcome, Low Impact

#3248 Reading themes changes design review fixes
  WMF Framework/Theme.swift
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/ImageDimmingExampleViewController.swift
  Wikipedia/Code/ImageDimmingExampleViewController.xib
Labels: Changes welcome, Low Impact

#3247 Fix links not opening in the app in iOS 13
  ContinueReadingWidget/WMFTodayContinueReadingWidgetViewController.swift
  FeaturedArticleWidget/FeaturedArticleWidget.swift
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  TopReadWidget/WMFTodayTopReadWidgetViewController.swift
  WMF Framework/ExtensionViewController.swift
  Wikipedia/Code/NSURL+WMFLinkParsing.h
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/URL+WMFLinkParsing.swift
Labels: Changes welcome

#3243 Fix reference popover location on iPad for iOS 12 and newer
  Wikipedia/Code/WebViewController.m
Labels: Changes welcome, Low Impact

#3251 Focused fix for T232022 that preserves ToC animation
  Wikipedia/Code/UIScrollView+WMFContentOffsetUtils.m
Labels: Changes welcome, Low Impact

#3254 Tighten up ToC animation on iPhone
  Wikipedia/Code/WMFArticleContainerViewController+TOC.swift
  Wikipedia/Code/WMFTableOfContentsAnimator.swift
Labels: Low Impact

#3253 Ensure scroll stops when scrolling to a new section
  Wikipedia/Code/UIScrollView+WMFContentOffsetUtils.m
Labels: Low Impact

#3259 Fix cell separator not stretching full width on iOS 13
  Wikipedia/Code/TextFormattingTableViewCell.swift
Labels: Changes welcome, Low Impact

#3258 Saved article not updated with reading list tag after article added to a reading list
  WMF Framework/WMFArticle+Extensions.swift
Labels: Low Impact

#3261 Contributing tag name
  CONTRIBUTING.md
  Wikipedia/Code/AboutViewController.plist
Labels: Hold, Low Impact

#3260 Fix incorrect empty view in Search results
  Wikipedia/Code/UIViewController+WMFEmptyView.m
Labels: Low Impact

#3262 Remove yOffset hack for the reference rect
  Wikipedia/Code/WebViewController.m
Labels: Low Impact

#3264 Remove SFSafariViewController use from WMFArticleViewController
  Wikipedia/Code/WMFArticleViewController.m
Labels: Low Impact

#3263 Open Insert Media image urls in Safari
  Wikipedia/Code/InsertMediaSearchResultsCollectionViewController.swift
  Wikipedia/Code/InsertMediaSelectedImageViewController.swift
  Wikipedia/Code/InsertMediaSettingsViewController.swift
Labels: Low Impact

#3265 Remove all SafariServices references
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/InsertMediaSearchResultsCollectionViewController.swift
  Wikipedia/Code/InsertMediaSelectedImageViewController.swift
  Wikipedia/Code/InsertMediaSettingsViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: Low Impact

#3266 Workaround for iOS 13 constraint breakage
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/WMFViewController.m
Labels: Changes welcome

#3268 6.4.1 and update fastlane
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  Gemfile.lock
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia Local-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: Low Impact

#3270 Show Wikidata API error message
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: Low Impact

#3269 Fix Description editing welcome CTA button not working
  Wikipedia/Code/DescriptionWelcome.storyboard
  Wikipedia/Code/DescriptionWelcomeContainerViewController.swift
  Wikipedia/Code/DescriptionWelcomePageViewController.swift
  Wikipedia/Code/DescriptionWelcomePanelViewController.swift
Labels: Changes welcome, Low Impact

#3275 Fix iOS 13 bugs in Link & Image wizards
  Wikipedia/Code/Advanced Settings/InsertMediaAdvancedSettingsViewController.swift
  Wikipedia/Code/Advanced Settings/InsertMediaImagePositionSettingsViewController.swift
  Wikipedia/Code/Advanced Settings/InsertMediaImageSizeSettingsViewController.swift
  Wikipedia/Code/Advanced Settings/InsertMediaImageTypeSettingsViewController.swift
  Wikipedia/Code/InsertMediaSearchResultsCollectionViewController.swift
  Wikipedia/Code/InsertMediaSelectedImageViewController.swift
  Wikipedia/Code/InsertMediaSettingsViewController.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
Labels: Low Impact

#3278 Dispatch captcha failures to main thread
  Wikipedia/Code/WMFLoginViewController.swift
Labels: Changes welcome, Low Impact

#3272 Fix TOC highlighting wrong section sometimes
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/MWKSectionList.h
  Wikipedia/Code/MWKSectionList.m
  Wikipedia/Code/WKWebView+ElementLocation.h
  Wikipedia/Code/WKWebView+ElementLocation.m
  Wikipedia/Code/WMFArticleContainerViewController+TOC.swift
  Wikipedia/Code/WMFArticleViewController.h
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFTableOfContentsViewController.swift
  Wikipedia/Code/WebViewController.h
  Wikipedia/Code/WebViewController.m
  Wikipedia/assets/index.js
  www/js/elementLocation.js
Labels: Changes welcome
