Repository wikimedia/wikipedia-ios, pull requests merged in 2019-02, with the labels that each got.

#2878 fix code mirror leading space (on a line) color
  Wikipedia/assets/codemirror/codemirror-common.css
  www/codemirror/codemirror-common.css
Labels: 6.2, Low impact

#2875 Add haptic feedback to Save for later & Reveal more edit toolbar button
  Wikipedia/Code/DefaultEditToolbarView.swift
  Wikipedia/Code/SaveButtonsController.swift
Labels: Design question(s), Low impact

#2881 Ensure basic edit funnels/event logging events are working
  Wikipedia/Code/EditSaveViewController.swift
Labels: 6.2, Low impact

#2876 Edit preview/save pixel push session
  Wikipedia/Code/EditSaveViewController.storyboard
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/EditSummaryViewController.swift
  Wikipedia/Code/EditSummaryViewController.xib
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2

#2884 Remove unused glyph font
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKLicense+ToGlyph.h
  Wikipedia/Code/MWKLicense+ToGlyph.m
  Wikipedia/Code/WMFImageGalleryDetailOverlayView.m
  Wikipedia/Code/WikiGlyph_Chars.h
  Wikipedia/Fonts/WikiFont-Glyphs.ttf
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia OSM-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
Labels: 6.2, Low impact

#2885 Remove padded label
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/PaddedLabel.h
  Wikipedia/Code/PaddedLabel.m
  Wikipedia/Code/PageHistoryViewController.m
Labels: 6.2, Low impact

#2886 Remove unused image
  Wikipedia/Images.xcassets/add-language.imageset/Contents.json
  Wikipedia/Images.xcassets/add-language.imageset/language-add.pdf
Labels: 6.2, Low impact

#2887 Fix wikidata description editing event logging bugs
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/EditFunnel.h
  Wikipedia/Code/EditFunnel.m
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.2, Low impact

#2890 Log error code when logging Wikidata description editing errors
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.2, Changes welcome, Low impact

#2889 Separate accessibility labels to avoid composing string localizations
  Wikipedia/Code/SectionEditorButton.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2, Low impact

#2892 fix constraint error on large dynamic text sizes
  Wikipedia/Code/EditSaveViewController.swift
Labels: 6.2, Low impact

#2891 Editor dynamic type support
  Wikipedia/Code/CodemirrorSetupUserScript.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/codemirror/resources/addon/search/search.js
  www/codemirror/codemirror-index.html
Labels: 6.2, Low impact

#2893 Issues with picture of the day
  Wikipedia/Code/WMFImageGalleryViewController.m
Labels: 6.2

#2888 Add "edit published" hint
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AddArticlesToReadingListViewController.swift
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/EditHintController.swift
  Wikipedia/Code/EditHintViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HintController.swift
  Wikipedia/Code/HintViewController.swift
  Wikipedia/Code/HintViewController.xib
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListHintController.swift
  Wikipedia/Code/ReadingListHintViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleViewController.h
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Images.xcassets/published-pencil.imageset/Contents.json
  Wikipedia/Images.xcassets/published-pencil.imageset/group.pdf
Labels: 6.2, Changes welcome

#2894 Tag build before uploading to the app store
  fastlane/Fastfile
Labels: 6.2, Low impact

#2898 Can't edit yuewp Top Read articles in iOS App
  Wikipedia/assets/codemirror/config/codemirror-config-yue.json
  Wikipedia/assets/languages.json
  codemirror-config/main.swift
Labels: 6.2

#2895 Show "no internet connection" on search instead of top alert
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/UIViewController+WMFEmptyView.h
  Wikipedia/Code/UIViewController+WMFEmptyView.m
  Wikipedia/Code/WMFEmptyView.h
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Images.xcassets/no-internet-blank.imageset/Contents.json
  Wikipedia/Images.xcassets/no-internet-blank.imageset/no-internet-blank.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2, Changes welcome

#2902 Restore edit toolbar top shadow
  Wikipedia/Code/EditToolbarView.swift
Labels: 6.2, Low impact

#2903 Remove carthage bootstrap from setup script
  scripts/setup
Labels: 6.2, Low impact

#2904 Add light haptic feedback to Save in Article view
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.2, Low impact

#2899 Can't view articles in certain languages
  Wikipedia/Code/WMFFeedArticlePreview.m
  WikipediaUnitTests/Fixtures/MCSFeedTopReadNewsItem.json
Labels: 6.2

#2905 Remove unused site info fetcher, model, & tests
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKSiteInfo.h
  Wikipedia/Code/MWKSiteInfo.m
  Wikipedia/Code/MWKSiteInfoFetcher.h
  Wikipedia/Code/MWKSiteInfoFetcher.m
  WikipediaUnitTests/Code/MWKSiteInfoFetcherTests.m
  scripts/setup_rbenv_and_ruby
Labels: 6.2, Low impact

#2911 Revert "Can't view articles in certain languages"
  Wikipedia/Code/WMFFeedArticlePreview.m
Labels: 6.2, Low Impact

#2908 Fix saved vc download status updating
  WMF Framework/WMFArticle+CoreDataClass.h
  WMF Framework/WMFArticle+CoreDataClass.m
  WMF Framework/WMFArticle+Extensions.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListEntryCollectionViewController.swift
  Wikipedia/Code/SavedArticlesCollectionViewController.swift
Labels: 6.2

#2913 Move the Find in Page icon to the first view of the toolbar
  Wikipedia/Code/DefaultEditToolbarView.swift
  Wikipedia/Code/DefaultEditToolbarView.xib
Labels: 6.2, Low Impact

#2915 6.2.1
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: 6.2.1, Low Impact

#2910 Use isEmpty instead of count > 0 to avoid redundant iteration
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  TopReadWidget/WMFTodayTopReadWidgetViewController.swift
  WMF Framework/CollectionViewEditController.swift
  WMF Framework/ColumnarCollectionViewLayoutInfo.swift
  WMF Framework/EventLoggingService.swift
  WMF Framework/Fetcher.swift
  WMF Framework/HasText.swift
  WMF Framework/NSManagedObject+Extensions.swift
  WMF Framework/ReadingList+CoreDataClass.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/SummaryExtensions.swift
  WMF Framework/WMFArticle+Extensions.swift
  WMF Framework/WMFCaptchaViewController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Array<UITextField>+WMFAllFieldsFilled.swift
  Wikipedia/Code/ArticleLocationController.swift
  Wikipedia/Code/CollectionViewUpdater.swift
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HTTPCookieStorage+Migration.swift
  Wikipedia/Code/ImageControllerCompletionManager.swift
  Wikipedia/Code/MWKSavedPageList.m
  Wikipedia/Code/NSArray+WMFExtensions.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/PlaceSearchService.swift
  Wikipedia/Code/PlaceSearchSuggestionController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListEntryCollectionViewController.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/ReadingListsViewController.swift
  Wikipedia/Code/SaveButtonsController.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/ShareAFactViewController.swift
  Wikipedia/Code/SideScrollingCollectionViewCell.swift
  Wikipedia/Code/TextFontFormattingTableViewController.swift
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WMFAccountCreationViewController.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFCaptchaResetter.swift
  Wikipedia/Code/WMFChangePasswordViewController.swift
  Wikipedia/Code/WMFDatabaseHouseKeeper.swift
  Wikipedia/Code/WMFFeedArticlePreview+DescriptionOrSnippet.swift
  Wikipedia/Code/WMFForgotPasswordViewController.swift
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFPasswordResetter.swift
  WikipediaUITests/XCUIApplication+SnapshotUtilities.swift
  WikipediaUnitTests/Code/Collection+AsyncMapTests.swift
  WikipediaUnitTests/Code/NSArray+WMFExtensionsTests.m
  scripts/localization.swift
Labels: 6.2.1, Changes welcome

#2912 Can't view articles in certain languages
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/WMFFeedArticlePreview.m
Labels: 6.2.1

#2916 Set edit funnel for EditPreviewViewController & EditSaveViewController
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2, Low Impact

#2879 Update pagelib and css
  Makefile
  Wikipedia/assets/abusefilter.css
  Wikipedia/assets/preview.css
  Wikipedia/assets/styles.css
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/package-lock.json
  www/package.json
Labels: 6.2.1

#2917 Use https for beta cluster tests
  WikipediaBetaClusterTests/WikipediaBetaClusterTests.m
Labels: 6.2.1, Low Impact

#2918 Remove URLSessionTaskOperation, fix KVO crash
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/URLSessionTaskOperation.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/Session.swift
Labels: 6.2, Low Impact

#2920 Add normalized_code to www/languages.json, make grunt to sync with codemirrror
  Wikipedia/assets/codemirror/resources/addon/search/search.js
  Wikipedia/assets/languages.json
  www/languages.json
Labels: 6.2

#2921 Separate wikimedia and wikipedia apps services URLs
  WMF Framework/Configuration.swift
  WMF Framework/WMFAnnouncementsFetcher.m
  WMF Framework/WMFOnThisDayEventsFetcher.m
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WMFFeedContentFetcher.m
Labels: 6.2, Low Impact

#2914 Fix edit toolbar constraints on various devices
  Wikipedia/Code/DefaultEditToolbarView.xib
Labels: 6.2, Design Question(s), Low Impact

#2919 Finish Session/Fetcher refactor
  WMF Framework/CSRFTokenOperation.swift
  WMF Framework/Fetcher.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/Session.swift
Labels: 6.2.1, Changes welcome

#2924 Update scripts & documentation
  .node-version
  Makefile
  README.md
  Wikipedia.xcodeproj/project.pbxproj
  docs/web-dev.md
  scripts/setup_fastlane
  scripts/setup_npm
  scripts/setup_www
  www/.node-version
Labels: 6.2.1, Low Impact

#2923 Log article language in edit events
  Wikipedia/Code/EditFunnel.h
  Wikipedia/Code/EditFunnel.m
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/MWKSection.h
  Wikipedia/Code/MWKSection.m
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2, Low Impact

#2926 Fix edit anchor button state when nested inside template
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2, Low Impact

#2927 Can't edit in Cantonese (missing CodeMirror config)
  Wikipedia/assets/codemirror/config/codemirror-config-zh-yue.json
  codemirror-config/main.swift
Labels: 6.2, Low Impact

#2930 Handle more states in toggleMarkup
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2

#2929 Pull language from content_urls instead of lang
  Wikipedia/Code/WMFFeedArticlePreview.h
  Wikipedia/Code/WMFFeedArticlePreview.m
Labels: 6.2

#2928 Clean up documentation
  README.md
  docs/ci.md
  docs/cont-integration.md
  docs/event_logging.md
  docs/process.md
  docs/ruby.md
  docs/web_dev.md
Labels: 6.2.1, Changes welcome

#2932 Fix theme regression
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
Labels: 6.2.1, Low Impact

#2933 Less invasive fix for empty SFSafariViewController bug
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/UIViewController+WMFOpenExternalUrl.m
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.2.1, Changes welcome

#2934 Update fastlane install instructions
  docs/ci.md
  scripts/setup_fastlane
Labels: 6.2.1, Changes welcome, Low Impact

#2937 Fix gap in search results after rotating
  Wikipedia/Code/SearchViewController.swift
Labels: 6.2.1

#2939 Remove unused queue
  Wikipedia/Code/Session.swift
Labels: 6.2.1, Low Impact

#2935 Fix image gallery license and info buttons
  Wikipedia/Code/UIViewController+WMFOpenExternalUrl.m
  Wikipedia/Code/WMFImageGalleryViewController.m
Labels: 6.2.1

#2936 Clean up documentation (again)
  Makefile
  README.md
  docs/ci.md
  docs/ruby.md
  docs/web_dev.md
  scripts/setup_www
Labels: 6.2.1, Changes welcome, Low Impact

#2941 Fix reference tag toggle behavior in the section editor
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2.1

#2942 Use bold font on edit abuse filter message
  Wikipedia/Code/AbuseFilterAlertView.xib
Labels: 6.2.1, Low Impact

#2943 Update canned edit summary button theme colors
  Wikipedia/Code/EditSummaryViewController.swift
Labels: 6.2.1, Low Impact

#2944 Remove close 'x' button from no connection panel
  Wikipedia/Code/Panels.swift
Labels: 6.2.1, Low Impact

#2946 Fix beta_cluster_tests and verify_test_platforms
  fastlane/Fastfile
Labels: 6.2.1, Low Impact

#2947 Update localization document to reflect plural changes
  docs/localization.md
Labels: 6.2.1, Changes welcome, Low Impact

#2940 Update Ruby & bundler to latest versions
  .ruby-version
  Gemfile.lock
Labels: 6.2.1
