Repository wikimedia/wikipedia-ios, pull requests merged in 2019-11, with the labels that each got.

#3315 EventLogging validation errors for MobileWikiAppiOSUserHistory
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
Labels: Low Impact

#3314 Replace asynchronouslyCacheArticle:toDisk: with a sync method
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/WMFArticleFetcher.m
  WikipediaUnitTests/Code/ArticleFetcherTests.m
Labels: Low Impact

#3318 Wire up revision 'thanking'
  WMF Framework/CommonStrings.swift
  WMF Framework/Theme.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/DiffController.swift
  Wikipedia/Code/DiffThanker.swift
  Wikipedia/Code/HintController.swift
  Wikipedia/Code/HintViewController.swift
  Wikipedia/Code/HintViewController.xib
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Images.xcassets/diff/diff-smile-filled.imageset/Contents.json
  Wikipedia/Images.xcassets/diff/diff-smile-filled.imageset/diff-smile-filled.pdf
  Wikipedia/Images.xcassets/diff/diff-smile-heart.imageset/Contents.json
  Wikipedia/Images.xcassets/diff/diff-smile-heart.imageset/diff-smile-heart.pdf
  Wikipedia/Images.xcassets/diff/diff-smile.imageset/Contents.json
  Wikipedia/Images.xcassets/diff/diff-smile.imageset/diff-smile.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
Labels: Changes welcome, Update branch before merging

#3319 Define in article announcement user experience for iOS app
  WMF Framework/HasText.swift
  WMF Framework/WMFAnnouncement.h
  WMF Framework/WMFAnnouncement.m
  WMF Framework/WMFContentGroup+CoreDataProperties.h
  WMF Framework/WMFContentGroup+CoreDataProperties.m
  WMF Framework/WMFContentGroup+Extensions.h
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 2.xcdatamodel/contents
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/ScrollableEducationPanelView.xib
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFArticleViewController.m
Labels: Changes welcome

#3325 Update pagelib to fix T236613
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
Labels: Low Impact

#3326 bump version number to 6.5.0
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia Local-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: Low Impact

#3324 Fix AlignedImageButton for RTL & iOS 13
  Wikipedia/Code/AlignedImageButton.swift
Labels: Low Impact

#3329 [Regression] Add missing button border in panels
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
Labels: Low Impact

#3327 remove wmflabs hardcoding for history & diffs
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/DiffController.swift
  Wikipedia/Code/DiffFetcher.swift
  Wikipedia/Code/PageHistoryCountsViewController.swift
  Wikipedia/Code/PageHistoryCountsViewController.xib
  Wikipedia/Code/PageHistoryFetcher.swift
  Wikipedia/Code/PageHistoryFilterCountsViewController.swift
  Wikipedia/Code/PageHistoryViewController.swift
  Wikipedia/Code/TalkPagesController.swift
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticleRevisionFetcher.h
  Wikipedia/Code/WMFArticleRevisionFetcher.m
  WikipediaUnitTests/Code/TalkPageControllerTests.swift
Labels: Low Impact

#3330 Fix vc insets on iOS 13
  Wikipedia/Code/ViewController.swift
Labels: Changes welcome, Low Impact

#3328 Fix typo
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
Labels: Low Impact

#3331 Render the "m" image as template so that it's visible on dark themes
  Wikipedia/Images.xcassets/minor-edit.imageset/Contents.json
Labels: Low Impact

#3332 Fix iPad crash
  Wikipedia/Code/DiffContainerViewController.swift
Labels: Low Impact

#3335 Remove unused code
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/UILabel+WMFStyling.swift
  Wikipedia/Code/UIView+WMFRoundCorners.h
  Wikipedia/Code/UIView+WMFRoundCorners.m
  Wikipedia/Code/UIView+WMFShadow.h
  Wikipedia/Code/UIView+WMFShadow.m
Labels: Changes welcome, Low Impact

#3337 Diffs design updates
  WMF Framework/NavigationBar.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/DiffHeaderCompareView.xib
  Wikipedia/Code/DiffHeaderExtendedView.swift
  Wikipedia/Code/DiffHeaderExtendedView.xib
  Wikipedia/Code/DiffHeaderViewModels.swift
  Wikipedia/Code/DiffListChangeCell.swift
  Wikipedia/Code/DiffListChangeItemViewModel.swift
  Wikipedia/Code/DiffListContextCell.swift
  Wikipedia/Code/DiffListContextViewModel.swift
  Wikipedia/Code/DiffListViewController.swift
  Wikipedia/Code/NSDate+WMFRelativeDate.h
  Wikipedia/Code/NSDate+WMFRelativeDate.m
  Wikipedia/Code/UIFont+Extensions.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/as.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/azb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ba.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/be-tarask.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/bgn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ce.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/cnh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/cy.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/diq.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fo.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/haw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/hrx.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/hsb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/hy.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ka.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/kn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/krc.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ksh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ku-latn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/mai.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/om.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/or.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/pa.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ro.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sa.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sco.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tcy.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/te.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tg-cyrl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/uz.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/vec.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/xmf.lproj/Localizable.stringsdict
Labels: WIP

#3343 Add Ammar Abdulhamid to the list of contributors
  Wikipedia/Code/AboutViewController.plist
Labels: Low Impact

#3344 Diff - handle first revision in history
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/DiffController.swift
  Wikipedia/Code/DiffFetcher.swift
  Wikipedia/Code/DiffHeaderViewModels.swift
  Wikipedia/Code/DiffListChangeItemViewModel.swift
  Wikipedia/Code/DiffListChangeViewModel.swift
  Wikipedia/Code/DiffListViewController.swift
  Wikipedia/Code/DiffTransformer.swift
Labels: Low Impact

#3352 diff - fix thank selected state bugs
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/DiffToolbarView.swift
Labels: Low Impact

#3301 Attempt re-login on 401 response
  WMF Framework/Fetcher.swift
  WMF Framework/WMFLegacyFetcher.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAccountLogin.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
Labels: Changes welcome

#3355 History - restore counts
  Wikipedia/Code/PageHistoryViewController.swift
Labels: Changes welcome

#3353 Crash fixes
  WMF Framework/ColumnarCollectionViewLayout.swift
Labels: Changes welcome, WIP

#3358 Increase some single diff text sizes
  Wikipedia/Code/DiffHeaderEditorView.swift
  Wikipedia/Code/DiffHeaderSummaryView.swift
Labels: Changes welcome, Low Impact

#3356 Increase single diff next/prev button touch targets
  Wikipedia/Code/DiffToolbarView.swift
  Wikipedia/Code/DiffToolbarView.xib
Labels: Changes welcome, Low Impact

#3364 added 'Intro' section header on single revision diff screen
  Wikipedia/Code/DiffNetworkModels.swift
  Wikipedia/Code/DiffTransformer.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome, Low Impact

#3365 Update education panel copy
  Wikipedia/Code/Panels.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome, Low Impact

#3366 Ignore resign active requirement for WMF_ANNOUNCEMENT_DATE_IGNORE
  Wikipedia/Code/WMFAnnouncementsContentSource.m
Labels: Changes welcome, Low Impact

#3371 diff - toolbar spacing tweaks
  Wikipedia/Code/DiffToolbarView.swift
  Wikipedia/Code/DiffToolbarView.xib
Labels: Changes welcome, Low Impact

#3372 announcement fixes
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: Changes welcome, Low Impact

#3373 Use Safari for feed announcement links
  Wikipedia/Code/ExploreCardViewController.swift
Labels: Changes welcome, Low Impact

#3368 Add event logging for in-article fundraising impressions
  WMF Framework/WMFContentGroup+EventLogging.swift
  Wikipedia/Code/EventLoggingFunnel.h
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/FeedFunnel.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: Changes welcome, Low Impact

#3374 Fix relative time string sometimes returning nothing
  Wikipedia/Code/NSDate+WMFRelativeDate.m
Labels: Changes welcome, Low Impact

#3370 Allow diff revision cells to be treated as atomic accessibility links
  Wikipedia/Code/PageHistoryCollectionViewCell.swift
  Wikipedia/Code/PageHistoryCountsViewController.swift
  Wikipedia/Code/PageHistoryViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome, Low Impact
