Repository wikimedia/wikipedia-ios, pull requests merged in 2019-07, with the labels that each got.

#3166 fatalError fix - no default reading list workaround
  Wikipedia/Code/SavedArticlesCollectionViewController.swift
  Wikipedia/Code/SavedViewController.swift
Labels: Changes welcome, Low Impact

#3172 Bump version to 6.3.1, update fastlane
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  Gemfile.lock
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia Local-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: Changes welcome, Low Impact

#3173 Fix missing headers
  Wikipedia/Code/Session.swift
Labels: Low Impact

#3159 Remove HTML from navigation bar title in Talk Page reply VC
  WMF Framework/String+HTML.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
Labels: Changes welcome, Low Impact

#3175 NonBeta label test for xcode-select nonbeta
  Jenkinsfile
  fastlane/Fastfile
Labels: Changes welcome

#3170 Universal link support for User:Talk
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/PageNamespace.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleSummaryController.swift
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/WMFAppViewController.h
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFThemeableNavigationController.h
  Wikipedia/Code/WMFThemeableNavigationController.m
Labels: Changes welcome

#3176 Show empty view when there's no Featured article (widget)
  FeaturedArticleWidget/FeaturedArticleWidget.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  scripts/localization_extract
Labels: Changes welcome, Low Impact

#3163 Handle redirects from summary responses
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/RelatedSearchFetcher.swift
  WMF Framework/SummaryExtensions.swift
  WMF Framework/WMFArticle+Extensions.h
  WMF Framework/WMFArticle+Extensions.m
  WMF Framework/WMFContentGroup+Display.swift
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/ArticleSummaryController.swift
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/DisambiguationPagesViewController.swift
  Wikipedia/Code/EditLinkViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKHistoryList.m
  Wikipedia/Code/MWKSavedPageList.h
  Wikipedia/Code/MWKSavedPageList.m
  Wikipedia/Code/NSURL+WMFLinkParsing.h
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/PlaceSearch.swift
  Wikipedia/Code/PlaceSearchService.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/SavedArticlesFetcher.m
  Wikipedia/Code/SchemeHandler/SchemeHandler+ArticleSectionHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandlerCache.swift
  Wikipedia/Code/ShareActivityController.swift
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageLocalHandler.swift
  Wikipedia/Code/URL+WMFLinkParsing.swift
  Wikipedia/Code/WKWebView+LoadAssetsHtml.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFDatabaseHouseKeeper.swift
  Wikipedia/Code/WMFFeedContentSource.m
  Wikipedia/Code/WMFNearbyContentSource.m
  Wikipedia/Code/WMFRelatedPagesContentSource.m
  WikipediaUnitTests/Code/MWKHistoryListUniquenessTests.m
  WikipediaUnitTests/Code/MWKSavedPageListTogglingTests.m
  WikipediaUnitTests/Code/NSURL+WMFLinkParsingTests.m
  WikipediaUnitTests/Code/TalkPageLocalHandlerTests.swift
  WikipediaUnitTests/Code/WMFArticleTests.swift
Labels: Changes welcome

#3177 Update languages.json in www
  www/languages.json
Labels: Low Impact

#3178 Talk Page pull to refresh
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AccountViewController.swift
  Wikipedia/Code/EmptyRefreshingViewController.swift
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
  Wikipedia/Code/TalkPageTopicListViewController.swift
  Wikipedia/Code/TalkPageTopicNewViewController.swift
  Wikipedia/Code/UIViewController+WMFEmptyView.h
  Wikipedia/Code/UIViewController+WMFEmptyView.m
Labels: Changes welcome

#3148 talk pages - performance tweaks for update method
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/TalkPageLocalHandler.swift
  WikipediaUnitTests/Code/TalkPageControllerTests.swift
  WikipediaUnitTests/Code/TalkPageFetcherTests.swift
  WikipediaUnitTests/Code/TalkPageLocalHandlerTests.swift
  WikipediaUnitTests/Code/TalkPageNetworkDataTests.swift
  WikipediaUnitTests/Code/TalkPageTestHelpers.swift
  WikipediaUnitTests/Fixtures/TalkPage-extrasmall.json
  WikipediaUnitTests/Fixtures/TalkPage-large-updated.json
  WikipediaUnitTests/Fixtures/TalkPage-large.json
  WikipediaUnitTests/Fixtures/TalkPage-small-updated.json
  WikipediaUnitTests/Fixtures/TalkPage-small.json
Labels: Low Impact

#3183 fastlane & screenshot updates for xcode 10.3
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/test0ReferenceOutput_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeGreenBackgroundColorsToBlue_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testChangeReduceLineSpacing_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemoveAllStrikeThroughs_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFModifyTests/testRemovingLink_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrimReference_11_4_LTR@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrimReference_12_2_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrim_11_4_LTR@2x.png
  WikipediaUnitTests/ReferenceImages_64/NSAttributedString_WMFTrimTests/testTrim_12_2_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testCentersPresObamasFaceVertically_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageNotCroppedBecauseFacesAreTooSmall_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testImageShorterThanViewIsNotStretched_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/UIImageViewWMFImageFetchingVisualTests/testUsesSpecifiedContentModeBehaviorOnFeaturelessImage_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImageAndNoSubtitle_12_4_RTL@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithImage_12_4_RTL@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImageAndNoSubtitle_12_4_RTL@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFArticlePreviewViewControllerVisualTests/testWithoutImage_12_4_RTL@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testLongTitle_12_4_RTL@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_12_4_LTR@3x.png
  WikipediaUnitTests/ReferenceImages_64/WMFSettingsCellVisualTests/testShortTitle_12_4_RTL@3x.png
  fastlane/Fastfile
Labels: Changes welcome, Low Impact

#3184 Update fastlane
  Gemfile.lock
Labels: Low Impact

#3171 Fix explore feed card visibility on initial install
  Wikipedia/Code/WMFAnnouncementsContentSource.m
Labels: Changes welcome, Low Impact

#3185 track source for edit preview event
  Wikipedia/Code/EditFunnel.swift
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
Labels: Changes welcome, Low Impact

#3182 add language switch button & functionality to talk pages
  WMF Framework/CommonStrings.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/TalkPage+Extensions.swift
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome

#3186 hide reading themes card
  Wikipedia/Code/WMFAnnouncementsContentSource.m
Labels: Changes welcome, Low Impact

#3191 offset for find & replace adjusted content inset bugs
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorViewController.swift
Labels: Changes welcome
