Repository wikimedia/wikipedia-ios, pull requests merged in 2019-05, with the labels that each got.

#3068 Design review updates: Link previews
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/EditPreviewInternalLinkViewController.swift
  Wikipedia/Code/EditPreviewInternalLinkViewController.xib
Labels: Changes welcome, Low Impact, Question(s)

#3071 Add GlobalPreferencesController and GlobalPreferencesFetcher
  WMF Framework/Configuration.swift
  WMF Framework/Fetcher.swift
  WMF Framework/GlobalPreferencesController.swift
  WMF Framework/GlobalPreferencesFetcher.swift
  WMF Framework/WMFKeyValue+Extensions.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: Changes welcome

#3074 Use document.body instead of querySelector or getElementsByTagName
  Wikipedia/Code/AboutViewController.m
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.m
  Wikipedia/Code/WebViewController.m
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/index.js
  www/codemirror/codemirror-index.html
  www/js/footers.js
Labels: Changes welcome, Low Impact

#3069 Design review updates: Insert media
  Wikipedia/Code/Advanced Settings/InsertMediaAdvancedSettingsViewController.swift
  Wikipedia/Code/InsertMediaImageInfoView.swift
  Wikipedia/Code/InsertMediaImageInfoView.xib
  Wikipedia/Code/InsertMediaSearchResultCollectionViewCell.swift
  Wikipedia/Code/InsertMediaSearchResultsCollectionViewController.swift
  Wikipedia/Code/InsertMediaSelectedImageViewController.swift
  Wikipedia/Code/InsertMediaSettingsImageView.swift
  Wikipedia/Code/InsertMediaSettingsImageView.xib
  Wikipedia/Code/InsertMediaSettingsTextTableViewCell.swift
  Wikipedia/Code/InsertMediaSettingsViewController.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/Images.xcassets/info-white.imageset/Contents.json
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/codemirror/codemirror-range-determination-bundle.js
  www/codemirror/codemirror-index.html
  www/codemirror/codemirror-range-clear-formatting.js
  www/codemirror/codemirror-range-determination-non-tag.js
  www/codemirror/codemirror-range-main.js
  www/codemirror/codemirror-range-objects.js
Labels: Changes welcome, Design Question(s), Low Impact

#3078 Remove shadow from the Toolbar on Reading themes (dark, black, sepia)
  Wikipedia/Code/EditToolbarView.swift
Labels: Design Question(s), Low Impact

#3080 Remove shadow from the Toolbar input views on Reading themes (dark, black, sepia), update inputAccessoryBackground
  WMF Framework/Theme.swift
  Wikipedia/Code/EditToolbarView.swift
  Wikipedia/Code/TextFormattingInputViewController.swift
Labels: Low Impact

#3082 Run make grunt to get the latest codemirror.html changes
  Wikipedia/assets/codemirror/codemirror-index.html
Labels: Low Impact

#3083 Fix Insert Media constraint crash
  Wikipedia/Code/SectionEditorViewController.swift
Labels: Low Impact

#3084 Display link text in Edit Link view even if there's no label
  Wikipedia/Code/EditLinkViewController.swift
Labels: Low Impact

#3086 Update conditions for inserting a new link
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: Low Impact

#3087 Fix insert media info button and add clear button to media settings text views
  WMF Framework/CommonStrings.swift
  Wikipedia/Code/InsertMediaSelectedImageViewController.swift
  Wikipedia/Code/InsertMediaSettingsTextTableViewCell.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/ThemeableTextView.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Low Impact

#3092 Fix WebKit crash caused by a deallocation of a WKURLSchemeTask on a thread other than main
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/Session.swift
Labels: Changes welcome

#3091 Update build settings for User Testing & WikipediaUITests
  Wikipedia.xcodeproj/project.pbxproj
  WikipediaUITests/XCUIApplication+SnapshotUtilities.swift
Labels: Changes welcome, Low Impact

#3095 Fix article alert label for RTL
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
Labels: Low Impact

#3096 Bouncing down on reading list details screen is jittery
  WMF Framework/CollectionViewEditController.swift
  Wikipedia/Code/ReadingListDetailUnderBarViewController.xib
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/ReadingListEntryCollectionViewController.swift
Labels: Changes welcome, Low Impact

#3093 Wizards user testing tweaks
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Code/WMFEmptyView.xib
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  www/codemirror/codemirror-index.html
Labels: Low Impact

#3094 Implement accessibilityPerformEscape for VCs presented modally
  Wikipedia/Code/AddArticlesToReadingListViewController.swift
  Wikipedia/Code/CreateReadingListViewController.swift
  Wikipedia/Code/InsertLinkViewController.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/PageHistoryViewController.m
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SubSettingsViewController.swift
  Wikipedia/Code/WMFAccountCreationViewController.swift
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFSettingsViewController.m
Labels: Changes welcome, Low Impact

#3101 User Talk: Username is missing from the Account list item in Settings
  Wikipedia/Code/WMFSettingsMenuItem.m
Labels: Low Impact

#3098 Fix missing `Cancel` & `Done` buttons on reading list detail view
  WMF Framework/NavigationBar.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
Labels: Changes welcome

#3100 Update media settings' textViews' clearButton, resize textView when user clears text
  Wikipedia/Code/InsertMediaSettingsTextTableViewCell.swift
  Wikipedia/Code/InsertMediaSettingsViewController.swift
  Wikipedia/Code/ThemeableTextView.swift
Labels: Low Impact

#3102 Floating 'clear text' button appearing on the reply screen
  Wikipedia/Code/InsertMediaSettingsTextTableViewCell.swift
  Wikipedia/Code/TalkPageReplyFooterView.swift
  Wikipedia/Code/ThemeableTextView.swift
Labels: Low Impact, Update branch before merging

#3099 make "Please be kind" view an inputAccessoryView
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/BeKindInputAccessoryView.swift
  Wikipedia/Code/BeKindInputAccessoryView.xib
  Wikipedia/Code/InfoBannerView.swift
  Wikipedia/Code/TalkPageTopicNewViewController.swift
  Wikipedia/Code/TalkPageTopicNewViewController.xib
Labels: Changes welcome, Low Impact

#3106 Make "Be kind.." view an input accessory view (Reply screen)
  Wikipedia/Code/TalkPageReplyComposeView.swift
  Wikipedia/Code/TalkPageReplyFooterView.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
Labels: Changes welcome, Low Impact, Update branch before merging

#3108 Track read status of talk page topics, Core Data thread safety fixes
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 2.xcdatamodel/contents
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageFetcher.swift
  Wikipedia/Code/TalkPageLocalHandler.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
  Wikipedia/Code/TalkPageTopic+Extensions.swift
  Wikipedia/Code/TalkPageTopicCell.swift
  Wikipedia/Code/TalkPageTopicListViewController.swift
  Wikipedia/Code/TalkPagesController.swift
  WikipediaUnitTests/Code/TalkPageControllerTests.swift
  WikipediaUnitTests/Code/TalkPageLocalHandlerTests.swift
  WikipediaUnitTests/Code/TalkPageTestHelpers.swift
Labels: Changes welcome

#3110 talk page - added superscript and subscript handling
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/String+HTML.swift
  Wikipedia/Code/NSString+WMFHTMLParsing.h
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/NewsCollectionViewCell.swift
  Wikipedia/Code/TalkPageHeaderView.swift
  Wikipedia/Code/TalkPageReplyCell.swift
  Wikipedia/Code/TalkPageTopicCell.swift
Labels: Changes welcome, Low Impact

#3109 User talk is not showing in History
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/PageNamespace.swift
  WMF Framework/SummaryExtensions.swift
  WMF Framework/WMFArticle+CoreDataProperties.h
  WMF Framework/WMFArticle+CoreDataProperties.m
  WMF Framework/WMFArticle+Extensions.m
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 2.xcdatamodel/contents
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/MWKHistoryList.h
  Wikipedia/Code/MWKHistoryList.m
  Wikipedia/Code/NSNumber+MWKTitleNamespace.h
  Wikipedia/Code/NSNumber+MWKTitleNamespace.m
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/WMFContinueReadingContentSource.m
Labels: Changes welcome

#3113 Handle nested lists, remove broken wmf_trim extension from NSAttributedString
  InTheNewsNotification/WMFInTheNewsNotificationViewController.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NSAttributedString+WMFTrim.h
  Wikipedia/Code/NSAttributedString+WMFTrim.m
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/NewsCollectionViewCell.swift
  Wikipedia/Code/TalkPageHeaderView.swift
  Wikipedia/Code/TalkPageReplyCell.swift
  Wikipedia/Code/TalkPageTopicCell.swift
  WikipediaUnitTests/Code/NSAttributedString+WMFTrimTests.m
Labels: Changes welcome
