Repository wikimedia/wikipedia-ios, pull requests merged in 2019-08, with the labels that each got.

#3193 Update lodash
  www/package-lock.json
Labels: Low Impact

#3199 dismiss findAndReplaceView when user taps X on find and replace header
  Wikipedia/Code/AboutViewController.plist
  Wikipedia/Code/FindAndReplaceKeyboardBar.swift
  Wikipedia/Code/SectionEditorInputViewsController.swift
Labels: 6.4, Low Impact

#3200 Mark articles failing with specific image download issue as downloaded
  Wikipedia/Code/SavedArticlesFetcher.h
  Wikipedia/Code/SavedArticlesFetcher.m
Labels: Changes welcome

#3219 bump version to 6.4.0
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Wikipedia Alpha-Info.plist
  Wikipedia/Wikipedia Beta-Info.plist
  Wikipedia/Wikipedia Local-Info.plist
  Wikipedia/Wikipedia User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: Low Impact

#3190 Removed "dv" Divehi language from unsupportedLanguagesCodes
  Wikipedia/Code/MWKLanguageLinkController.m
Labels: Low Impact

#3213 iOS13 [Bug] - Reading Preferences Settings > font size unresponsive
  Wikipedia/Third Party Code/SWStepSlider/SWStepSlider.swift
Labels: Low Impact

#3222 Fix font size slider bug
  Wikipedia/Third Party Code/SWStepSlider/SWStepSlider.swift
Labels: Low Impact
