Repository wikimedia/wikipedia-ios, pull requests merged in 2019-06, with the labels that each got.

#3114 Update revision number of MobileWikiAppiOSUserHistory schema
  Wikipedia/Code/UserHistoryFunnel.swift
Labels: Low Impact

#3118 Add talk page preferences (auto-sign)
  Wikipedia/Code/AccountViewController.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/TalkPagesController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Low Impact

#3112 Track usage of the "open here to edit" feature
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/EditFunnel.h
  Wikipedia/Code/EditFunnel.m
  Wikipedia/Code/EditFunnel.swift
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WebViewController_Private.h
  Wikipedia/Code/Wikipedia-Bridging-Header.h
Labels: Changes welcome

#3117 Talk Page error & empty states
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPagesController.swift
  Wikipedia/Code/UIViewController+WMFEmptyView.h
  Wikipedia/Code/UIViewController+WMFEmptyView.m
  Wikipedia/Code/WMFAlertManager.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFEmptyView.h
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
  Wikipedia/Images.xcassets/empty-talk-page.imageset/Contents.json
  Wikipedia/Images.xcassets/empty-talk-page.imageset/group8.pdf
  Wikipedia/Images.xcassets/unable-to-load-talk-page.imageset/Contents.json
  Wikipedia/Images.xcassets/unable-to-load-talk-page.imageset/unable-to-load-talk-page.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Low Impact

#3119 Skip waiting for release build processing
  Gemfile.lock
  fastlane/Fastfile
Labels: Changes welcome, Low Impact

#3123 [Talk Pages Dev] add Share functionality
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageTopicListViewController.swift
  Wikipedia/Code/UIActivity.ActivityType+CustomTypes.swift
Labels: Changes welcome, Low Impact

#3121 Fix revealing the selected image when searching in Media Insert
  Wikipedia/Code/InsertMediaSearchViewController.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/NavigationBarHider.swift
Labels: Design Question(s), Low Impact

#3124 Editing event logging: log revision id only only on section edit save, log missing actions
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/EditFunnel.swift
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: Low Impact

#3128 Update talk page codable model objects to match new endpoint format
  WMF Framework/Configuration.swift
  Wikipedia/Code/TalkPageFetcher.swift
  Wikipedia/Code/TalkPageLocalHandler.swift
  WikipediaUnitTests/Code/TalkPageControllerTests.swift
  WikipediaUnitTests/Code/TalkPageFetcherTests.swift
  WikipediaUnitTests/Code/TalkPageNetworkDataTests.swift
  WikipediaUnitTests/Code/TalkPageTestHelpers.swift
Labels: Changes welcome, Low Impact

#3129 Default to auto-signing talk page discussions
  Wikipedia/Code/AppDelegate.m
Labels: Low Impact

#3125 Talk pages - handle additional links
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/FakeLoading.swift
  Wikipedia/Code/MWKLanguageLinkController.h
  Wikipedia/Code/MWKLanguageLinkController.m
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
  Wikipedia/Code/TalkPagesController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome

#3130 talk page - ensure only onscreen footer view is set for future resetting
  Wikipedia/Code/TalkPageReplyListViewController.swift
Labels: Changes welcome, Low Impact

#3131 talk page - make intro text tappable into reply thread
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 2.xcdatamodel/contents
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageFetcher.swift
  Wikipedia/Code/TalkPageHeaderView.swift
  Wikipedia/Code/TalkPageLocalHandler.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
  Wikipedia/Code/TalkPageTopicListViewController.swift
  WikipediaUnitTests/Code/TalkPageTestHelpers.swift
Labels: Changes welcome

#3137 Select to edit works on protected pages after navigating away
  Wikipedia/Code/WebViewController.m
Labels: Low Impact

#3134 talk page - CoreData housekeeping
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 2.xcdatamodel/contents
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageLocalHandler.swift
  Wikipedia/Code/TalkPagesController.swift
  Wikipedia/Code/WMFDatabaseHouseKeeper.swift
Labels: Changes welcome

#3136 Add Giphy sticker pack to app package
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Astronaut animated.sticker/Astronaut_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Astronaut animated.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Books.sticker/Books_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Books.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/BrainFood.sticker/BrainFood_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/BrainFood.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Butterfly.sticker/Butterfly_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Butterfly.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/CatLaptop.sticker/CatLaptop_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/CatLaptop.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Citation needed animated.sticker/Citation_Needed_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Citation needed animated.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Dragon.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Dragon.sticker/Dragon_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Facts.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Facts.sticker/Facts_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Heart eyes.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Heart eyes.sticker/HeartEyes_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Help lol.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Help lol.sticker/HelpLol_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Idea.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Idea.sticker/idea_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Math meme.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Math meme.sticker/MathMeme_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Newspaper.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Newspaper.sticker/Newspaper_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Note taking.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Note taking.sticker/Note_Taking_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/RabbitHole.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/RabbitHole.sticker/RabbitHole_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Science.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Science.sticker/Science_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Tea dark skin tone.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Tea dark skin tone.sticker/Tea1_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Tea light skin tone.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Tea light skin tone.sticker/Tea2_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Teamwork.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Teamwork.sticker/Teamwork_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Thug.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Thug.sticker/Thug_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/What.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/What.sticker/What_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Wordmark.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Wordmark.sticker/wordmark_2.gif
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/World.sticker/Contents.json
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/World.sticker/World_2.gif
Labels: Low Impact

#3139 Utilize cached article responses when restoring navigation stack
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/WMFArticleFetcher.h
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticleViewController.h
  Wikipedia/Code/WMFArticleViewController.m
Labels: Changes welcome, Low Impact

#3133 talk page - show local data if fetch fails
  Wikipedia/Code/TalkPageContainerViewController.swift
Labels: Changes welcome

#3140 Fix splash view
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFThemeableNavigationController.h
  Wikipedia/Code/WMFThemeableNavigationController.m
Labels: Changes welcome, Low Impact

#3142 Apply theme when restoring nav stack
  Wikipedia/Code/NavigationStateController.swift
Labels: Changes welcome, Low Impact

#3143 Fix scroll view offset in Reply list view after publishing a reply
  Wikipedia/Code/TalkPageReplyListViewController.swift
Labels: Changes welcome, Low Impact

#3144 Use talk-pages-2
  WMF Framework/Configuration.swift
  WikipediaUnitTests/Code/TalkPageControllerTests.swift
  WikipediaUnitTests/Code/TalkPageFetcherTests.swift
Labels: Changes welcome, Low Impact

#3146 Fix explore preferences settings
  WMF Framework/WMFExploreFeedContentController.h
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/FeedCardSettingsViewController.swift
  Wikipedia/Code/WMFContentGroupKind+FeedCustomization.swift
Labels: Changes welcome

#3147 App restored to unusable state when exiting from Settings > Languages
  Wikipedia/Code/NavigationStateController.swift
Labels: Low Impact

#3151 Various long translation strings issues
  Wikipedia/Code/ArticlePopoverViewController.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/SaveButton.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/WMFSettingsTableViewCell.xib
  Wikipedia/Code/WMFTableHeaderFooterLabelView.xib
Labels: Changes welcome, Low Impact

#3150 Talk Pages Design QA fixes
  WMF Framework/NavigationBar.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/BeKindInputAccessoryView.swift
  Wikipedia/Code/BeKindInputAccessoryView.xib
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/InfoBannerView.swift
  Wikipedia/Code/LinkOnlyTextView.swift
  Wikipedia/Code/NavigationBarHider.swift
  Wikipedia/Code/SearchResultsViewController.swift
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageHeaderView.swift
  Wikipedia/Code/TalkPageHeaderView.xib
  Wikipedia/Code/TalkPageReplyListViewController.swift
  Wikipedia/Code/TalkPageTopicNewViewController.swift
  Wikipedia/Code/TalkPageTopicNewViewController.xib
Labels: Changes welcome, Low Impact

#3152 Show new stickers first
  Wikipedia Stickers/Stickers.xcassets/Sticker Pack.stickerpack/Contents.json
Labels: Low Impact

#3153 Talk Page Topics become hidden after rotation
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageHeaderView.xib
  Wikipedia/Code/TalkPageTopicListViewController.swift
Labels: Changes welcome, Low Impact

#3154 talk page - fix iPad popover crashes
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageHeaderView.swift
  Wikipedia/Code/TalkPageReplyCell.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
  Wikipedia/Code/TalkPageTopicListViewController.swift
  Wikipedia/Code/UITextView+Extensions.swift
Labels: Changes welcome, Low Impact

#3156 Talk page - fix inset bug when returning from state restoration
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/TalkPageTopicListViewController.swift
Labels: Changes welcome, Low Impact

#3155 Fix continue reading layout, ensure URLs are unique
  WMF Framework/WMFContentGroup+Extensions.h
  WMF Framework/WMFContentGroup+Extensions.m
  Wikipedia/Code/WMFContinueReadingContentSource.m
Labels: Changes welcome, Low Impact

#3160 talk page reply - mark fine print as not editable
  Wikipedia/Code/TalkPageReplyComposeView.swift
  Wikipedia/Code/TalkPageTopicNewViewController.swift
  Wikipedia/Code/TalkPagesController.swift
Labels: Changes welcome, Hold, Low Impact

#3161 Fetcher - pass along correct error object from result + tests
  WMF Framework/Fetcher.swift
  WikipediaUnitTests/Code/ArticleFetcherTests.m
  WikipediaUnitTests/Fixtures/missing-title.json
Labels: Changes welcome

#3162 saved articles sync - pass original articleURL to didFetchArticle for task removal
  Wikipedia/Code/SavedArticlesFetcher.m
Labels: Changes welcome
