Repository wikimedia/wikipedia-ios, pull requests merged in 2019-01, with the labels that each got.

#2816 Update LICENSE.txt
  LICENSE.txt
Labels: Low impact

#2818 Edit messaging refactor
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ContextualHighlightEditToolbarView.swift
  Wikipedia/Code/ContextualHighlightEditToolbarView.xib
  Wikipedia/Code/DefaultEditToolbarView.swift
  Wikipedia/Code/DefaultEditToolbarView.xib
  Wikipedia/Code/EditToolbarView.swift
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebView.swift
  Wikipedia/Code/SectionEditorWebViewConfiguration.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/Code/SectionEditorWebViewWithEditToolbar.swift
  Wikipedia/Code/TextFontFormattingTableViewController.swift
  Wikipedia/Code/TextFormattingGroupedToolbarView.swift
  Wikipedia/Code/TextFormattingGroupedToolbarView.xib
  Wikipedia/Code/TextFormattingInputViewController.swift
  Wikipedia/Code/TextFormattingPlainToolbarView.swift
  Wikipedia/Code/TextFormattingPlainToolbarView.xib
  Wikipedia/Code/TextFormattingProviding.swift
  Wikipedia/Code/TextFormattingProvidingTableViewController.swift
  Wikipedia/Code/TextFormattingTableViewController.swift
  Wikipedia/Code/TextFormattingToolbarView.swift
  Wikipedia/Code/TextSizeFormattingTableViewController.swift
  Wikipedia/Code/TextStyleFormattingTableViewController.swift
  Wikipedia/Code/WKWebViewWithSettableInputViews.swift
  Wikipedia/assets/mediawiki-extensions-CodeMirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: Changes welcome

#2822 Fix wikidata description language mapping, re-enable enwiki editing
  WMF Framework/Configuration.swift
  WMF Framework/Fetcher.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/PlaceSearchService.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
  Wikipedia/Code/WikidataFetcher.swift
Labels: 6.2, Changes welcome

#2825 Disable ellipsis on the main toolbar
  Wikipedia/Code/DefaultEditToolbarView.xib
Labels: Low impact

#2826 Apply theme to editing input views
  WMF Framework/Theme.swift
  Wikipedia/Code/EditToolbarView.swift
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebView.swift
  Wikipedia/Code/TextFormattingButton.swift
  Wikipedia/Code/TextFormattingDetailTableViewCell.swift
  Wikipedia/Code/TextFormattingGroupedToolbarView.swift
  Wikipedia/Code/TextFormattingGroupedToolbarView.xib
  Wikipedia/Code/TextFormattingInputViewController.swift
  Wikipedia/Code/TextFormattingProvidingTableViewController.swift
  Wikipedia/Code/TextFormattingTableViewCell.swift
  Wikipedia/Code/TextFormattingTableViewController.swift
  Wikipedia/Code/TextFormattingToolbarView.swift
  Wikipedia/Code/TextSizeFormattingTableViewController.swift
  Wikipedia/Code/TextStyleFormattingTableViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2, Changes welcome

#2830 Update edit input view theme colors
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/EditToolbarView.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/TextFormattingButton.swift
  Wikipedia/Code/TextFormattingInputViewController.swift
  Wikipedia/Code/TextFormattingProvidingTableViewController.swift
  Wikipedia/Code/TextFormattingTableViewCell.swift
  Wikipedia/Code/TextFormattingToolbarView.swift
Labels: 6.2, Low impact

#2831 Fix keyboard dismissal in section editor
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2, Low impact

#2832 Fix constraint errors, use intrinsic content size for separators
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ContextualHighlightEditToolbarView.xib
  Wikipedia/Code/DefaultEditToolbarView.xib
  Wikipedia/Code/TextFormattingButton.swift
  Wikipedia/Code/TextFormattingGroupedToolbarView.xib
  Wikipedia/Code/TextFormattingPlainToolbarView.xib
  Wikipedia/Code/ToolbarSeparatorView.swift
Labels: 6.2, Changes welcome, Low impact

#2833 Remove non-functioning buttons
  Wikipedia/Code/ContextualHighlightEditToolbarView.xib
  Wikipedia/Code/DefaultEditToolbarView.xib
  Wikipedia/Code/TextFormattingTableViewController.swift
  Wikipedia/Images.xcassets/directionDown.imageset/Contents.json
  Wikipedia/Images.xcassets/directionLeft.imageset/Contents.json
  Wikipedia/Images.xcassets/directionRight.imageset/Contents.json
  Wikipedia/Images.xcassets/directionUp.imageset/Contents.json
  Wikipedia/Images.xcassets/dots.imageset/Contents.json
  fastlane/metadata/pt-br/description.txt
  fastlane/metadata/pt-br/keywords.txt
  fastlane/metadata/pt-br/name.txt
  fastlane/metadata/pt-br/subtitle.txt
Labels: 6.2

#2834 Update pink color
  Wikipedia/assets/codemirror/codemirror-black.css
  Wikipedia/assets/codemirror/codemirror-dark.css
  Wikipedia/assets/codemirror/codemirror-sepia.css
  www/codemirror/codemirror-black.css
  www/codemirror/codemirror-dark.css
  www/codemirror/codemirror-sepia.css
Labels: 6.2, Low impact

#2836 Don't reload article on edit cancel
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2, Low impact

#2837 Update fastlane
  Gemfile.lock
Labels: 6.2, Low impact

#2838 fix nav button flicker when using cursor buttons
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2, Low impact

#2764 Use new pagelib article title/descrip method.
  Makefile
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.js
  Wikipedia/assets/styleoverrides.css
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/js/sections.js
  www/less/misc.less
  www/less/titleDescriptions.less
  www/package-lock.json
  www/package.json
Labels: 6.2

#2843 Update search placeholder text
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2, Low impact

#2844 Re-show keyboard after other input view is interactively dismissed
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/TextFormattingProviding.swift
Labels: 6.2, Low impact

#2842 Scroll cursor onscreen if needed on text entry, arrow key use or rotation.
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2, Low impact

#2847 Fix ES6 template literals crash
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2, Low impact

#2848 Keep input accessory view at bottom of screen when keyboard dismissed
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2, Changes welcome, Low impact

#2845 Fix keyboard observations not being removed
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/SearchLanguagesBarViewController.swift
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFScrollViewController.swift
  Wikipedia/Code/WMFScrollable.swift
Labels: 6.2

#2852 Update section editor theme colors to match mockups
  WMF Framework/Theme.swift
  Wikipedia/Code/DefaultEditToolbarView.swift
  Wikipedia/Code/EditToolbarView.swift
  Wikipedia/Code/SectionEditorNavigationItemController.swift
  Wikipedia/Code/TextFormattingButton.swift
  Wikipedia/Code/TextFormattingInputViewController.swift
  Wikipedia/Code/TextFormattingProvidingTableViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFThemeableNavigationController.h
  Wikipedia/Code/WMFThemeableNavigationController.m
Labels: 6.2, Low impact

#2841 Fix handling of redirects to title and fragment
  Wikipedia/Code/SavedArticlesFetcher.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFBlockDefinitions.h
  WikipediaUnitTests/Code/ArticleFetcherTests.m
Labels: 6.2

#2856 After editing, hide the out of date article while the updated version is loading
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.2, Low impact

#2855 Wait until after display to post 'articleContentLoaded'
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.swift
  Wikipedia/assets/index.js
  www/js/sections.js
Labels: 6.2, Changes welcome

#2857 Pass direction to codemirror config
  Wikipedia/Code/CodemirrorSetupUserScript.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2, Low impact

#2860 Fix typo in README.md
  README.md
  Wikipedia/Code/AboutViewController.plist
Labels: Low impact

#2862 Fix initial refresh control tint
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.2, Low impact

#2863 Smooth scroll hidden cursor back into view.
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2, Low impact

#2864 Fix scrolling cursor into view when scrolled to bottom of wikitext
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2, Low impact

#2865 Update the Dim images settings text to reflect the addition of black mode
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2, Low impact

#2867 Implement eventlogging for Wikidata descriptions editing on iOS app
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/EditFunnel.h
  Wikipedia/Code/EditFunnel.m
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
Labels: 6.2

#2870 Fix places search
  WMF Framework/URLComponents+Extensions.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFLocationSearchFetcher.m
Labels: 6.2, Low impact

#2871 Fix special page loading, fix search for '&', add localized descriptions to fetcher errors
  WMF Framework/Fetcher.swift
  WMF Framework/NSCharacterSet+WMFLinkParsing.m
  WMF Framework/WMFAnnouncementsFetcher.m
  WMF Framework/WMFLegacySerializer.m
  WMF Framework/WMFOnThisDayEventsFetcher.m
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/MWKList.m
  Wikipedia/Code/NSError+WMFExtensions.h
  Wikipedia/Code/NSError+WMFExtensions.m
  Wikipedia/Code/PageHistoryFetcher.swift
  Wikipedia/Code/SavedArticlesFetcher.m
  Wikipedia/Code/Session.swift
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.m
  Wikipedia/Code/UIViewController+WMFOpenExternalUrl.m
  Wikipedia/Code/WMFArticleFetcher.m
  Wikipedia/Code/WMFArticlePreviewFetcher.m
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFFeedContentFetcher.m
  Wikipedia/Code/WMFLocationSearchFetcher.m
  Wikipedia/Code/WMFRandomArticleFetcher.m
  Wikipedia/Code/WMFRelatedSearchFetcher.m
  Wikipedia/Code/WMFSearchFetcher.m
  Wikipedia/Code/WMFURLSchemeHandler.m
  Wikipedia/Code/WikiTextSectionFetcher.m
  Wikipedia/Code/WikiTextSectionUploader.m
  Wikipedia/Code/WikidataFetcher.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2, Low impact

#2872 Fix for offline articles not loading
  Wikipedia/Code/WMFArticleFetcher.m
Labels: 6.2, Low impact

#2869 Update edit submission screen to use current look and feel, Part 2
  WMF Framework/CommonStrings.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AbuseFilterAlert.h
  Wikipedia/Code/AbuseFilterAlert.m
  Wikipedia/Code/AbuseFilterAlertView.swift
  Wikipedia/Code/AbuseFilterAlertView.xib
  Wikipedia/Code/BulletedLabel.h
  Wikipedia/Code/BulletedLabel.m
  Wikipedia/Code/BulletedLabel.xib
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/EditSaveViewController.storyboard
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/EditSummaryViewController.swift
  Wikipedia/Code/EditSummaryViewController.xib
  Wikipedia/Code/MWKLanguageLinkFetcher.h
  Wikipedia/Code/MenuButton.h
  Wikipedia/Code/MenuButton.m
  Wikipedia/Code/MenuLabel.h
  Wikipedia/Code/MenuLabel.m
  Wikipedia/Code/PreviewLicenseView.swift
  Wikipedia/Code/PreviewWebViewContainer.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/TabularScrollView.h
  Wikipedia/Code/TabularScrollView.m
  Wikipedia/Code/UIView+RemoveConstraints.h
  Wikipedia/Code/UIView+RemoveConstraints.m
  Wikipedia/Code/UIViewController+WMFAlerts.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WebViewController_Private.h
  Wikipedia/Code/WikiTextSectionFetcher.h
  Wikipedia/Code/WikiTextSectionFetcher.m
  Wikipedia/Code/WikiTextSectionUploader.h
  Wikipedia/Code/WikiTextSectionUploader.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
  www/package-lock.json
Labels: 6.2

#2873 Update edit submission screen to use current look and feel, Part 3
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/EditSaveViewController.storyboard
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/EditSummaryViewController.xib
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/PreviewLicenseView.swift
  Wikipedia/Code/PreviewLicenseView.xib
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WikiTextSectionUploader.h
  Wikipedia/Code/WikiTextSectionUploader.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2, Low impact
