Repository wikimedia/wikipedia-ios, pull requests merged in 2019-03, with the labels that each got.

#2949 Fix reading list sync
  WMF Framework/ReadingListsAPIController.swift
  Wikipedia/Code/Session.swift
Labels: 6.2.1, Low Impact

#2950 Fix bold and italic markup behavior
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2.1, Changes welcome, Low Impact

#2952 "Add article to reading list" hint appears during sync
  Wikipedia/Code/MWKSavedPageList.m
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.2, Changes welcome, Low Impact

#2953 Wikidata description welcome shown after every edit
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: 6.1.2, Changes welcome, Low Impact

#2955 Workaround for Swift KVO crash
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/SwiftKVOCrashWorkaround.swift
  Wikipedia/Code/main.m
Labels: 6.2.1, Changes welcome

#2954 Percent encode `=` characters in query items
  WMF Framework/NSCharacterSet+WMFLinkParsing.h
  WMF Framework/NSCharacterSet+WMFLinkParsing.m
  WMF Framework/URLComponents+Extensions.swift
  Wikipedia/Code/URL+WMFLinkParsing.swift
Labels: 6.2.1

#2956 Fix reading lists sync token
  WMF Framework/Fetcher.swift
  WMF Framework/ReadingListsAPIController.swift
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: 6.2.1, Changes welcome, Low Impact

#2957 Added IconBarButtonItem for disabled tint control
  WMF Framework/CommonStrings.swift
  WMF Framework/Theme.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DescriptionWelcomePageViewController.swift
  Wikipedia/Code/IconBarButtonItem.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFWelcomePageViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2.1

#2959 Fix oga links
  Wikipedia/Code/NSURL+WMFLinkParsing.m
Labels: 6.2.1, Changes welcome

#2961 use secondary colors for disabledLink for light/sepia
  WMF Framework/Theme.swift
Labels: 6.2.1, Low Impact

#2958 Select text to edit
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/Code/WKWebView+EditSelectionJavascript.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WebViewController.h
  Wikipedia/Code/WebViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/assets/codemirror/codemirror-editTextSelection.js
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.html
  Wikipedia/assets/preview.js
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  www/codemirror/codemirror-editTextSelection.js
  www/codemirror/codemirror-index.html
  www/index-main.js
  www/js/editTextSelection.js
  www/preview.html
Labels: 6.2.1

#2962 Show toolbar elements in the same order in both insertion and selection contexts
  Wikipedia/Code/ContextualHighlightEditToolbarView.swift
  Wikipedia/Code/ContextualHighlightEditToolbarView.xib
  Wikipedia/Code/TextFormattingButton.swift
  Wikipedia/Code/TextFormattingPlainToolbarView.xib
  Wikipedia/Code/TextFormattingTableViewCell.swift
  Wikipedia/Code/TextFormattingTableViewController.swift
  Wikipedia/Code/TextFormattingToolbarView.swift
  Wikipedia/Images.xcassets/round-plus.imageset/Contents.json
  Wikipedia/Images.xcassets/round-plus.imageset/Plus (1).pdf
Labels: 6.2.1, Low Impact

#2963 Cannot sync reading list entries
  WMF Framework/ReadingListsAPIController.swift
Labels: 6.1.2, Low Impact

#2966 Add editing onboarding strings
  WMF Framework/CommonStrings.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2.1, Low Impact

#2967 Add lost strings
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 6.2.1, Low Impact

#2948 Presenting reading themes popover from Editor
  WMF Framework/CommonStrings.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/CodemirrorSetupUserScript.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/ReadingThemesControlsProtocols.swift
  Wikipedia/Code/ReadingThemesControlsViewController.swift
  Wikipedia/Code/ReadingThemesControlsViewController.xib
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorNavigationItemController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/codemirror/codemirror-syntax-highlighting-off.css
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  www/codemirror/codemirror-index.html
  www/codemirror/codemirror-syntax-highlighting-off.css
Labels: 6.2.1

#2968 Consolidate summary handling, reduce dependence on MWKSearchResult
  WMF Framework/RelatedSearchFetcher.swift
  WMF Framework/SummaryExtensions.swift
  Wikipedia/Code/RandomArticleFetcher.swift
  Wikipedia/Code/WMFRelatedPagesContentSource.m
Labels: Changes welcome, Low Impact

#2973 Fix slow syntax highlighting toggle
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2.1, Changes welcome, Low Impact

#2972 Fix appearance settings anchor
  Wikipedia/Code/ReadingThemesControlsProtocols.swift
Labels: 6.2.1, Changes welcome, Low Impact

#2974 Read image orienation from CGImageSource
  Wikipedia/Code/ImageController.swift
Labels: 6.2.1, Changes welcome, Low Impact

#2975 Fix unhelpful password reset error messages
  WMF Framework/CommonStrings.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFForgotPasswordViewController.swift
  Wikipedia/Code/WMFPasswordResetter.swift
Labels: Low Impact

#2969 Editing on boarding: As a new editor, I'd like for there to be an introduction to Wikitext the first time I visit the editor
  WMF Framework/CommonStrings.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DescriptionWelcome.storyboard
  Wikipedia/Code/DescriptionWelcomePanelViewController.swift
  Wikipedia/Code/EditingWelcomeViewController.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/WMFArticleViewController.m
  Wikipedia/Code/WMFWelcomePanelViewController.swift
  Wikipedia/Code/WelcomeAnimationView.swift
  Wikipedia/Code/WelcomeAnimationViewController.swift
  Wikipedia/Code/WelcomeContainerViewController.swift
  Wikipedia/Code/WelcomeContainerViewController.xib
  Wikipedia/Code/WelcomePageViewController.swift
  Wikipedia/Code/WelcomePanelLabelContentViewController.swift
  Wikipedia/Code/WelcomePanelLabelContentViewController.xib
  Wikipedia/Code/WelcomePanelViewController.swift
  Wikipedia/Code/WelcomePanelViewController.xib
  Wikipedia/Code/WelcomeViewController.swift
  Wikipedia/Images.xcassets/editing-welcome-article.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-article.imageset/group9.pdf
  Wikipedia/Images.xcassets/editing-welcome-articles.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-articles.imageset/group2.pdf
  Wikipedia/Images.xcassets/editing-welcome-citation.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-citation.imageset/group7.pdf
  Wikipedia/Images.xcassets/editing-welcome-scale.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-scale.imageset/group4.pdf
Labels: 6.2.1, Changes welcome

#2965 Switch related pages and random to RESTBase endpoints
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/RelatedSearchFetcher.swift
  WMF Framework/SummaryExtensions.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKSearchResult.h
  Wikipedia/Code/MWKSearchResult.m
  Wikipedia/Code/NSDictionary+WMFCommonParams.m
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/RandomArticleFetcher.swift
  Wikipedia/Code/WMFFirstRandomViewController.m
  Wikipedia/Code/WMFLocationSearchFetcher.m
  Wikipedia/Code/WMFRandomArticleFetcher.h
  Wikipedia/Code/WMFRandomArticleFetcher.m
  Wikipedia/Code/WMFRandomArticleViewController.m
  Wikipedia/Code/WMFRandomContentSource.m
  Wikipedia/Code/WMFRelatedPagesContentSource.m
  Wikipedia/Code/WMFRelatedSearchFetcher.h
  Wikipedia/Code/WMFRelatedSearchFetcher.m
  Wikipedia/Code/WMFRelatedSearchResults.h
  Wikipedia/Code/WMFRelatedSearchResults.m
  Wikipedia/Code/WMFSearchFetcher.m
Labels: 6.2.1, Changes welcome

#2976 small tweak to FocusNavigationView background color
  Wikipedia/Code/FocusNavigationView.swift
Labels: 6.2.1, Low Impact

#2979 Update Pagelib to new version and sync with upstream CSS
  Wikipedia/assets/abusefilter.css
  Wikipedia/assets/index.js
  Wikipedia/assets/preview.css
  Wikipedia/assets/preview.js
  Wikipedia/assets/styles.css
  Wikipedia/assets/wikimedia-page-library-transform.css
  Wikipedia/assets/wikimedia-page-library-transform.css.map
  www/package-lock.json
  www/package.json
Labels: 6.2.1, Low Impact

#2980 Find & replace bug fixes
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/codemirror/resources/addon/search/search.js
  www/codemirror/codemirror-index.html
Labels: 6.2.1

#2981 Fix maths syntax corruption
  Wikipedia/Code/NSString+WMFExtras.m
Labels: 6.2.1, Changes welcome

#2983 Switch themes and syntax highlighting using classes
  Wikipedia/assets/codemirror/codemirror-black.css
  Wikipedia/assets/codemirror/codemirror-dark.css
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/codemirror/codemirror-light.css
  Wikipedia/assets/codemirror/codemirror-sepia.css
  Wikipedia/assets/codemirror/codemirror-syntax-highlighting-off.css
  www/codemirror/codemirror-black.css
  www/codemirror/codemirror-dark.css
  www/codemirror/codemirror-index.html
  www/codemirror/codemirror-light.css
  www/codemirror/codemirror-sepia.css
  www/codemirror/codemirror-syntax-highlighting-off.css
Labels: 6.2.1, Low Impact

#2978 Wikitext scrolled out of view when exiting out of Find in page
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2.1, Changes welcome, Low Impact

#2984 Don't dismiss WMFForgotPasswordViewController when password reset succeeds
  Wikipedia/Code/WMFForgotPasswordViewController.swift
  Wikipedia/Third Party Code/RMessage/RMessageView.xib
Labels: 6.2.1, Low Impact

#2985 Update fastlane
  Gemfile.lock
Labels: 6.2.1, Low Impact

#2986 Analyzer fixes
  WMF Framework/WMFArticle+CoreDataClass.m
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFFirstRandomViewController.m
  Wikipedia/Code/WMFRandomArticleViewController.m
  Wikipedia/Code/WMFURLSchemeHandler.m
  Wikipedia/Code/WikiTextSectionFetcher.m
Labels: 6.2.1, Low Impact

#2988 Editing onboarding tweaks
  Wikipedia/Code/WelcomeAnimationView.swift
  Wikipedia/Code/WelcomeContainerViewController.xib
  Wikipedia/Code/WelcomePanelViewController.swift
  Wikipedia/Images.xcassets/editing-welcome-article.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-article.imageset/be bold.pdf
  Wikipedia/Images.xcassets/editing-welcome-article.imageset/group9.pdf
  Wikipedia/Images.xcassets/editing-welcome-articles.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-articles.imageset/article heart.pdf
  Wikipedia/Images.xcassets/editing-welcome-articles.imageset/group2.pdf
  Wikipedia/Images.xcassets/editing-welcome-citation.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-citation.imageset/group7.pdf
  Wikipedia/Images.xcassets/editing-welcome-citation.imageset/verifiable.pdf
  Wikipedia/Images.xcassets/editing-welcome-scale.imageset/Contents.json
  Wikipedia/Images.xcassets/editing-welcome-scale.imageset/group4.pdf
  Wikipedia/Images.xcassets/editing-welcome-scale.imageset/npov.pdf
Labels: 6.2.1, Low Impact

#2989 Find & Replace - undo to the end of history clears out all text
  Wikipedia/assets/codemirror/codemirror-index.html
  www/codemirror/codemirror-index.html
Labels: 6.2.1, Changes welcome, Low Impact

#2982 Fix WebKit exception crash
  Wikipedia/Code/WMFURLSchemeHandler.m
Labels: 6.2.1

#2991 Find & Replace match scrolled out of view after tapping the ellipsis to choose the replace method
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
Labels: 6.2.1, Low Impact

#2992 small tweaks to syntax highlighting label
  Wikipedia/Code/ReadingThemesControlsViewController.swift
  Wikipedia/Code/ReadingThemesControlsViewController.xib
Labels: 6.2.1, Low Impact

#2993 Fix edit replace undo not scrolling to undone text
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/codemirror/resources/addon/search/search.js
  www/codemirror/codemirror-index.html
Labels: 6.2.1, Low Impact

#2995 [BUG] Incorrect toolbar is shown after going into a submenu
  Wikipedia/Code/SectionEditorInputViewsController.swift
Labels: 6.2.1, Low Impact

#2996 Keep replaceSwitchButton enabled from the start
  Wikipedia/Code/FindAndReplaceKeyboardBar.swift
Labels: 6.2.1, Low Impact

#2998 Replace non breaking spaces with normal spaces in edited wikitext
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
Labels: 6.2.1, Changes welcome, Low Impact

#2999 Select to edit follow-ups
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/WebViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/assets/codemirror/codemirror-editTextSelection.js
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  www/codemirror/codemirror-editTextSelection.js
Labels: 6.2.1

#3000 Fix warning caused by wikitext type change
  Wikipedia/Code/SectionEditorViewController.swift
Labels: 6.2.1, Low Impact

#2964 Clear markup button
  Wikipedia/Code/ContextualHighlightEditToolbarView.swift
  Wikipedia/Code/ContextualHighlightEditToolbarView.xib
  Wikipedia/Code/NSString+WMFExtras.m
  Wikipedia/Code/SectionEditorButton.swift
  Wikipedia/Code/SectionEditorInputViewsController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/Code/TextFormattingProviding.swift
  Wikipedia/Images.xcassets/text-formatting-clear-formatting.imageset/Contents.json
  Wikipedia/Images.xcassets/text-formatting-clear-formatting.imageset/text-formatting-clear-markup.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/assets/codemirror/codemirror-bundle.js
  Wikipedia/assets/codemirror/codemirror-index.html
  Wikipedia/assets/codemirror/codemirror-range-determination-bundle.js
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  www/Gruntfile.js
  www/codemirror/codemirror-index.html
  www/codemirror/codemirror-range-clear-formatting.js
  www/codemirror/codemirror-range-debugging.js
  www/codemirror/codemirror-range-determination-non-tag.js
  www/codemirror/codemirror-range-determination-tag.js
  www/codemirror/codemirror-range-determination.js
  www/codemirror/codemirror-range-main.js
  www/codemirror/codemirror-range-objects.js
  www/codemirror/codemirror-range-set-utilities.js
  www/codemirror/codemirror-range-utilities.js
Labels: 6.2.1

#3004 Update strings after merge
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
Labels: Low Impact

#3003 Box briefly appears around recent search cell text if text itself is tapped
  Wikipedia/Code/SearchViewController.swift
Labels: Low Impact

#3010 Fix leaking NSFetchedResultsController in Places
  Wikipedia/Code/PlacesViewController.swift
Labels: Changes welcome

#3009 find & replace - bug fixes
  Wikipedia/Code/FindAndReplaceKeyboardBar.swift
  Wikipedia/assets/codemirror/resources/addon/search/search.js
Labels: Changes welcome
