Repository wikimedia/wikipedia-ios, pull requests merged in 2020-04, with the labels that each got.

#3510 add 2nd missing completion handler check
  Wikipedia/Code/ArticleViewController+LinkPreviewing.swift
Labels: Changes welcome, Low Impact

#3511 Fix missing footer on pages with apostrophes in the title
  Wikipedia/Code/ActionHandlerScript.swift
Labels: Changes welcome, Low Impact

#3512 Reload the page when the web content process terminates
  Wikipedia/Code/ArticleViewController.swift
Labels: Changes welcome, Low Impact

#3514 Fix animated images in the gallery view
  Wikipedia/Code/MediaListGalleryViewController.swift
Labels: Changes welcome, Low Impact

#3513 Fix initial flash of content when restoring state
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFFirstRandomViewController.m
Labels: Changes welcome, Low Impact

#3507 Clean up headers being sent to the Page Content Service
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/CacheFetching.swift
  WMF Framework/Fetcher.swift
  WMF Framework/ImageCacheController.swift
  WMF Framework/ImageCacheDBWriter.swift
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleFetcher.swift
Labels: Changes welcome

#3516 Remove obsolete references in Xcode project
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Resources/LibrariesUsed.plist
Labels: Changes welcome, Low Impact

#3517 Persist article settings on refresh
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
Labels: Changes welcome, Low Impact

#3519 Fix inconsistent `UISwitch` state when Explore feed preferences are updated
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
Labels: Low Impact

#3520 Remove unused `download` file.
  download
Labels: Low Impact

#3522 Remove mimeType logic
  WMF Framework/ArticleCacheController.swift
  WMF Framework/CacheFetching.swift
  WMF Framework/CacheFileWriter.swift
  WMF Framework/CacheFileWriterHelper.swift
  WMF Framework/FileManager+CacheExtensions.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  Wikipedia/Code/MWKDataStore+LegacyMobileview.swift
  Wikipedia/Code/Session.swift
Labels: Changes welcome, Low Impact

#3523 Make sure fallback response runs on cacheBackgroundContext
  WMF Framework/PermanentlyPersistableURLCache.swift
Labels: Changes welcome, Low Impact

#3524 Update twn and bundle_update scripts to use master instead of develop
  scripts/bundle_update
  scripts/twn.rb
Labels: Changes welcome, Low Impact

#3521 Run response header save on background thread
  WMF Framework/CacheController.swift
  WMF Framework/CacheItemMigrationPolicy.swift
  WMF Framework/ImageCacheController.swift
  Wikipedia/Code/MWKDataStore.m
Labels: Changes welcome, Low Impact

#3526 Fix "Explore feed" settings page's multiple languages regression
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
Labels: Changes welcome

#3528 Per discussion, change back to alert.
  Wikipedia/Code/ArticleViewController+Editing.swift
Labels: Changes welcome, Low Impact

#3527 Change order of VoiceOver reading in edit mode
  WMF Framework/CollectionViewEditController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppTabBarDelegate.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: Changes welcome, Low Impact

#3531 Restore ability to edit title descriptions
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/SummaryExtensions.swift
  Wikipedia/Code/ArticleViewController+Editing.swift
  Wikipedia/Code/DescriptionEditViewController.swift
Labels: Changes welcome, Low Impact

#3532 Fix failing Alpha and Beta build targets.
  Wikipedia.xcodeproj/project.pbxproj
Labels: Low Impact

#3518 Display native survey prompt
  WMF Framework/AnnouncementType.swift
  WMF Framework/String+LinkParsing.swift
  WMF Framework/SurveyAnnouncementsController.swift
  WMF Framework/WMF.h
  WMF Framework/WMFAnnouncement.h
  WMF Framework/WMFAnnouncement.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleViewController+Announcements.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+SurveyAnnouncements.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/ScrollableEducationPanelView.xib
  Wikipedia/Code/ScrollableEducationPanelViewController.swift
  Wikipedia/Code/StorageAndSyncingSettingsViewController.swift
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFAppViewController.m
Labels: Changes welcome

#3534 Only recognize iOS announcements version 3
  WMF Framework/WMFAnnouncementsFetcher.m
Labels: Changes welcome, Low Impact

#3535 Create fastlane lane for deploy
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: Changes welcome, Low Impact

#3538 Fix CI issues, rename builds to match new conventions, update documentation
  README.md
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Beta (mobileapps.wmflabs.org pcs).xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Experimental.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Local Page Content Service & Announcements.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/MediaWiki Beta Cluster.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/RTL.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Staging.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/UITests.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/User Testing.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Wikipedia Stickers.xcscheme
  Wikipedia/Experimental-Info.plist
  Wikipedia/Local-Info.plist
  Wikipedia/Staging-Info.plist
  Wikipedia/User Testing-Info.plist
  Wikipedia/Wikipedia OSM-Info.plist
  docs/ci.md
  fastlane/Fastfile
  fastlane/README.md
Labels: Changes welcome, Low Impact

#3539 Fix share from gallery
  Wikipedia/Code/WMFImageGalleryViewController.m
Labels: Changes welcome, Low Impact

#3536 Address visual issues with article pull to refresh
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleToolbarController.swift
  Wikipedia/Code/ArticleViewController.swift
Labels: Low Impact

#3540 Fix floating hint issues
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/HintController.swift
Labels: Changes welcome, Low Impact

#3543 Allow pronunciation audio playback when ring/silent switch is engaged
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleViewController+Media.swift
Labels: Low Impact

#3545 Improve offline experience when refreshing articles
  Wikipedia/Code/ArticleViewController.swift
Labels: Low Impact

#3537 Show loading animation if library migration takes too long
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/HintController.swift
  Wikipedia/Code/InsertLinkViewController.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/LoadingAnimationViewController.swift
  Wikipedia/Code/LoadingAnimationViewController.xib
  Wikipedia/Code/PageHistoryCountsViewController.swift
  Wikipedia/Code/ReadingListDetailViewController.swift
  Wikipedia/Code/RootNavigationController.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/SplashScreenViewController.swift
  Wikipedia/Code/UIViewController+WMFChildViewController.swift
  Wikipedia/Code/WMFAccountCreationViewController.swift
  Wikipedia/Code/WMFAppViewController.h
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFThemeableNavigationController.h
  Wikipedia/Code/WMFThemeableNavigationController.m
  Wikipedia/Images.xcassets/loading/Contents.json
  Wikipedia/Images.xcassets/loading/bg.imageset/Contents.json
  Wikipedia/Images.xcassets/loading/bg.imageset/group6.png
  Wikipedia/Images.xcassets/loading/bg.imageset/group6@2x.png
  Wikipedia/Images.xcassets/loading/bg.imageset/group6@3x.png
  Wikipedia/Images.xcassets/loading/earth.imageset/Contents.json
  Wikipedia/Images.xcassets/loading/earth.imageset/group5.png
  Wikipedia/Images.xcassets/loading/earth.imageset/group5@2x.png
  Wikipedia/Images.xcassets/loading/earth.imageset/group5@3x.png
  Wikipedia/Images.xcassets/loading/satellite.imageset/Contents.json
  Wikipedia/Images.xcassets/loading/satellite.imageset/Group 4.png
  Wikipedia/Images.xcassets/loading/satellite.imageset/Group 4@2x.png
  Wikipedia/Images.xcassets/loading/satellite.imageset/Group 4@3x.png
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome

#3542 remove some unnecessary DEBUG checks
  TopReadWidget/WMFTodayTopReadWidgetViewController.swift
  WMF Framework/SurveyAnnouncementsController.swift
  Wikipedia/Code/Session.swift
Labels: Changes welcome, Low Impact

#3548 Stop background task when no more articles exist
  Wikipedia/Code/SavedArticlesFetcher.swift
Labels: Changes welcome, Low Impact

#3550 Improve VoiceOver for Table of Contents
  Wikipedia/Code/TableOfContentsCell.swift
  Wikipedia/Code/TableOfContentsViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
Labels: Changes welcome, Low Impact

#3544 Make compatibility adjustments to link URLs from mobile-html
  WMF Framework/Configuration.swift
  WMF Framework/Router.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+Media.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/NSURL+WMFLinkParsing.h
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/URL+LinkParsing.swift
  Wikipedia/Code/ViewControllerRouter.swift
  WikipediaUnitTests/Code/URLParsingAndRoutingTests.swift
Labels: Changes welcome

#3546 Allow edit preview to reflect local PCS changes
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/Session.swift
  grep
Labels: Changes welcome, Low Impact
