Repository wikimedia/wikipedia-ios, pull requests merged in 2020-03, with the labels that each got.

#3454 Restore article context menu previewing and 3d touch
  WMF Framework/CommonStrings.swift
  WMF Framework/Router.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/ArticleViewController+Analytics.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+ContextMenu.swift
  Wikipedia/Code/ArticleViewController+LinkPreviewing.swift
  Wikipedia/Code/ArticleViewController+Media.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/URL+LinkParsing.swift
  Wikipedia/Code/ViewControllerRouter.swift
  Wikipedia/Code/Wikipedia-Bridging-Header.h
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/assets/index.js
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  www/js/editTextSelection.js
  www/js/utilities.js
Labels: Changes welcome

#3457 Use old Cache database, migrate bundled resources
  WMF Framework/ArticleCacheController.swift
  WMF Framework/ArticleCacheHeaderProvider.swift
  WMF Framework/ArticleURLConverter.swift
  WMF Framework/Cache.xcdatamodeld/.xccurrentversion
  WMF Framework/Cache.xcdatamodeld/Cache 2.xcdatamodel/contents
  WMF Framework/CacheController.swift
  WMF Framework/CacheControllerWrapper.swift
  WMF Framework/CacheDBWriterHelper.swift
  WMF Framework/CacheDBWriting.swift
  WMF Framework/CacheFetching.swift
  WMF Framework/CacheFileWriter.swift
  WMF Framework/CacheFileWriterHelper.swift
  WMF Framework/CacheGroup+CoreDataClass.swift
  WMF Framework/CacheGroup+CoreDataProperties.swift
  WMF Framework/CacheHeaderProviding.swift
  WMF Framework/CacheItem+CoreDataClass.swift
  WMF Framework/CacheItem+CoreDataProperties.swift
  WMF Framework/CacheItemMappingModel.xcmappingmodel/xcmapping.xml
  WMF Framework/CacheItemMigrationPolicy.swift
  WMF Framework/CacheProviderHelper.swift
  WMF Framework/ImageCacheController.swift
  WMF Framework/ImageCacheDBWriter.swift
  WMF Framework/ImageInfoCacheHeaderProvider.swift
  WMF Framework/PersistentCacheGroup+CoreDataClass.swift
  WMF Framework/PersistentCacheGroup+CoreDataProperties.swift
  WMF Framework/PersistentCacheItem+CoreDataClass.swift
  WMF Framework/PersistentCacheItem+CoreDataProperties.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ImageController.swift
  Wikipedia/Code/LegacyArticle.swift
  Wikipedia/Code/MWKDataStore+LegacyMobileview.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MediaListGalleryViewController.swift
  Wikipedia/Code/MobileviewToMobileHTMLConverter.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/SavedArticlesFetcher.swift
  Wikipedia/Code/SavedPageSpotlightManager.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/ShareViewController.swift
  Wikipedia/Code/UIImageView+WMFImageFetching.h
  Wikipedia/Code/UIImageView+WMFImageFetching.m
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.h
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.m
  Wikipedia/Code/WMFImageGalleryViewController.m
  Wikipedia/Code/WMFNotificationsController.m
  Wikipedia/assets/pcs-html-converter/baseCSS.css
  Wikipedia/assets/pcs-html-converter/build/PCSHTMLConverter.js
  Wikipedia/assets/pcs-html-converter/build/Polyfill.js
  Wikipedia/assets/pcs-html-converter/pcsCSS.css
  Wikipedia/assets/pcs-html-converter/pcsJS.js
Labels: Changes welcome

#3460 Add header to reference presentation
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+References.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/ReferenceBackLinksViewController.swift
  Wikipedia/Code/ReferenceViewController.swift
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.h
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.m
  Wikipedia/Code/WMFReferencePageViewController.swift
Labels: Changes welcome

#3462 Updates for PCS localization
  WMF Framework/CommonStrings.swift
  Wikipedia.xcodeproj/xcshareddata/xcschemes/localization.xcscheme
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  localization/main.swift
  scripts/localization.swift
Labels: Changes welcome

#3461 mobile-html: Migrate article if load fails and migration is required
  Wikipedia/Code/ArticleViewController.swift
Labels: Changes welcome

#3464 Update migration assets
  WMF Framework/CacheFileWriter.swift
  WMF Framework/CacheFileWriterHelper.swift
  WMF Framework/CacheItemMigrationPolicy.swift
  WMF Framework/ImageCacheDBWriter.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/MWKLanguageLinkFetcher.m
  Wikipedia/Code/MobileviewToMobileHTMLConverter.swift
  Wikipedia/assets/pcs-html-converter/base.css
  Wikipedia/assets/pcs-html-converter/baseCSS.css
  Wikipedia/assets/pcs-html-converter/build/PCSHTMLConverter.js
  Wikipedia/assets/pcs-html-converter/build/Polyfill.js
  Wikipedia/assets/pcs-html-converter/pcs.css
  Wikipedia/assets/pcs-html-converter/pcs.js
  Wikipedia/assets/pcs-html-converter/pcsCSS.css
  Wikipedia/assets/pcs-html-converter/pcsJS.js
Labels: Changes welcome

#3466 Saved articles fetcher error handling
  WMF Framework/ArticleCacheController.swift
  WMF Framework/ArticleCollectionViewCell+Themeable.swift
  WMF Framework/CommonStrings.swift
  WMF Framework/Fetcher.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  WMF Framework/Remote Notifications/RemoteNotificationsAPIController.swift
  WMF Framework/UIView+SemanticContent.swift
  WMF Framework/WMF.h
  WMF Framework/WMFArticle+CoreDataProperties.h
  WMF Framework/WMFArticle+CoreDataProperties.m
  WMF Framework/WMFArticle+Errors.swift
  WMF Framework/WMFArticle+Extensions.swift
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 3.xcdatamodel/contents
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleCollectionViewCell.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/MWKLanguageLinkFetcher.m
  Wikipedia/Code/MWNetworkActivityIndicatorManager.h
  Wikipedia/Code/MWNetworkActivityIndicatorManager.m
  Wikipedia/Code/NSDictionary+WMFCommonParams.h
  Wikipedia/Code/NSDictionary+WMFCommonParams.m
  Wikipedia/Code/ReadingListEntryCollectionViewController.swift
  Wikipedia/Code/ReadingListsCollectionViewCell.swift
  Wikipedia/Code/RequestError.swift
  Wikipedia/Code/SavedArticlesCollectionViewCell.swift
  Wikipedia/Code/SavedArticlesFetcher.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/ViewController+ArticleErrorHandling.swift
  Wikipedia/Code/WMFArticleRevisionFetcher.m
  Wikipedia/Code/WMFFeedContentFetcher.m
  Wikipedia/Code/WMFLocationSearchFetcher.m
  Wikipedia/Code/WMFNetworkUtilities.h
  Wikipedia/Code/WMFNetworkUtilities.m
  Wikipedia/Code/WMFSearchFetcher.m
  Wikipedia/Code/WikiTextSectionUploader.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  WikipediaUnitTests/Code/MWKLanguageLinkFetcherTests.m
  WikipediaUnitTests/Code/URLParsingAndRoutingTests.swift
  WikipediaUnitTests/Code/WMFJoinedPropertyParametersTests.m
Labels: Changes welcome

#3469 Show empty view on article load error
  Wikipedia/Code/ArticleViewController.swift
Labels: Changes welcome, Low Impact

#3467 T246722 - Cache new resources on saved article load
  WMF Framework/ArticleCacheController.swift
  WMF Framework/ArticleCacheDBWriter+SyncResources.swift
  WMF Framework/ArticleCacheResourceDBWriting.swift
  WMF Framework/CacheController.swift
  WMF Framework/CacheDBWriterHelper.swift
  WMF Framework/CacheDBWriting.swift
  WMF Framework/CacheFetching.swift
  WMF Framework/ImageCacheDBWriter.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFFirstRandomViewController.m
Labels: Changes welcome

#3471 Fix issue where SavedArticlesFetcher would get stuck on a single item
  Wikipedia/Code/SavedArticlesFetcher.swift
Labels: Changes welcome, Low Impact

#3470 Restore Event Logging Dev Debug scheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Event Logging Dev Debug.xcscheme
Labels: Changes welcome, Low Impact

#3478 Language fixes
  WMF Framework/ArticleCacheController.swift
  WMF Framework/ArticleCacheDBWriter+SyncResources.swift
  WMF Framework/ArticleCacheResourceDBWriting.swift
  WMF Framework/CacheController.swift
  WMF Framework/CacheDBWriting.swift
  WMF Framework/CacheFetching.swift
  WMF Framework/CacheFileWriter.swift
  WMF Framework/ImageCacheController.swift
  WMF Framework/ImageCacheDBWriter.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/Session.swift
Labels: Changes welcome

#3474 Set maxage and smaxage on siteinfo requests
  WMF Framework/WikipediaSiteInfo.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/WikidataDescriptionEditingController.swift
Labels: Changes welcome, Low Impact

#3475 Fix console warning for CocoaLumberjack, remove unnecessary directory log
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/DDLog+WMFLogger.m
Labels: Changes welcome, Low Impact

#3476 Verify the etag changed before updating the cache
  WMF Framework/PermanentlyPersistableURLCache.swift
Labels: Changes welcome, Low Impact

#3479 Cache policy fixes
  WMF Framework/CacheFetching.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/Session.swift
Labels: Changes welcome

#3473 Retry failed downloads on pull to refresh in reading list views
  WMF Framework/WMFArticle+Errors.swift
  Wikipedia/Code/ReadingListEntryCollectionViewController.swift
Labels: Changes welcome

#3484 Stop the SavedArticlesFetcher when offline
  WMF Framework/ArticleCacheController.swift
  WMF Framework/CacheController.swift
  Wikipedia/Code/SavedArticlesFetcher.swift
Labels: Changes welcome, Low Impact

#3482 Fix scroll to anchor for collapsed sections
  WMF Framework/CacheFetching.swift
  WMF Framework/CacheFileWriter.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/Session.swift
Labels: Changes welcome, Low Impact

#3485 Added history and diff screen event logging
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleViewController+ArticleInformation.swift
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/EditHistoryCompareFunnel.swift
  Wikipedia/Code/PageHistoryViewController.swift
Labels: Changes welcome

#3491 Switch to prod for beta builds
  fastlane/Fastfile
Labels: Low Impact

#3489 Re-implement article announcement functionality
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleViewController+Announcements.swift
  Wikipedia/Code/ArticleViewController.swift
Labels: Changes welcome

#3490 Ensure article announcements are removed from the database
  WMF Framework/ArticleURLConverter.swift
  WMF Framework/Configuration.swift
  WMF Framework/Fetcher.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  WMF Framework/ReadingListsAPIController.swift
  WMF Framework/RelatedSearchFetcher.swift
  WMF Framework/WMFAnnouncementsFetcher.m
  WMF Framework/WMFOnThisDayEventsFetcher.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Beta (apps.wmflabs.org pcs).xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Wikipedia (apps.wmflabs.org pcs).xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Wikipedia (local pcs & announcements).xcscheme
  Wikipedia/Code/APIURLComponentsBuilder.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/PageHistoryFetcher.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/RandomArticleFetcher.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/TalkPageFetcher.swift
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFFeedContentFetcher.m
Labels: Changes welcome

#3494 Update beta app config
  fastlane/Fastfile
Labels: Changes welcome, Low Impact

#3495 remove ArticleURLConverter
  WMF Framework/ArticleURLConverter.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/EditPreviewViewController.swift
Labels: Changes welcome, Low Impact

#3496 Remove default-data-protection entitlement and unused user defaults
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Wikipedia.entitlements
Labels: Changes welcome, Low Impact

#3497 Comment out legacy article data deletion after conversion
  Wikipedia/Code/MWKDataStore+LegacyMobileview.swift
  Wikipedia/Code/SavedArticlesFetcher.swift
Labels: Changes welcome, Low Impact

#3499 Fix console errors for event logging dev debug scheme
  WMF Framework/EventLoggingService.swift
Labels: Changes welcome, Low Impact

#3500 Pass version instead of clientVersion to PCS
  Wikipedia/Code/ActionHandlerScript.swift
Labels: Hold

#3502 Debug helper: Perform full refresh on pull-to-refresh for debug builds
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController.swift
Labels: Changes welcome

#3503 add missing completion handler check to prevent double calls
  Wikipedia/Code/ArticleViewController+LinkPreviewing.swift
Labels: Changes welcome, Low Impact

#3501 Add debug ability to randomly save articles across wiki languages
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia/Code/DebugReadingListsViewController.swift
  Wikipedia/Code/DebugReadingListsViewController.xib
  Wikipedia/Code/ReadingListsController.swift
Labels: Changes welcome, Low Impact

#3505 Fix bottom "view in browser" link, and remove unneeded license code
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
Labels: Changes welcome, Low Impact
