Repository wikimedia/wikipedia-ios, pull requests merged in 2020-01, with the labels that each got.

#3398 Update fastlane to fix security warning on excon gem
  Gemfile.lock
Labels: Low Impact

#3397 Fix duplicate sections in page history
  Wikipedia/Code/NSDateFormatter+WMFExtensions.m
  Wikipedia/Code/PageHistoryFetcher.swift
  Wikipedia/Code/PageHistoryViewController.swift
  Wikipedia/Code/WMFPageHistoryRevision.m
Labels: Changes welcome

#3400 Add language code fallback for section editor
  Wikipedia/Code/SectionEditorViewController.swift
Labels: Changes welcome

#3401 Use allowed character set for title path components to ensure / characters in titles are encoded
  Wikipedia/Code/PageHistoryFetcher.swift
Labels: Changes welcome

#3404 Re-organize and add more documentation to WMFArticle.h
  WMF Framework/WMFArticle+CoreDataProperties.h
Labels: Changes welcome, Low Impact

#3408 Minor fixes for SavedArticlesFetcher.swift
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/SavedArticlesFetcher.swift
Labels: Changes welcome, Low Impact

#3411 Rework random and help VCs to work with the new Article view
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCollectionViewController.swift
  Wikipedia/Code/ArticleLocationCollectionViewController.swift
  Wikipedia/Code/ArticlePreviewingDelegate.swift
  Wikipedia/Code/ArticleToolbarController.swift
  Wikipedia/Code/ArticleURLListViewController.swift
  Wikipedia/Code/ArticleViewController+WIconPopover.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HelpViewController.swift
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/NewsViewController.swift
  Wikipedia/Code/OnThisDayViewController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/RandomArticleFetcher.swift
  Wikipedia/Code/RandomArticleViewController.swift
  Wikipedia/Code/ReadingListEntryCollectionViewController.swift
  Wikipedia/Code/ViewController+ArticlePreviewing.swift
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFAppViewController.h
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFContentGroup+DetailViewControllers.swift
  Wikipedia/Code/WMFFirstRandomViewController.m
  Wikipedia/Code/WMFHelpViewController.h
  Wikipedia/Code/WMFHelpViewController.m
  Wikipedia/Code/WMFRandomArticleViewController.h
  Wikipedia/Code/WMFRandomArticleViewController.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
Labels: Changes welcome

#3417 mobile-html - etag functionality
  WMF Framework/CacheController.swift
  WMF Framework/CacheControllerWrapper.swift
  WMF Framework/CacheDBWriting.swift
  WMF Framework/CacheFileWriting.swift
  WMF Framework/CacheProviderHelper.swift
  WMF Framework/CacheProviding.swift
  WMF Framework/ImageCacheFileWriter.swift
  WMF Framework/ImageCacheProvider.swift
  WMF Framework/ImageFetcher.swift
  WMF Framework/PersistentCache.xcdatamodeld/NewCache.xcdatamodel/contents
  WMF Framework/PersistentCacheItem+CoreDataProperties.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCacheFileWriter.swift
  Wikipedia/Code/ArticleCacheProvider.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/SchemeHandler/RemoteSubHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler+DefaultHandler.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFFirstRandomViewController.m
Labels: Changes welcome
