Repository wikimedia/wikipedia-ios, pull requests merged in 2020-05, with the labels that each got.

#3553 Remove empty `grep` file.
  grep
Labels: Low Impact

#3556 Remove legacy image tag parsing
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/WMFImageTag+TargetImageWidthURL.h
  Wikipedia/Code/WMFImageTag+TargetImageWidthURL.m
  Wikipedia/Code/WMFImageTag.h
  Wikipedia/Code/WMFImageTag.m
  Wikipedia/Code/WMFImageTagList+ImageURLs.h
  Wikipedia/Code/WMFImageTagList+ImageURLs.m
  Wikipedia/Code/WMFImageTagList.h
  Wikipedia/Code/WMFImageTagList.m
  Wikipedia/Code/WMFImageTagParser.h
  Wikipedia/Code/WMFImageTagParser.m
Labels: Changes welcome, Low Impact

#3555 Update PCS conversion assets, ensure legacy user data is removed
  Wikipedia/Code/MWKDataStore+LegacyMobileview.swift
  Wikipedia/Code/SavedArticlesFetcher.swift
  Wikipedia/assets/pcs-html-converter/base.css
  Wikipedia/assets/pcs-html-converter/build/PCSHTMLConverter.js
  Wikipedia/assets/pcs-html-converter/build/Polyfill.js
  Wikipedia/assets/pcs-html-converter/pcs.css
  Wikipedia/assets/pcs-html-converter/pcs.js
Labels: Changes welcome

#3549 Added some article performance and caching tests
  WMF Framework/CacheController.swift
  WMF Framework/PermanentlyPersistableURLCache.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/MediaWiki Beta Cluster.xcscheme
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Wikipedia.xcscheme
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+LinkPreviewing.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFFirstRandomViewController.m
  WikipediaUnitTests/ArticleTestHelpers.swift
  WikipediaUnitTests/Code/ArticleCacheReadingTests.swift
  WikipediaUnitTests/Code/ArticlePerformanceTests.swift
  WikipediaUnitTests/Code/ArticleViewControllerTests.swift
  WikipediaUnitTests/Fixtures/320pxVizslaRáhúzAVadra.jpg
  WikipediaUnitTests/Fixtures/40pxCommonsLogo.svg.webp
  WikipediaUnitTests/Fixtures/46pxWikiquoteLogo.svg.webp
  WikipediaUnitTests/Fixtures/46pxWikispeciesLogo.svg.webp
  WikipediaUnitTests/Fixtures/51pxWikisourceLogo.svg.webp
  WikipediaUnitTests/Fixtures/54pxWikibooksLogo.svg.webp
  WikipediaUnitTests/Fixtures/54pxWikinewsLogo.svg.webp
  WikipediaUnitTests/Fixtures/54pxWiktionaryLogoV2.svg.webp
  WikipediaUnitTests/Fixtures/59pxCommonsLogo.svg.webp
  WikipediaUnitTests/Fixtures/640px-Flag_of_the_United_States_(Pantone).svg.png
  WikipediaUnitTests/Fixtures/640pxDogMorphologicalVariation.png
  WikipediaUnitTests/Fixtures/64pxAussieBlacktri.jpg
  WikipediaUnitTests/Fixtures/64pxOkapi2.jpg
  WikipediaUnitTests/Fixtures/960px-Flag_of_the_United_States.svg.png
  WikipediaUnitTests/Fixtures/CollageOfNineDogs.jpg
  WikipediaUnitTests/Fixtures/DogArticleSummary.json
  WikipediaUnitTests/Fixtures/DogMobileHTML.html
  WikipediaUnitTests/Fixtures/MobileBase.css
  WikipediaUnitTests/Fixtures/MobilePCS.css
  WikipediaUnitTests/Fixtures/MobilePCS.js
  WikipediaUnitTests/Fixtures/MobileSite.css
  WikipediaUnitTests/Fixtures/PCSI18N.json
  WikipediaUnitTests/Fixtures/RedPencilIcon.png
  WikipediaUnitTests/Fixtures/UserInfoGroups.json
  WikipediaUnitTests/Fixtures/basic.css
  WikipediaUnitTests/Fixtures/basic.html
  WikipediaUnitTests/Fixtures/basicCached.css
  WikipediaUnitTests/Fixtures/basicCached.html
  WikipediaUnitTests/Fixtures/basicZh.css
  WikipediaUnitTests/Fixtures/basicZhans.html
  WikipediaUnitTests/Manual Tests/ArticleCacheReadingManualTests.swift
  fastlane/Fastfile
Labels: Changes welcome

#3559 Fix regression in non-english languages where plural rules for 1= apply only when n=1
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ast.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/bn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/eo.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fa.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fi.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ga.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/gl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/hu.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/id.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/it.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ja.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/jv.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ms.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/my.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/nb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/pl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sd.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sk.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ta.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/th.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/vi.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.stringsdict
  scripts/localization
  scripts/localization.swift
Labels: Changes welcome, Low Impact

#3560 Fix language comparison error
  Wikipedia/Code/MWKLanguageLink.m
  Wikipedia/Code/SearchLanguagesBarViewController.swift
Labels: Changes welcome, Low Impact

#3563 Hide message on wikitext load
  Wikipedia/Code/SectionEditorViewController.swift
Labels: Changes welcome, Low Impact

#3565 Fix "Add another language" button
  Wikipedia/Code/WMFArticleLanguagesSectionFooter.h
  Wikipedia/Code/WMFArticleLanguagesSectionFooter.m
  Wikipedia/Code/WMFArticleLanguagesSectionFooter.xib
  Wikipedia/Code/WMFLanguagesViewController.m
Labels: Changes welcome

#3566 Only show the description editing option of the description is from Wikidata
  Wikipedia/Code/ArticleViewController+Editing.swift
Labels: Changes welcome, Low Impact

#3561 Match functionality of JavaScript's encodeURIComponent() for encoding URL path components
  WMF Framework/CharacterSet+LinkParsing.swift
  WMF Framework/NSCharacterSet+WMFLinkParsing.h
  WMF Framework/NSCharacterSet+WMFLinkParsing.m
  WMF Framework/String+LinkParsing.swift
  WMF Framework/WMFContentGroup+Extensions.m
  Wikipedia/Code/NSURLComponents+WMFLinkParsing.m
  WikipediaUnitTests/Code/TalkPageFetcherTests.swift
Labels: Changes welcome

#3554 Add `ArticleSurveyTimerController` for survey timer management
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleSurveyTimerController.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+SurveyAnnouncements.swift
  Wikipedia/Code/ArticleViewController.swift
Labels: Changes welcome

#3568 Update contributors.
  Wikipedia/Code/AboutViewController.plist
Labels: Low Impact

#3569 Only show updating animation if a library migration is occurring on launch
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/RootNavigationController.swift
  Wikipedia/Code/SplashScreenViewController.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFThemeableNavigationController.m
Labels: Changes welcome

#3571 Hide splash view with animation after onboarding
  Wikipedia/Code/WMFAppViewController.m
Labels: Low Impact, Question(s)

#3570 Allow user to tap article to dismiss references
  Wikipedia/Code/ArticleViewController+References.swift
  Wikipedia/Code/ArticleViewController.swift
Labels: Changes welcome

#3572 Remove orphaned files.
  Wikipedia/Code/EventCapsule.swift
  Wikipedia/Code/MWKArticle+Javascript.swift
  Wikipedia/Code/PiwikTracker+WMFExtensions.h
  Wikipedia/Code/PiwikTracker+WMFExtensions.m
  Wikipedia/Code/SavedArticlesViewController.swift
  Wikipedia/Code/UILabel+Fonts.swift
  Wikipedia/Code/UITableView+WMFLockedUpdates.h
  Wikipedia/Code/UITableView+WMFLockedUpdates.m
  Wikipedia/Code/WMFCVLSectionColumn.h
  Wikipedia/Code/WMFCVLSectionColumn.m
  Wikipedia/Code/WMFExploreCollectionViewController.h
  Wikipedia/Code/WMFExploreSectionSchema.m
  Wikipedia/Code/WMFProxyServer.m
  Wikipedia/Third Party Code/AFNetworking/AFCompatibilityMacros.h
  Wikipedia/Third Party Code/AFNetworking/AFHTTPSessionManager.h
  Wikipedia/Third Party Code/AFNetworking/AFHTTPSessionManager.m
  Wikipedia/Third Party Code/AFNetworking/AFNetworkReachabilityManager.h
  Wikipedia/Third Party Code/AFNetworking/AFNetworkReachabilityManager.m
  Wikipedia/Third Party Code/AFNetworking/AFNetworking.h
  Wikipedia/Third Party Code/AFNetworking/AFSecurityPolicy.h
  Wikipedia/Third Party Code/AFNetworking/AFSecurityPolicy.m
  Wikipedia/Third Party Code/AFNetworking/AFURLRequestSerialization.h
  Wikipedia/Third Party Code/AFNetworking/AFURLRequestSerialization.m
  Wikipedia/Third Party Code/AFNetworking/AFURLResponseSerialization.h
  Wikipedia/Third Party Code/AFNetworking/AFURLResponseSerialization.m
  Wikipedia/Third Party Code/AFNetworking/AFURLSessionManager.h
  Wikipedia/Third Party Code/AFNetworking/AFURLSessionManager.m
Labels: Changes welcome, Low Impact

#3577 Sync with campaign id prefix tweak for iOS announcement
  Wikipedia/Code/WMFAnnouncementsContentSource.m
Labels: Low Impact

#3575 Update bundled files with the latest from staging
  Wikipedia/assets/pcs-html-converter/base.css
  Wikipedia/assets/pcs-html-converter/pcs.css
  Wikipedia/assets/pcs-html-converter/pcs.js
Labels: Low Impact

#3530 add template macro for empty header on new files
  Wikipedia.xcodeproj/xcshareddata/IDETemplateMacros.plist
  scripts/setup
  scripts/setup_git_hooks
  scripts/strip_header
Labels: Low Impact

#3578 For Explore feed options, use form sheet on iPad
  Wikipedia/Code/ExploreViewController.swift
Labels: Low Impact

#3585 Bump version to 6.6.1
  ContinueReadingWidget/Info.plist
  FeaturedArticleWidget/Info.plist
  InTheNewsNotification/Info.plist
  TopReadWidget/Info.plist
  WMF Framework/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Experimental-Info.plist
  Wikipedia/Local-Info.plist
  Wikipedia/Staging-Info.plist
  Wikipedia/User Testing-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaBetaClusterTests/Info.plist
  WikipediaUITests/Info.plist
  WikipediaUnitTests/Info.plist
Labels: Low Impact

#3586 Improve accessibility of onboarding flow when tapping "Next"
  Wikipedia/Code/WMFWelcomeContainerViewController.swift
Labels: Low Impact
