Repository wikimedia/wikipedia-ios, pull requests merged in 2020-02, with the labels that each got.

#3423 mobile-html: Add references fetcher
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/ArticleURLConverter.swift
  WMF Framework/CharacterSet+LinkParsing.swift
  WMF Framework/RelatedSearchFetcher.swift
  WMF Framework/Router.swift
  WMF Framework/String+LinkParsing.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleReferencesFetcher.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/DiffController.swift
  Wikipedia/Code/MWKTitle.m
  Wikipedia/Code/NSString+WMFPageUtilities.h
  Wikipedia/Code/NSString+WMFPageUtilities.m
  Wikipedia/Code/NSURL+WMFLinkParsing.m
  Wikipedia/Code/NSURLComponents+WMFLinkParsing.m
  Wikipedia/Code/PageHistoryFetcher.swift
  Wikipedia/Code/References.swift
  Wikipedia/Code/TalkPageFetcher.swift
  Wikipedia/Code/URL+LinkParsing.swift
  Wikipedia/Code/WMFFeedNewsStory.m
  Wikipedia/Code/WMFFeedOnThisDayEvent.m
  Wikipedia/Code/WMFImageURLParsing.m
  WikipediaUnitTests/Code/NSURL+WMFLinkParsingTests.m
Labels: Changes welcome, Low Impact

#3424 mobile-html: Fix article margins
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/EditPreviewViewController.swift
Labels: Changes welcome, Low Impact

#3425 mobile-html: Prototype of native references view
  WMF Framework/CGRect+Layout.swift
  WMF Framework/NSCharacterSet+WMFLinkParsing.h
  WMF Framework/NSCharacterSet+WMFLinkParsing.m
  WMF Framework/ReferenceCollectionViewCell.swift
  WMF Framework/String+JavaScript.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleViewController+ArticleInformation.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+References.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/NSString+WMFExtras.h
  Wikipedia/Code/NSString+WMFExtras.m
  Wikipedia/Code/NSString+WMFHTMLParsing.h
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/PageIssuesTableViewController.swift
  Wikipedia/Code/ReferencesViewController.swift
  Wikipedia/Code/SectionEditorWebViewMessagingController.swift
  Wikipedia/Code/ViewController+URLHandling.swift
  Wikipedia/Code/WKWebView+WMFWebViewControllerJavascript.m
  Wikipedia/Code/WMFLegacyReference.swift
  Wikipedia/Code/WMFReference.swift
  Wikipedia/Code/WMFReferencePageViewController.swift
  Wikipedia/Code/WMFReferencePanelViewController.swift
  Wikipedia/Code/WMFReferencePopoverMessageViewController.h
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/assets/index.js
  Wikipedia/assets/styleoverrides.css
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  www/Gruntfile.js
  www/js/elementLocation.js
  www/js/findInPage.js
  www/less/findInPage.less
  www/less/misc.less
  www/less/refs.less
Labels: Changes welcome, Low Impact

#3426 mobile-html: Fetcher consolidation
  WMF Framework/ArticleSummaryFetcher.swift
  WMF Framework/ArticleURLConverter.swift
  WMF Framework/Fetcher.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Local Node Services.xcscheme
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleReferencesFetcher.swift
  Wikipedia/Code/ArticleSummaryController.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/MediaList.swift
  Wikipedia/Code/References.swift
Labels: Changes welcome

#3412 Converter updates
  WMF Framework/ArticleCacheController.swift
  WMF Framework/Configuration.swift
  WMF Framework/WMFArticle+CoreDataProperties.h
  WMF Framework/WMFArticle+CoreDataProperties.m
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 3.xcdatamodel/contents
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/MWKArticle+LegacyMobileview.swift
  Wikipedia/Code/MWKDataStore+LegacyMobileview.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/SavedArticlesFetcher.swift
  Wikipedia/Code/WMFAppViewController.m
Labels: Changes welcome

#3432 Remove native references view
  WMF Framework/CharacterSet+LinkParsing.swift
  WMF Framework/ReferenceCollectionViewCell.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+References.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/References.swift
  Wikipedia/Code/ReferencesViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Changes welcome, Low Impact

#3434 Add image gallery based on media-list endpoint
  WMF Framework/ArticleURLConverter.swift
  WMF Framework/ReadingListsSyncOperation.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCacheProvider.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+Media.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MediaList.swift
  Wikipedia/Code/MediaListGalleryViewController.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/SavedArticlesCollectionViewController.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/ViewController.swift
  Wikipedia/Code/WMFImageGalleryViewController.h
  Wikipedia/Code/WMFImageGalleryViewController.m
  Wikipedia/assets/pcs-html-converter/build/PCSHTMLConverter.js
  Wikipedia/assets/pcs-html-converter/build/PCSHTMLConverter.js.map
  Wikipedia/assets/pcs-html-converter/build/Polyfill.js
  Wikipedia/assets/pcs-html-converter/build/Polyfill.js.map
  WikipediaUnitTests/Code/DataStoreTests.swift
Labels: Changes welcome

#3436 Ensure legacy data is removed
  WMF Framework/WMFArticle+CoreDataProperties.h
  WMF Framework/WMFArticle+CoreDataProperties.m
  WMF Framework/Wikipedia.xcdatamodeld/Wikipedia 3.xcdatamodel/contents
  Wikipedia/Code/MWKDataStore+LegacyMobileview.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/SavedArticlesFetcher.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFDatabaseHouseKeeper.swift
Labels: Changes welcome

#3437 Add .xcversion file to indicate the xcode version for building
  .xcversion
  Jenkinsfile
  docs/ci.md
  fastlane/Fastfile
  fastlane/README.md
Labels: Changes welcome, Low Impact

#3439 Consolidate user defaults
  WMF Framework/EventLoggingService.swift
  WMF Framework/ExploreFeedPreferencesUpdateCoordinator.swift
  WMF Framework/ReadingListsSyncOperation.swift
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AccountViewController.swift
  Wikipedia/Code/AppDelegate.m
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/ArticleTableOfContentsDisplayController.swift
  Wikipedia/Code/ArticleViewController+Editing.swift
  Wikipedia/Code/ArticleViewController+WIconPopover.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/BaseExploreFeedSettingsViewController.swift
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/EventLoggingFunnel.m
  Wikipedia/Code/ExploreCardViewController.swift
  Wikipedia/Code/ExploreFeedSettingsViewController.swift
  Wikipedia/Code/FontSizeSliderViewController.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKLanguageLinkController.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/NotificationSettingsViewController.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/ReadingListsAlertController.swift
  Wikipedia/Code/ReadingThemesControlsProtocols.swift
  Wikipedia/Code/ReadingThemesControlsViewController.swift
  Wikipedia/Code/SearchLanguagesBarViewController.swift
  Wikipedia/Code/SearchSettingsViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/TalkPagesController.swift
  Wikipedia/Code/UserHistoryFunnel.swift
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFContinueReadingContentSource.m
  Wikipedia/Code/WMFFeedContentSource.m
  Wikipedia/Code/WMFImageGalleryViewController.m
  Wikipedia/Code/WMFNearbyContentSource.m
  Wikipedia/Code/WMFReferencePopoverMessageViewController.m
  Wikipedia/Code/WMFSearchFunnel.m
  Wikipedia/Code/WMFSettingsMenuItem.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Code/WMFWelcomeLanguageTableViewController.swift
  WikipediaUnitTests/Code/MWKLanguageLinkControllerTests.m
  WikipediaUnitTests/Code/WMFNotificationTests.m
Labels: Changes welcome

#3442 mobile-html: Reference link and lead image bug fixes
  WMF Framework/ArticleCacheController.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+References.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/Properties.js
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFReferencePageViewController.swift
  Wikipedia/Code/WMFReferencePanelViewController.swift
  Wikipedia/Code/WMFReferencePopoverMessageViewController.h
Labels: Changes welcome, Low Impact

#3443 mobile-html: Implement find in page, fix other bugs
  ContinueReadingWidget/WMFTodayContinueReadingWidgetViewController.swift
  WMF Framework/NSManagedObjectContext+History.swift
  WMF Framework/WMF.h
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleFetchedResultsViewController.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+FindInPage.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/MWKDataStore.h
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/MWKHistoryList.h
  Wikipedia/Code/MWKHistoryList.m
  Wikipedia/Code/NSString+WMFHTMLParsing.m
  Wikipedia/Code/TalkPageContainerViewController.swift
  Wikipedia/Code/WMFContinueReadingContentSource.m
  Wikipedia/Code/WMFEmptyView.h
  Wikipedia/Code/WMFEmptyView.m
  Wikipedia/Code/WMFSearchFetcher.m
  Wikipedia/assets/index.js
  www/js/findInPage.js
Labels: Changes welcome

#3445 mobile-html: handle title description and pronunciation actions
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+Media.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
Labels: Changes welcome, Low Impact

#3446 Fix inconsistent `UISwitch` state when Search settings table cells are configured
  Wikipedia/Code/SearchSettingsViewController.swift
Labels: Low Impact

#3440 Caching rework
  WMF Framework/ArticleCacheController.swift
  WMF Framework/ArticleCacheHeaderProvider.swift
  WMF Framework/ArticleCacheKeyGenerator.swift
  WMF Framework/CacheController.swift
  WMF Framework/CacheControllerWrapper.swift
  WMF Framework/CacheDBWriterHelper.swift
  WMF Framework/CacheDBWriting.swift
  WMF Framework/CacheFetching.swift
  WMF Framework/CacheFileWriter.swift
  WMF Framework/CacheFileWriterHelper.swift
  WMF Framework/CacheFileWriting.swift
  WMF Framework/CacheGatekeeper.swift
  WMF Framework/CacheHeaderProviding.swift
  WMF Framework/CacheKeyGenerating.swift
  WMF Framework/CacheProviderHelper.swift
  WMF Framework/CacheProviding.swift
  WMF Framework/Fetcher.swift
  WMF Framework/ImageCacheController.swift
  WMF Framework/ImageCacheDBWriter.swift
  WMF Framework/ImageCacheFileWriter.swift
  WMF Framework/ImageCacheHeaderProvider.swift
  WMF Framework/ImageCacheKeyGenerator.swift
  WMF Framework/ImageCacheProvider.swift
  WMF Framework/ImageFetcher.swift
  WMF Framework/PersistentCache.xcdatamodeld/NewCache.xcdatamodel/contents
  WMF Framework/PersistentCacheItem+CoreDataProperties.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleCacheFileWriter.swift
  Wikipedia/Code/ArticleCacheProvider.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+Media.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/NSLocale+WMFExtras.swift
  Wikipedia/Code/SavedArticlesFetcher.swift
  Wikipedia/Code/SchemeHandler/SchemeHandler.swift
  Wikipedia/Code/Session.swift
  WikipediaUnitTests/Code/LocaleTests.swift
Labels: Changes welcome

#3449 Loading lead image in offline mode
  WMF Framework/CacheFetching.swift
  WMF Framework/ImageFetcher.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/UIImageView+WMFImageFetching.h
  Wikipedia/Code/UIImageView+WMFImageFetching.m
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.h
  Wikipedia/Code/UIImageView+WMFImageFetchingInternal.m
Labels: Changes welcome, Low Impact

#3450 Load gallery in offline mode
  WMF Framework/ArticleCacheHeaderProvider.swift
  WMF Framework/CacheControllerWrapper.swift
  WMF Framework/CacheFetching.swift
  WMF Framework/CacheFileWriter.swift
  WMF Framework/CacheHeaderProviding.swift
  WMF Framework/CacheKeyGenerating.swift
  WMF Framework/CacheProviderHelper.swift
  WMF Framework/Fetcher.swift
  WMF Framework/ImageCacheHeaderProvider.swift
  WMF Framework/ImageInfoCacheHeaderProvider.swift
  WMF Framework/ImageInfoCacheKeyGenerator.swift
  WMF Framework/URLComponents+Extensions.swift
  WMF Framework/WMF.h
  WMF Framework/WMFLegacyFetcher.h
  WMF Framework/WMFLegacyFetcher.m
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCacheDBWriter.swift
  Wikipedia/Code/ArticleFetcher.swift
  Wikipedia/Code/ArticleViewController+ArticleToolbarHandling.swift
  Wikipedia/Code/InsertMediaSearchViewController.swift
  Wikipedia/Code/MWKImageInfoFetcher+PicOfTheDayInfo.h
  Wikipedia/Code/MWKImageInfoFetcher.h
  Wikipedia/Code/MWKImageInfoFetcher.m
  Wikipedia/Code/MediaListGalleryViewController.swift
  Wikipedia/Code/ReadingListsController.swift
  Wikipedia/Code/RequestError.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFImageGalleryViewController.m
  Wikipedia/Code/Wikipedia-Bridging-Header.h
Labels: Changes welcome

#3452 Add documentation to ImageController and reorganize the file
  Wikipedia/Code/ImageController.swift
Labels: Changes welcome, Low Impact

#3453 Remove unused WMFFIFOCache
  WMF Framework/WMF.h
  WMF Framework/WMFFIFOCache.h
  WMF Framework/WMFFIFOCache.m
  Wikipedia.xcodeproj/project.pbxproj
Labels: Low Impact

#3455 Update reference back links navigator to match the mockups
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
  Wikipedia/Code/ReferenceBackLinksViewController.swift
  Wikipedia/Images.xcassets/references.imageset/Contents.json
  Wikipedia/Images.xcassets/references.imageset/fill1.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ca.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/my.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ne.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sr-EC.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: Changes welcome, Low Impact
