Repository wikimedia/wikipedia-ios, pull requests merged in 2022-03, with the labels that each got.

#4143 Improve logic for push notification tap routing
  WMF Framework/CommonStrings.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/DescriptionEditViewController.swift
  Wikipedia/Code/EditPreviewViewController.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/InsertLinkViewController.swift
  Wikipedia/Code/InsertMediaSearchResultPreviewingViewController.swift
  Wikipedia/Code/InsertMediaViewController.swift
  Wikipedia/Code/NotificationsCenterFlowHostingController.swift
  Wikipedia/Code/NotificationsCenterViewController.swift
  Wikipedia/Code/SectionEditorViewController.swift
  Wikipedia/Code/TalkPageReplyListViewController.swift
  Wikipedia/Code/TalkPageTopicNewViewController.swift
  Wikipedia/Code/WMFAppViewController+Extensions.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Beta

#4155 Add Notifications Center onboarding modal and panel
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Wikipedia/Code/NotificationsCenterOnboardingHostingViewController.swift
  Wikipedia/Code/NotificationsCenterOnboardingView.swift
  Wikipedia/Code/NotificationsCenterViewController.swift
  Wikipedia/Code/Panels.swift
  Wikipedia/Images.xcassets/notifications/onboarding/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-bell-alt.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-bell-alt.imageset/notifications-center-onboarding-bell-alt.pdf
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-bell.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-bell.imageset/notifications-center-onboarding-bell.pdf
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-filter-alt.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-filter-alt.imageset/notifications-center-onboarding-filter-alt.pdf
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-filter.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-filter.imageset/notifications-center-onboarding-filter.pdf
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-inbox-alt.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-inbox-alt.imageset/notifications-center-onboarding-inbox-alt.pdf
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-inbox.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-inbox.imageset/notifications-center-onboarding-inbox.pdf
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-push-alt.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-push-alt.imageset/notifications-center-onboarding-push-alt.pdf
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-push.imageset/Contents.json
  Wikipedia/Images.xcassets/notifications/onboarding/notifications-center-onboarding-push.imageset/notifications-center-onboarding-push.pdf
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: Question(s), Beta

#4160 Add Push permissions opt in to Notifications Center onboarding
  Wikipedia/Code/NotificationsCenterViewController.swift
  Wikipedia/Code/NotificationsCenterViewModel.swift
  Wikipedia/Code/WMFAppViewController+Extensions.swift
  Wikipedia/Code/WMFNotificationsController.m
Labels: Update branch before merging, Beta

#4158 NotificationsCenterCellViewModel tests
  WMF Framework/CommonStrings.swift
  WMF Framework/Remote Notifications/Model/RemoteNotificationType.swift
  WMF Framework/Remote Notifications/Model/RemoteNotificationsModelController.swift
  WMF Framework/Remote Notifications/RemoteNotificationsController.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NotificationsCenterCell.swift
  Wikipedia/Code/NotificationsCenterCellViewModel+IconNameExtensions.swift
  Wikipedia/Code/NotificationsCenterCellViewModel+LinkExtensions.swift
  Wikipedia/Code/NotificationsCenterCellViewModel+SheetActionExtensions.swift
  Wikipedia/Code/NotificationsCenterCellViewModel.swift
  Wikipedia/Code/NotificationsCenterModelController.swift
  Wikipedia/Code/NotificationsCenterViewController.swift
  Wikipedia/Code/NotificationsCenterViewModel.swift
  Wikipedia/Code/SectionEditorViewController.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelEditMilestoneTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelEditRevertedTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelGenericTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelLoginIssuesTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelMentionTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelPageLinkTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelThanksTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelUserRightsChangeTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelUserTalkMessageTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelWelcomeTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterCellViewModelWikidataConnectionTests.swift
  WikipediaUnitTests/Code/Notifications Tests/NotificationsCenterViewModelTests.swift
  WikipediaUnitTests/Code/Notifications Tests/RemoteNotificationsModelController+TestExtensions.swift
  WikipediaUnitTests/Fixtures/notifications-editMilestone.json
  WikipediaUnitTests/Fixtures/notifications-editReverted.json
  WikipediaUnitTests/Fixtures/notifications-generic.json
  WikipediaUnitTests/Fixtures/notifications-loginIssues.json
  WikipediaUnitTests/Fixtures/notifications-mentions.json
  WikipediaUnitTests/Fixtures/notifications-pageLink.json
  WikipediaUnitTests/Fixtures/notifications-thanks.json
  WikipediaUnitTests/Fixtures/notifications-userRights.json
  WikipediaUnitTests/Fixtures/notifications-userTalkMessages.json
  WikipediaUnitTests/Fixtures/notifications-welcome.json
  WikipediaUnitTests/Fixtures/notifications-wikidataConnection.json
Labels: Beta

#4168 Update notifications cell read/unread styles
  Wikipedia/Code/NotificationsCenterCell.swift
  Wikipedia/Code/NotificationsCenterCellStyle.swift
Labels: Beta

#4166 Add Notifications Center notification detail view
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/NotificationsCenterAction.swift
  Wikipedia/Code/NotificationsCenterDetailActionCell.swift
  Wikipedia/Code/NotificationsCenterDetailContentCell.swift
  Wikipedia/Code/NotificationsCenterDetailHeaderCell.swift
  Wikipedia/Code/NotificationsCenterDetailView.swift
  Wikipedia/Code/NotificationsCenterDetailViewController.swift
  Wikipedia/Code/NotificationsCenterIconType.swift
  Wikipedia/Code/NotificationsCenterViewController.swift
  Wikipedia/Code/ReusableCell.swift
Labels: Beta

#4167 Update displaying logic for the explore feed notifications card
  WMF Framework/WMFContentGroup+Extensions.m
  WMF Framework/WMFExploreFeedContentController.m
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/MWKDataStore.m
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/WMFAnnouncementsContentSource.m
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFContentGroup+WMFFeedContentDisplaying.m
  Wikipedia/Code/WMFFeedContentSource.m
Labels: Beta
