Repository wikimedia/wikipedia-ios, pull requests merged in 2025-09, with the labels that each got.

#5408 No longer explicitly set left/right margin through PCS.
  Wikipedia/Code/ActionHandlerScript.swift
  Wikipedia/Code/ArticleWebMessagingController.swift
Labels: 7.8.2

#5409 T402705: Updated Saved Article Titles to Bold
  WMFComponents/Sources/WMFComponents/Components/Year in Review/View Models/WMFYearInReviewViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/Slide Views/WMFYearInReviewSlideStandardView.swift
  Wikipedia/Code/YearInReviewCoordinator.swift
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.8.2

#5405 [YiR V3] Update most read day slide
  .github/workflows/run_unit_tests.yml
  WMFComponents/Sources/WMFComponents/Components/Year in Review/View Models/WMFYearInReviewMostReadDateV3ViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/View Models/WMFYearInReviewViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/Shareable Slide Views/WMFYearInReviewSlideMostReadDateV3ShareableView.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/Slide Views/WMFYearInReviewSlideMostReadDateV3View.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/WMFYearInReviewBodyView.swift
  WMFData/Sources/WMFData/Data Controllers/Shared/WMFPageViewsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/Slide Data Controllers/WMFYearInReviewMostReadDateSlideDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/Slide Data Controllers/WMFYearInReviewSlideDataControllerFactory.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/Slide Data Controllers/YearInReviewTopArticlesSlideDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFYearInReviewDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFYearInReviewSlideConfig.swift
  WMFData/Sources/WMFData/Models/Developer Settings/WMFFeatureConfigResponse.swift
  WMFData/Sources/WMFData/Models/Year In Review/WMFYearInReviewSlide.swift
  WMFData/Sources/WMFDataMocks/Resources/feature-get-config.json
  WMFData/Tests/WMFDataTests/WMFPageViewsDataControllerTests.swift
  WMFData/Tests/WMFDataTests/WMFYearInReviewDataControllerCreateOrRetrieveTests.swift
  WMFData/Tests/WMFDataTests/WMFYearInReviewDataControllerTests.swift
  Wikipedia/Code/YearInReviewCoordinator.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
Labels: 7.8.2

#5413 T402696: Donor Slides v3 Part 1/2
  WMFComponents/Sources/WMFComponents/Assets.xcassets/yir/contribution-slide.imageset/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/yir/contribution-slide.imageset/background+puzzle (1).png
  WMFComponents/Sources/WMFComponents/Components/Year in Review/View Models/WMFYearInReviewContributorSlideViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/View Models/WMFYearInReviewViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/Slide Views/WMFYearInReviewContributionSlideView.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/WMFYearInReviewBodyView.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/Slide Data Controllers/WMFYearInReviewDonateCountSlideDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/Slide Data Controllers/YearInReviewEditCountSlideDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFUserContributionsAPIResponse.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFYearInReviewDataController.swift
  WMFData/Sources/WMFData/Store/WMFUserDefaultsKey.swift
  Wikipedia.xcodeproj/xcshareddata/xcschemes/Staging.xcscheme
  Wikipedia/Code/YearInReviewCoordinator.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.8.2

#5410 Allow other arrow directions for article tooltip
  Wikipedia/Code/ArticleViewController+Tooltips.swift
Labels: 7.8.2

#5420 [YiR V3] Hours spent slide - Part 1
  WMFComponents/Sources/WMFComponents/Components/Year in Review/View Models/WMFYearInReviewViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/Slide Views/WMFYearInReviewSlideStandardView.swift
  WMFData/Sources/WMFData/Data Controllers/Shared/WMFPageViewsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/Slide Data Controllers/YearInReviewReadCountSlideDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFYearInReviewDataController.swift
  WMFData/Sources/WMFData/Models/Shared/WMFProject.swift
  WMFData/Tests/WMFDataTests/WMFYearInReviewDataControllerCreateOrRetrieveTests.swift
  Wikipedia/Code/YearInReviewCoordinator.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/as.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/azb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/be-tarask.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/bgn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/cnh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fo.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/haw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/hrx.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ka.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/kn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ksh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/mai.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/om.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sa.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sco.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tcy.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/xmf.lproj/Localizable.stringsdict
Labels: 7.8.2

#5425 Localisation updates from https://translatewiki.net.
  Wikipedia/Localizations/ar.lproj/Localizable.strings
  Wikipedia/Localizations/az.lproj/Localizable.strings
  Wikipedia/Localizations/cs.lproj/Localizable.strings
  Wikipedia/Localizations/da.lproj/Localizable.strings
  Wikipedia/Localizations/de.lproj/Localizable.strings
  Wikipedia/Localizations/es.lproj/Localizable.strings
  Wikipedia/Localizations/fa.lproj/Localizable.strings
  Wikipedia/Localizations/fi.lproj/Localizable.strings
  Wikipedia/Localizations/fr.lproj/Localizable.strings
  Wikipedia/Localizations/he.lproj/Localizable.strings
  Wikipedia/Localizations/ia.lproj/Localizable.strings
  Wikipedia/Localizations/it.lproj/Localizable.strings
  Wikipedia/Localizations/lb.lproj/Localizable.strings
  Wikipedia/Localizations/mk.lproj/Localizable.strings
  Wikipedia/Localizations/nl.lproj/Localizable.strings
  Wikipedia/Localizations/ps.lproj/Localizable.strings
  Wikipedia/Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/Localizations/pt.lproj/Localizable.strings
  Wikipedia/Localizations/rki.lproj/Localizable.strings
  Wikipedia/Localizations/shn.lproj/Localizable.strings
  Wikipedia/Localizations/sr-ec.lproj/Localizable.strings
  Wikipedia/Localizations/sv.lproj/Localizable.strings
  Wikipedia/Localizations/te.lproj/Localizable.strings
  Wikipedia/Localizations/tr.lproj/Localizable.strings
  Wikipedia/Localizations/uk.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/cs.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/it.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ps.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sr-EC.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/te.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/te.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.stringsdict
  fastlane/metadata/pt-br/description.txt
  fastlane/metadata/pt-pt/description.txt
Labels: 7.8.3

#5421 [YiR V3] Modify app to point to new config endpoint
  WMFData/Sources/WMFData/Data Controllers/Developer Settings/WMFDeveloperSettingsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFYearInReviewDataController.swift
  WMFData/Sources/WMFData/Environment/WMFDataEnvironment.swift
  WMFData/Sources/WMFData/Extensions/URL+API.swift
  WMFData/Sources/WMFData/Models/Developer Settings/WMFFeatureConfigResponse.swift
  WMFData/Sources/WMFDataMocks/Resources/feature-get-config.json
  WMFData/Sources/WMFDataMocks/WMFMockBasicService.swift
  WMFData/Tests/WMFDataTests/WMFDeveloperSettingsDataControllerTests.swift
  WMFData/Tests/WMFDataTests/WMFYearInReviewDataControllerCreateOrRetrieveTests.swift
  WMFData/Tests/WMFDataTests/WMFYearInReviewDataControllerTests.swift
Labels: 7.8.3

#5419 [Tabs] Fix tabs layout on iPad mini
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/WMFArticleTabsView.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/WMFArticleTabsViewModel.swift
Labels: 7.8.3

#5428 T403543: Custom Icon Settings Toggle
  WMF Framework/CommonStrings.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFYearInReviewDataController.swift
  WMFData/Sources/WMFData/Store/WMFUserDefaultsKey.swift
  Wikipedia/Code/AppearanceSettingsViewController.swift
  Wikipedia/Code/InsertMediaSettingsViewController.swift
  Wikipedia/Code/WMFSettingsTableViewCell.h
  Wikipedia/Code/WMFSettingsTableViewCell.m
  Wikipedia/Code/YearInReviewCoordinator.swift
  Wikipedia/Images.xcassets/AppIconContributor_Small.imageset/60 (1).pdf
  Wikipedia/Images.xcassets/AppIconContributor_Small.imageset/Contents.json
  Wikipedia/Images.xcassets/AppIcon_Small.imageset/60.pdf
  Wikipedia/Images.xcassets/AppIcon_Small.imageset/Contents.json
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.8.3

#5433 T402696: Donor Design Feedback
  WMFComponents/Sources/WMFComponents/Components/Year in Review/Views/Slide Views/WMFYearInReviewContributionSlideView.swift
Labels: 7.8.3

#5435 [TABS] Old tabs code cleanup
  WMF Framework/CommonStrings.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/DYK/TextViewWrapper.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/DYK/WMFNewArticleTabDidYouKnowViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/DYK/WMFNewArticleTabViewDidYouKnowView.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/New Tab/Because You Read/WMFBecauseYouReadView.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/New Tab/Because You Read/WMFBecauseYouReadViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/New Tab/Settings/WMFNewArticleTabSettingsView.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/New Tab/Settings/WMFNewArticleTabSettingsViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/WMFArticleTabsHostingController.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/WMFArticleTabsViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Search/Recently Searched/WMFNewTabSearchView.swift
  WMFComponents/Sources/WMFComponents/Components/Search/Recently Searched/WMFRecentlySearchedViewModel.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCoordinator.swift
  Wikipedia/Code/ArticleTabsFunnel.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/NewArticleTabCoordinator.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/TabsOverviewCoordinator.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFNewArticleTabDataController.swift
  Wikipedia/Code/WMFNewArticleTabsSettingsViewController.swift
  Wikipedia/Code/WMFSettingsMenuItem.h
  Wikipedia/Code/WMFSettingsMenuItem.m
  Wikipedia/Code/WMFSettingsViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fa.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 7.8.3

#5431 Fix unit test status checks on Update Versions and Translatewiki PRs
  .github/workflows/localization.yml
  .github/workflows/update_version.yml
  docs/ci.md
Labels: 7.8.3

#5449 Localisation updates from https://translatewiki.net.
  Wikipedia/Localizations/ar.lproj/Localizable.strings
  Wikipedia/Localizations/az.lproj/Localizable.strings
  Wikipedia/Localizations/de.lproj/Localizable.strings
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/es.lproj/Localizable.strings
  Wikipedia/Localizations/fr.lproj/Localizable.strings
  Wikipedia/Localizations/ia.lproj/Localizable.strings
  Wikipedia/Localizations/lb.lproj/Localizable.strings
  Wikipedia/Localizations/mk.lproj/Localizable.strings
  Wikipedia/Localizations/nl.lproj/Localizable.strings
  Wikipedia/Localizations/ps.lproj/Localizable.strings
  Wikipedia/Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/Localizations/ru.lproj/Localizable.strings
  Wikipedia/Localizations/sr-ec.lproj/Localizable.strings
  Wikipedia/Localizations/sv.lproj/Localizable.strings
  Wikipedia/Localizations/sw.lproj/Localizable.strings
  Wikipedia/Localizations/tr.lproj/Localizable.strings
  Wikipedia/Localizations/uk.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/nl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ru.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sr-EC.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hans.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.stringsdict
Labels: 7.8.4

#5451 T401452: Categories
  WMFData/Sources/WMFData/Data Controllers/Year In Review/Slide Data Controllers/WMFYearInReviewMostReadCategoriesSlideDataController.swift
Labels: 7.8.4

#5445 [TABS] Previews
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/WMFArticleTabsView.swift
  WMFComponents/Sources/WMFComponents/Components/Article Tabs/WMFArticleTabsViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/ArticlePreview/WMFArticlePreviewView.swift
  WMFComponents/Sources/WMFComponents/Components/ArticlePreview/WMFArticlePreviewViewModel.swift
  WMFData/Sources/WMFData/Data Controllers/Article Tabs/WMFArticleTabsDataController.swift
  WMFData/Sources/WMFData/Models/Shared/WMFLanguage.swift
  WMFData/Sources/WMFData/Models/Shared/WMFProject.swift
  WMFData/Sources/WMFData/Utility/WMFURLUtils.swift
  WMFData/Sources/WMFDataMocks/WMFMockArticleTabsDataController.swift
  WMFData/Tests/WMFDataTests/WMFArticleTabsDataControllerTests.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleCoordinator.swift
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/Coordinator.swift
  Wikipedia/Code/DonateCoordinator.swift
  Wikipedia/Code/LinkCoordinator.swift
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/RandomArticleCoordinator.swift
  Wikipedia/Code/ShareActivityController.swift
  Wikipedia/Code/TabsOverviewCoordinator.swift
  Wikipedia/Code/WKProject+Extensions.swift
Labels: 7.8.4
