Repository wikimedia/wikipedia-ios, pull requests merged in 2025-07, with the labels that each got.

#5341 Localisation updates from https://translatewiki.net.
  WMF Framework/CommonStrings.swift
  Wikipedia/Localizations/ar.lproj/Localizable.strings
  Wikipedia/Localizations/ban.lproj/Localizable.strings
  Wikipedia/Localizations/ce.lproj/Localizable.strings
  Wikipedia/Localizations/da.lproj/Localizable.strings
  Wikipedia/Localizations/it.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ce.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ce.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/da.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/it.lproj/Localizable.strings
Labels: 7.7.8

#5339 Add search logging
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/SearchFunnel.swift
  Wikipedia/Code/SearchViewController.swift
Labels: 7.7.8

#5344 Localisation updates from https://translatewiki.net.
  Wikipedia/Localizations/ar.lproj/Localizable.strings
  Wikipedia/Localizations/az.lproj/Localizable.strings
  Wikipedia/Localizations/bn.lproj/Localizable.strings
  Wikipedia/Localizations/ce.lproj/Localizable.strings
  Wikipedia/Localizations/de.lproj/Localizable.strings
  Wikipedia/Localizations/es.lproj/Localizable.strings
  Wikipedia/Localizations/fa.lproj/Localizable.strings
  Wikipedia/Localizations/fr.lproj/Localizable.strings
  Wikipedia/Localizations/he.lproj/Localizable.strings
  Wikipedia/Localizations/hi.lproj/Localizable.strings
  Wikipedia/Localizations/ia.lproj/Localizable.strings
  Wikipedia/Localizations/it.lproj/Localizable.strings
  Wikipedia/Localizations/ko.lproj/Localizable.strings
  Wikipedia/Localizations/lb.lproj/Localizable.strings
  Wikipedia/Localizations/mk.lproj/Localizable.strings
  Wikipedia/Localizations/ps.lproj/Localizable.strings
  Wikipedia/Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/Localizations/sk.lproj/Localizable.strings
  Wikipedia/Localizations/sr-ec.lproj/Localizable.strings
  Wikipedia/Localizations/tr.lproj/Localizable.strings
  Wikipedia/Localizations/uk.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ce.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fa.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/he.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ps.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 7.7.8

#5347 Hide search widget announcement from prod
  Wikipedia/Code/ExploreViewController.swift
Labels: 7.7.8

#5353 Allow iPad floating tab bar tap to pop to root
  Wikipedia/Code/WMFAppViewController.m
Labels: 7.7.8

#5346 Flag field as one time code for email auth
  Wikipedia/Code/WMFTwoFactorPasswordViewController.swift
Labels: 7.7.8

#5356 T399466: Make Tabs v1 Available to all
  WMFComponents/Sources/WMFComponents/Components/Developer Settings/WMFDeveloperSettingsViewModel.swift
  WMFComponents/Sources/WMFComponents/Extensions/Navigation Bar/WMFNavigationBarConfiguring.swift
  WMFData/Sources/WMFData/Data Controllers/Article Tabs/WMFArticleTabsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Developer Settings/WMFDeveloperSettingsDataController.swift
  Wikipedia/Code/ArticleCoordinator.swift
  Wikipedia/Code/ArticlePeekPreviewViewController.swift
  Wikipedia/Code/ArticleToolbarController.swift
  Wikipedia/Code/ArticleViewController+Tooltips.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/ExploreViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/NavigationStateController.swift
  Wikipedia/Code/PlacesViewController.swift
  Wikipedia/Code/SavedViewController.swift
  Wikipedia/Code/SearchViewController.swift
  Wikipedia/Code/TabsOverviewCoordinator.swift
  Wikipedia/Code/WMFAppViewController+Extensions.swift
Labels: 7.7.8

#5360 Include user-agent when posting with GitHubPRBot.
  .github/workflows/post_phab.yml
Labels: 7.8.0

#5355 T399045: Fix TabOverview presentation from Random Article
  Wikipedia/Code/ArticleCoordinator.swift
  Wikipedia/Code/RandomArticleCoordinator.swift
Labels: 7.8.0

#5362 Localisation updates from https://translatewiki.net.
  Wikipedia/Localizations/az.lproj/Localizable.strings
  Wikipedia/Localizations/fr.lproj/Localizable.strings
  Wikipedia/Localizations/lb.lproj/Localizable.strings
  Wikipedia/Localizations/mk.lproj/Localizable.strings
  Wikipedia/Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/Localizations/ro.lproj/Localizable.strings
  Wikipedia/Localizations/skr-arab.lproj/Localizable.strings
  Wikipedia/Localizations/tr.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ro.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/tr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 7.8.0

#5366 Localisation updates from https://translatewiki.net.
  Wikipedia/Localizations/de.lproj/Localizable.strings
  Wikipedia/Localizations/ia.lproj/Localizable.strings
  Wikipedia/Localizations/ko.lproj/Localizable.strings
  Wikipedia/Localizations/sr-ec.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/de.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ko.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sr-EC.lproj/Localizable.strings
Labels: 7.8.0

#5364 Make WebView inspectable in debug builds.
  Wikipedia/Code/ArticleViewController.swift
Labels: 7.8.0

#5371 Localisation updates from https://translatewiki.net.
  Wikipedia/Localizations/hy.lproj/Localizable.strings
  Wikipedia/Localizations/ia.lproj/Localizable.strings
  Wikipedia/Localizations/ps.lproj/Localizable.strings
  Wikipedia/Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hy.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ia.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ps.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/pt-br.lproj/Localizable.stringsdict
Labels: 7.8.1

#5372 Fix iPad sharing crash
  Wikipedia/Code/ArticleViewController+ArticlePreviewing.swift
  Wikipedia/Code/ColumnarCollectionViewController.swift
  Wikipedia/Code/ExploreCardViewController.swift
Labels: 7.8.0
