Repository wikimedia/wikipedia-ios, pull requests merged in 2025-04, with the labels that each got.

#5229 Check temp account availability per wiki
  WMF Framework/NSManagedObjectContext+WMFKeyValue.m
  WMFData/Sources/WMFData/Data Controllers/Temp Accounts/WMFTempAccountDataController.swift
  Wikipedia/Code/ArticleViewController+Editing.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/EditorNavigationItemController.swift
  Wikipedia/Code/EditorViewController.swift
  Wikipedia/Code/ProfileCoordinator.swift
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Code/WMFLanguagesViewController.m
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 7.7.3

#5246 Fix twn conflicts
  Wikipedia/Localizations/es.lproj/Localizable.strings
  Wikipedia/Localizations/uk.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/es.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.stringsdict
Labels: 7.7.3

#5245 Add end session for temp accounts
  WMFComponents/Sources/WMFComponents/Assets.xcassets/person-circle-x.imageset/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/person-circle-x.imageset/personcirclex.svg
  WMFComponents/Sources/WMFComponents/Style/WMFIcon.swift
  Wikipedia/Code/Temp Accounts/TempAccountsSettingsViewController.swift
  Wikipedia/Images.xcassets/person-circle-x.imageset/Contents.json
  Wikipedia/Images.xcassets/person-circle-x.imageset/personcirclex.svg
Labels: 7.7.3

#5247 Bump version to 7.7.4
  ContinueReadingWidget/Info.plist
  NotificationServiceExtension/Info.plist
  WMF Framework/Info.plist
  Widgets/Info.plist
  Wikipedia Stickers/Info.plist
  Wikipedia/Experimental-Info.plist
  Wikipedia/Local-Info.plist
  Wikipedia/Staging-Info.plist
  Wikipedia/Wikipedia-Info.plist
  WikipediaUnitTests/Info.plist
Labels: 7.7.4

#5248 Strings for activity tab
  WMF Framework/CommonStrings.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/as.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/azb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/be-tarask.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/bgn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/cnh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fo.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/haw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/hrx.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ka.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/kn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ksh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/mai.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/om.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sa.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sco.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tcy.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/xmf.lproj/Localizable.stringsdict
Labels: 7.7.4

#5250 Update activity component
  WMF Framework/CommonStrings.swift
  WMFComponents/Sources/WMFComponents/Components/Activity Tab/WMFActivityTabViewController.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityComponentView.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityView.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityViewModel.swift
  Wikipedia/Code/WMFAppViewController+Extensions.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.7.4

#5249 Add email authentication
  WMFComponents/Sources/WMFComponents/Components/Developer Settings/WMFDeveloperSettingsViewModel.swift
  WMFData/Sources/WMFData/Data Controllers/Developer Settings/WMFDeveloperSettingsDataController.swift
  WMFData/Sources/WMFData/Store/WMFUserDefaultsKey.swift
  Wikipedia/Code/AboutViewController.m
  Wikipedia/Code/HTTPCookieStorage+Migration.swift
  Wikipedia/Code/Session.swift
  Wikipedia/Code/WMFAccountCreationViewController.swift
  Wikipedia/Code/WMFAccountLoginLogoutFetcher.swift
  Wikipedia/Code/WMFAuthenticationManager.swift
  Wikipedia/Code/WMFChangePasswordViewController.swift
  Wikipedia/Code/WMFLoginViewController.swift
  Wikipedia/Code/WMFTwoFactorPasswordViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.7.4

#5251 Temp accounts - Add notifications center fixes
  WMF Framework/Remote Notifications/RemoteNotificationsController.swift
  WMF Framework/Remote Notifications/RemoteNotificationsOperationsController.swift
  WMFComponents/Sources/WMFComponents/Components/Profile/WMFProfileViewModel.swift
  WMFData/Sources/WMFData/Data Controllers/Year In Review/WMFYearInReviewDataController.swift
  Wikipedia/Code/UIViewController+ProfileButton.swift
  Wikipedia/Code/WMFSettingsViewController.m
Labels: 7.7.4

#5254 Update copy
  Wikipedia/Code/TempAccountSheetCoordinator.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/zh-hant.lproj/Localizable.strings
Labels: 7.7.4

#5253 Adjust copy for article history counts
  Wikipedia/Code/PageHistoryFilterCountsViewController.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.7.4

#5255 Update copy
  WMF Framework/CommonStrings.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.7.4

#5256 Bring image back
  Wikipedia/Code/TempAccountSheetCoordinator.swift
  Wikipedia/Images.xcassets/page-message.imageset/Contents.json
  Wikipedia/Images.xcassets/page-message.imageset/page-message.png
Labels: 7.7.4

#5261 Fix copy
  WMF Framework/CommonStrings.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/as.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/azb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/be-tarask.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/bgn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/cnh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/fo.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/haw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/hrx.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ka.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/kn.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/ksh.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/mai.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/om.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sa.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sco.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/sw.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tcy.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/tl.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/xmf.lproj/Localizable.stringsdict
Labels: 7.7.5

#5264 Localisation updates from https://translatewiki.net.
  Wikipedia/Localizations/ar.lproj/Localizable.strings
  Wikipedia/Localizations/az.lproj/Localizable.strings
  Wikipedia/Localizations/diq.lproj/Localizable.strings
  Wikipedia/Localizations/es.lproj/Localizable.strings
  Wikipedia/Localizations/fr.lproj/Localizable.strings
  Wikipedia/Localizations/hy.lproj/Localizable.strings
  Wikipedia/Localizations/lb.lproj/Localizable.strings
  Wikipedia/Localizations/mk.lproj/Localizable.strings
  Wikipedia/Localizations/pa.lproj/Localizable.strings
  Wikipedia/Localizations/sr-ec.lproj/Localizable.strings
  Wikipedia/Localizations/sv.lproj/Localizable.strings
  Wikipedia/Localizations/uk.lproj/Localizable.strings
  Wikipedia/Localizations/zh-hant.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/diq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/hy.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/lb.lproj/Localizable.stringsdict
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.stringsdict
Labels: 7.7.5

#5265 Activity tab prototype
  WMF Framework/CommonStrings.swift
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-edit.imageset/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-edit.imageset/icon.svg
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-link.imageset/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-link.imageset/Union.svg
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-read.imageset/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-read.imageset/icon (2).svg
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-save.imageset/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/activity-save.imageset/icon (1).svg
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/add-images.imageset/Contents.json
  WMFComponents/Sources/WMFComponents/Assets.xcassets/ActivityTab/add-images.imageset/add-images.svg
  WMFComponents/Sources/WMFComponents/Components/Activity Tab/WMFActivityTabLoggedOutView.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityComponentView.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityView.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityViewModel.swift
  WMFComponents/Sources/WMFComponents/Components/Developer Settings/WMFDeveloperSettingsViewModel.swift
  WMFComponents/Sources/WMFComponents/Style/WMFColor.swift
  WMFComponents/Sources/WMFComponents/Style/WMFTheme.swift
  WMFData/Sources/WMFData/Data Controllers/Activity/WMFActivityTabDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Activity/WMFActivityTabExperimentsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Developer Settings/WMFDeveloperSettingsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Experiments/WMFExperimentsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Navigation/WMFNavigationExperimentsDataController.swift
  WMFData/Sources/WMFData/Store/WMFUserDefaultsKey.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AboutViewController.m
  Wikipedia/Code/EditInteractionFunnel.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/LoginFunnel.swift
  Wikipedia/Code/WMFActivityTabViewController.swift
  Wikipedia/Code/WMFAppViewController+Extensions.swift
  Wikipedia/Code/WMFAppViewController.h
  Wikipedia/Code/WMFAppViewController.m
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/ar.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/az.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/fr.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/mk.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sr-EC.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/sv.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/uk.lproj/Localizable.strings
Labels: 7.7.5

#5257 Add persistence for article categories
  WMFData/Sources/WMFData/Data Controllers/Shared/WMFArticleDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Shared/WMFCategoriesDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Shared/WMFPageViewsDataController.swift
  WMFData/Sources/WMFData/Data Controllers/Watchlist/WMFWatchlistDataController.swift
  WMFData/Sources/WMFData/Models/Watchlist/WMFPageWatchStatus.swift
  WMFData/Sources/WMFData/Resources/WMFData.xcdatamodeld/.xccurrentversion
  WMFData/Sources/WMFData/Resources/WMFData.xcdatamodeld/WMFData 2.xcdatamodel/contents
  WMFData/Sources/WMFData/Store/WMFCoreDataStore.swift
  WMFData/Tests/WMFDataTests/WMFArticleDataControllerTests.swift
  WMFData/Tests/WMFDataTests/WMFPageViewsDataControllerTests.swift
  WMFData/Tests/WMFDataTests/WMFWatchlistDataControllerTests.swift
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/AppDelegate.swift
  Wikipedia/Code/ArticleViewController+ArticleWebMessageHandling.swift
  Wikipedia/Code/ArticleViewController+Categories.swift
  Wikipedia/Code/ArticleViewController+Watchlist.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/DiffContainerViewController.swift
  Wikipedia/Code/EditSaveViewController.swift
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/WikipediaSiteInfoLookup.swift
  Wikipedia/Code/WikipediaURLTranslations.swift
Labels: 7.7.5

#5258 Track time spent on articles
  WMFData/Sources/WMFData/Data Controllers/Shared/WMFPageViewsDataController.swift
  WMFData/Sources/WMFData/Resources/WMFData.xcdatamodeld/WMFData 2.xcdatamodel/contents
  Wikipedia.xcodeproj/project.pbxproj
  Wikipedia/Code/ArticleViewController+YearInReview.swift
  Wikipedia/Code/ArticleViewController.swift
Labels: 7.7.5

#5259 Persist session seconds
  Wikipedia/Code/HistoryViewController.swift
  Wikipedia/Code/NSUserDefaults+WMFExtensions.swift
  Wikipedia/Code/SessionsFunnel.swift
Labels: 7.7.5

#5267 Activity tab - Push on editing contributions
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityViewModel.swift
  Wikipedia/Code/EditInteractionFunnel.swift
  Wikipedia/Code/WMFAppViewController+Extensions.swift
Labels: Dependent PR, 7.7.5

#5260 Add rabbit hole tracking
  WMFData/Sources/WMFData/Data Controllers/Shared/WMFPageViewsDataController.swift
  WMFData/Sources/WMFData/Resources/WMFData.xcdatamodeld/WMFData 2.xcdatamodel/contents
  WMFData/Tests/WMFDataTests/WMFPageViewsDataControllerTests.swift
  Wikipedia/Code/ArticleCoordinator.swift
  Wikipedia/Code/ArticleViewController+ArticleInformation.swift
  Wikipedia/Code/ArticleViewController+YearInReview.swift
  Wikipedia/Code/ArticleViewController.swift
  Wikipedia/Code/LinkCoordinator.swift
  Wikipedia/Code/ViewController+ArticlePreviewing.swift
  Wikipedia/Code/WMFFirstRandomViewController.m
Labels: 7.7.5

#5266 Activity tab - Localized string fixes
  WMF Framework/CommonStrings.swift
  WMFComponents/Sources/WMFComponents/Components/Activity Tab/WMFActivityTabLoggedOutView.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityView.swift
  WMFComponents/Sources/WMFComponents/Components/Activity/WMFActivityViewModel.swift
  Wikipedia/Code/EditInteractionFunnel.swift
  Wikipedia/Code/WMFAppViewController+Extensions.swift
  Wikipedia/Localizations/en.lproj/Localizable.strings
  Wikipedia/Localizations/qqq.lproj/Localizable.strings
  Wikipedia/iOS Native Localizations/en.lproj/Localizable.strings
Labels: 7.7.5
